### ISSUE TITLE
Problem with overworld again

### ISSUE THREAD

**Issue by Golgatron** [zmaster587/AdvancedRocketry#100]
Hey my Friend

i have a problem again but now with not duplicate dat datei 

here is the dat datei

http://www.file-upload.net/download-11382552/temp.dat.html

**Comment by Golgatron** [comment]
and the last server log with this bug 

http://www.file-upload.net/download-11382574/2016-03-11-2.log.html

**Comment by Golgatron** [comment]
hello anywhere here?

**Comment by DarkGuardsman** [comment]
I think the author is busy with real life and school. I'll bug him if I see him next in teamspeak.

**Comment by Golgatron** [comment]
thanks

**Comment by zmaster587** [comment]
Sorry I took so long to get back, I've been really busy.  The .dat file appears fine, although is that the fml-server-*.log and not latest.log?

**Comment by Golgatron** [comment]
no sorry last log i dont have now only this two files

**Comment by zmaster587** [comment]
Can you please get me a listing with names and versions of every mod in the instance including the forge version?

**Comment by Golgatron** [comment]
puh.
Okay give me plz a day
270 mods

**Comment by Golgatron** [comment]
<a href="http://www.directupload.net/file/d/4297/oemn79wy_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/160318/temp/oemn79wy.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

<a href="http://www.directupload.net/file/d/4297/fdtrzbmw_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/160318/temp/fdtrzbmw.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by Golgatron** [comment]
10.13.4.1614  this is the forge

**Comment by DarkGuardsman** [comment]
That is a lot of mods, I'm amazed you have not had other problems. As well have not run out of block Ids. I mean you do get 3000+ ids but packs of these sizes can run out. Just out of scientific curiosity can you do a block id dump using NEI. It would be under options in NEI when you have it open in an inventory.

**Comment by Golgatron** [comment]
the block.csv? or other csv files?

**Comment by DarkGuardsman** [comment]
I think the block.csv

**Comment by Golgatron** [comment]
So here the Files block and item but this is not with Rocketry

http://www.file-upload.net/download-11408217/block.csv.html
http://www.file-upload.net/download-11408218/item.csv.html

**Comment by DarkGuardsman** [comment]
You're about out of Ids, I would watch adding any more mods. 

Also @zmaster587 look at that log there are a few ids at the 8000 range. That is outside the 4096 limit that MC normally has?

**Comment by Golgatron** [comment]
okay what can i do now?

**Comment by zmaster587** [comment]
This is the same isse with the sky misbehaving right?

**Comment by zmaster587** [comment]
Is this issue still occuring?

**Comment by Filip-Drapalik** [comment]
I can confirm that we seem to be experiencing the same issue with the sky on our small server - here's what I know:
The issue started when we updated galacticraft (all three files) to 1.7-3.0.12.454 in our custom pack - no other changes.
It's not just the sky, other things also behave as if on the moon - low gravity (though falls from heights that would be harmless on the moon still do fall damage), no sound (since the moon has no atmosphere to propagate sound through)... Luckily there is no "oxygen setup is invalid" suffocation, at least.
After reading this thread we had a look at ID's and we have roughly 3000 block ID's and 8000 item ID's - this may be just a coincidence, but could be worth keeping in mind. In fact, what's the standard limit for item ID's? And would NotEnoughId help there too?

As for the mod list, we have the following in common with what Golgatron posted:
ae2, ae2 stuff, agricraft
bdlib, big reactors, Bookshelf, buildcraft
chicken chunks, code chicken core, cofh core, cofh lib
decocraft, dragon API
electricraft, enchiridion, ender IO, ender zoo, extra cells, extra utilities
flood lights, forestry
galacticraft core, galacticraft planets, gendustry, generators
ichun util, IGW, ic2, ic2 nuclear control, immersive engineering, immersive integration,
JABBA, journeymap
magneticraft, mantle, mariculture deluxe, mekanism, mekanism tools, mekanism generators, micdoodle core, MFR, morpheus
natura, NEI, numina
openblocks, opencomputers, openglasses, openmods lib, openperipheral
pneumaticraft, progressive automation, project red (all except mechanical)
railcraft, redstone arsenal, rotarycraft
security craft, simply jetpacks, steve's carts, storage drawers, sync
thermal foundation, thermal expansion, thermal dynamics
waila, wawla

I'm afraid that doesn't narrow it down much, but it's all I have for now.

**Comment by zmaster587** [comment]
What was the previous build of galactic craft you were running?

**Comment by zmaster587** [comment]
The no sound thing is kinda odd.. I don't mess with the sound at all.  I believe standard limit is 4096 for block IDs.

**Comment by zmaster587** [comment]
Apparently this problem was 2fold, if GC cannot regiser it's moon, it assigns the moon provider to the overworld, and 2, I forgot to not register the dimension if GC is installed.

**Comment by zmaster587** [comment]
You may have to start the server twice to fix it.
