### ISSUE TITLE
Russian language translation propositions.

### ISSUE THREAD

**Issue by EasterncheesE** [zmaster587/AdvancedRocketry#1012]
Hello.

As for now, i have been making the russian translation for Advanced Rocketry and libVulpes for my personal use. There are 2 things i cannot make to work properly, however.

1) I have found out some text is missing from .lang files, exactly: All the machine GUI text, so i don't have a chance to change "missing guidance computer" in rocket assembling machine  to russian "отсутсвует автопилот" for our poor too-lazy-to-learn-english-people. Can you please add the possibility to translate it? As soon as your development is very active, i don't think, that using the IN-CLASS-TRANSLATOR for each version is a good idea. 

2) Please first have some explanation on russian language rules to understand what's wrong for me. The problem is described in the end. 
There is a great difference in russian and english language, such as word endings.
When we say Aluminum Ore and Aluminum ingot, the word "Aluminum" got changed.
E.G. aluminumA ore and aluminumO ingot. That's just for reference, not real example. So many items in our language use male or female sex. And worlds like material name are changed according the "item sex". So, like, all the material endings for ores are the same, but different from ingots.
Your way to code the usage of material names is fancy, cause it helps you not to name each item in your mod, but it makes me translate it in pretty strange way, which looks like i don't actually know russian (or have no idea where this text will be used). I understand that it's a small issue, but any chance we could have the name for each block separately? Then i could have different names for different blocks, without Aluminum(a,o,u)-prefix used everywhere.

**Comment by zmaster587** [comment]
I am slowly adding localizations for various odds and ends as I come through them again.  In all honesty I didn't think about it the first time and the shear amount of issues has been wearing me down.  So it's definatly coming, I'm just a bit slow with it at the moment because trying to get gamplay issues out of the way first.  If you know how to do some code and are willing to submit a PR or two, it would be a great help to me if you could localize these strings using the LibVulpes.proxy.getLocalizedString(str) method.  For machine messages im going with the format "msg.<machineName>.<unlocallizedMsgName>.  If you're willing to wait or are unable to help, I'll get to it when I can.

As for number 2, I am somewhat familiar with latin, which also has gender for different words, so I do get the nature of the problem.  It wasn't something I'd thought about either honestly.  I think what i could do is a fallback system.  It looks for the localized version of the whole thing first like "item.aluminium.ingot.name" and if that's not found then it falls back to the material.<name> and type.<name>  that way the existing system can still be used, but it can be overridden as needed.  I'll work on implementing that tonight.

**Comment by zmaster587** [comment]
I've added the ability to override the names.  So you should be able to add "item.<material>.<type>.name" to name individual items.  So for example "item.Steel.fan.name=Steel Fan2" would rename the steel fan to "Steel Fan2" and so on.  And for blocks you can do "tile.<material>.<type>.name".

**Comment by EasterncheesE** [comment]
Thank you on your reply.
Unfortunately, i'm not familiar with coding anyhow, so i have no chance to fix it. Anyway, that's not a big thing, i always can write a guide for those, who cannot get it while waiting till you have enough time to revise this. 

As for the name override, for now i have solved the problem by simply overriding the names with NEI (with help of minetweaker), which helps me make them whatever i like. Once your awesome mod get another stable beta (like 1.2.5 for 1.7.10), i will definitely grab it and use the new system.

Thank you for the quick response and for such a great mod itself!

**Comment by EasterncheesE** [comment]
Oh. As soon as i do only use 1.7.10, once it's available, i will give it a try immediately.
Thank you on your kind response!

**Comment by Jummit** [comment]
Oh gosh... I have no idea how I should update the German translation. I don't want to start all over again, but how can I merge the new english.lang file in my german.lang so the old elements stay and only the new untranslated ones will be added?

**Comment by zmaster587** [comment]
@Jummit there will be some probably, but nothing nearly this massive again.  This was just moving all of the hardcoded strings to the locale system.

**Comment by EasterncheesE** [comment]
Jummit, there are millions of text-compare-websites over web, that can help you to compare and merge files. Me specifically use TextWrangler APP to do that job. I'm pretty sure notepad ++ has such plugin or built-in function. 
Also, translating 200-300 lines is not such a big problem and can be done in 20-30 mins. When i translate Thaumcraft addons, it takes about 2-3k lines, including the fact that i should regard the line length for in-game viewing.
