### ISSUE TITLE
asteroidConfig.xml  (default)

### ISSUE THREAD

**Issue by nonenothing** [zmaster587/AdvancedRocketry#1025]
<asteroid name="Small Asteroid" distance="10" mass="100" massVariability="0.5" minLevel="0" probability="10" richness="0.2" richnessVariability="0.5">
		<ore itemStack="minecraft:iron_ore" chance="15" />
		<ore itemStack="minecraft:gold_ore" chance="10" />
		<ore itemStack="minecraft:redstone_ore" chance="10" />
	</asteroid>
Explain issue in detail:
**10** ore per asteroid?
Is this some kind of joke or what?

**Comment by artaficialAI** [comment]
That isn't the # of ore per asteroid, it is the ratio of that ore compared to the other ores.  In all the ore in the asteroid there will be 15:10:10 parts iron:gold:redstone.  If the asteroid contained 1000 ore there would be 428 iron, 285 gold, and 285 redstone.  Because of the richness variability and richness the asteroid will only be between 0% and 70% ore, which will be divided along the above mentioned ratios.  The ratios do differ between each asteroid because there is some math going on behind the scene that also slightly alters the ratios for every asteroid.

**Comment by nonenothing** [comment]
That **is** default ore per asteroid - 10 (from 5 to 15).

>  If the asteroid contained 1000 ore

No, it is not. Default mass is 100 only - becouse by default exist only small asteroid.

> there should be ~53 iron,

No, it is not - never be more than 20.

**Comment by zmaster587** [comment]
With default config: ![image](https://user-images.githubusercontent.com/3536685/34546889-09e70d76-f0c5-11e7-96f5-824ce61a379b.png)

last I checked 24 > 20

@nonenothing  The bit where @artaficialAI said 1000 ore was it illustrate a point, using 1000 to make it easier to see.  I've also got no idea where you're getting the 5 from in 5 to 15, 15 i can at least see because it's the chance.  The chance however is not the upper limit for ores in the asteroid, it's there to define a ratio.

Anyway, the default asteroids are designed to be  under a stack per ore because rockets are reusable and fuel is cheap (literally water, which is infinite + energy) to produce once you get the infrastructure.  You can also have multiple in flight at a time.  Asteroid mining by default is also not supposed to be endgame, that's what the laser drill is for.  If you don't like the default config, feel free to change it, that's why it's configurable and not hard coded.

Mass is 100, yes, but there's also a 0.5 variability, so you get masses from 50 to 150.

Given the code in below and given a mass of 125, the most ore you can get in a single asteroid by default is 125*(0.2 + 0.5 - 0.25) = 125*0.45 = 56 total ores per asteroid.  ( I think @artaficialAI forgot the -variation over 2).  At max mass of 150 you can get up to 27 iron per asteroid.

Code is here if you'd like to look for yourself:
https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/util/AsteroidSmall.java#L55

**Comment by nonenothing** [comment]
> and fuel is cheap

and asterchip is **not** reusable and **not** cheap (as distinct from this joke)

> Asteroid mining by default is also not supposed to be endgame

20 iron ore is definitely not endgame.

**Comment by zmaster587** [comment]
The asteroid chip is fairly cheap, data income is passive ( you don't need energy to get data, you can have more than one satellite per data type )

Again, it's not supposed to be end game.  Its supposed to supplement mining so you can get ores and do other things at the same time.

Point two, I put in a ton of work to make it configurable, if you don't like it, feel free to change the config, that's what it's there for.  As far as I can tell, there's not too many people upset with the default as it currently stands and gameplay bugs that cannot be fixed by a config take priority.
