### ISSUE TITLE
Docking Pad Station issues.

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#1031]
Minecraft Version: 1.12.2
-
Forge Version: 2555
-
Advanced Rocketry Version:  AdvancedRocketry-1.12.2-1.2.6-43
-
LibVulpes Version:LibVulpes-1.12.2-0.2.7-24-universal
-
**is this the latest curseforge build?**  Yes

Explain issue in detail:

Launching a rocket from one pad on a space station to another has twoish results:
1)  Unmanned rockets fly up until you terminate the game session, resume their landing on reload.
2)  Manned rockets dump you off near the destination coords when it reaches y=1000.
  2a)  If you use a teleportation item to another dimension, you reboard the rocket  and it moves to the teleportation destination.
  2b)  If you log out and log back in, it does a proper landing.

Station ID chips for any station makes a rocket fly to the planet below the station, not to a different station if the ID chip is for another station.

In good news, a normal rocket would not take off to a different space station that is not in the same planet system.  Additionally, warp core-enabled rockets also report the same issue as a normal rocket in different solar systems (the error says "not same Planet System" though).   The warp-enabled rocket does fly if the stations are in the same solar system, however after it did 2b, the rocket was MIA and I was not on it.

I'm working on a pack that does not have item teleportation in any easy capacity, so trying to make rockets do the logistics of moving materials automatically.  I don't have a solution for moving items between solar systems.

Please do not hide docking pads that have linkers in them.  It makes it hard to manually put a rocket on the pad if there are none setup on the route yet.

Thanks,
IMarv

PS  Is there a command to list the locations of all rockets?  It would be nice to know where these missing rockets went.

**Comment by zmaster587** [comment]
Gonna try take two for fixing player rockets, Im thinking it may be related to the method used to teleport the player, gonna try unmounting, teleporting and remounting.

As for unmanned rockets, have you attempted loading the chunk they are to land in (teleporting there and waiting for a minute or two for it to descent usually works)?  Or have you at least verified they stop motionless at 1000 at the descenting coords?  I've not been able to replicate it totally halting on my end.

Station chip issue: noted and will investigate

Warp core issue replicated, working on a fix.

Not hiding rockets with linkers in them will require a deeper change since the reason they don't show up is because they're removed from the list to allow automatic landing and the pads that show up are just pulled from that list.  It's doable, but will take a bit of time.

Right now there's no command to list location of missing rockets.  I can add one, but since minecraft will not report entities in unloaded chunks, Im not sure how helpful it'll be if the rockets wander off to chunks that are not loaded.

**Comment by IMarvinTPA** [comment]
The unmanned rocket was to the same station that it took off from, just a pad about 12 blocks away.  I'm pretty sure the chunks were loaded.  I forget what it did exactly after it went up past 1000.

Perhaps a log file/console spam that records the location of where a rocket goes to whenever it completes a launch.

**Comment by zmaster587** [comment]
Alright, I didn't test on a station, only on planets, maybe it's related to that since stations are handled differently than planets.

That'd be a possiblilty, I could add a debug config option so it doesn't spam normal players.  If it does come down to a chunkloading issue I may just make rockets in flight keep chunks loaded similarly to the gas harvesting drones.

**Comment by zmaster587** [comment]
Station to station should work now, station to same station tested and works.  Planet to same planet tested and works for both cargo and player travel.

**Comment by IMarvinTPA** [comment]
Did I do something wrong? 
https://youtu.be/lXc6BZ7FfG4

IMarv
