### ISSUE TITLE
Realistic Terrain Generation support

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1035]
RTG: https://github.com/Team-RTG/Realistic-Terrain-Generation
This mod really enhances the feeling of the world and exploring it is more fun. But unfortunately AR planets don't have this world gen. When you create a new world with RTG you can change the generation type from 'Default' to 'Realistic'. The main dimension generates with this option, but other dims not. This is the same with all other generation types like superflat or amplified. Is it hard to change the gen on other planets to the selected type?

A screenie to give you a little preview of how planets would generate: https://imgur.com/SnFDITa / https://minecraft.curseforge.com/projects/realistic-terrain-generation/images

**Comment by zmaster587** [comment]
Eventually I'd like to have planets support arbitrary generation types.  One of the main issues I run into at the moment is keeping track of biomes allowed to spawn

**Comment by Jummit** [comment]
one thing i don't understand is that if you install BiomesOplenty and select its terrain generation type then it works on all planets. But why?

**Comment by zmaster587** [comment]
the advanced rocketry planet generator looks through all available biomes then selects biomes with temperatures and humidities matching the planet's characteristics.  It's that exact feature that makes it hard to make the planets compatible with other terrain generators.  Otherwise you'll get a hot planet with snow biomes and cold planets with deserts and cacti.

**Comment by Frontrider** [comment]
I have some ideas for that, but my current priority is to get a larger variety of "alien" biomes in first.
Mars and moon already got revisited, and a "europa" type world AKA. Sea underneath a sheat of ice is in the works. Having some setbacks, since I also attempt some refactoring so the code is easier to read.
Than I have to do some testing on my custom, variable biome class. Testing will be done via the implementation of extra biomes.

I also want do some fancy stuff with caves (eg set fluid material, so you can say that this biome/planet should have liquid glowstone instead of lava).

Also, the Biome Provider needs to be sanitized before we can do that, because right now its a trainwreck. Its more than willing to generate the decorations of an ocean, on top of a mountain. 
And thats gonna be hard to figure out, since mc's original can not be used as a template, because it does not support a variable number of biomes. (its all math what only they understand)

**Comment by zmaster587** [comment]
@Frontrider it doesn't help that the code is obfuscated, the variables may have meaningful names in the original source.

On the note of custom terrain generation and getting around a lot of the limits, https://github.com/PG85/OpenTerrainGenerator seems to do everything custom I think.  I was playing around with it the other day and all the biomes I walked through reported as plains, but the generation between areas was vastly different despite displaying the same biome.

**Comment by Frontrider** [comment]
I'll look into it. It could actually be the thing to solve the issues I'm having.

**Comment by Frontrider** [comment]
The reason why you see "Plains" on every biom, is because the "getname" method on the Biome class is final, so it can not be overridden.

Is it okey, if I just use asm on that method (So I can override it to print out the custom name for that biome)? if yes, can you give me some mterial on how the xml configs work in this mod? Or just point me at a class to check out?

**Comment by Frontrider** [comment]
This commit has the Biome base, if the direction is useable in your opinion, than it can be merged.
https://github.com/Frontrider/AdvancedRocketry/commit/9fd1a646923ab926c9371f1e02b2df15f5cd6c10

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
