### ISSUE TITLE
Building a new Station, undocumented need to be "built" in the right place.

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#1049]
Minecraft Version: 1.12.2
-
Forge Version: 2555
-
Advanced Rocketry Version:  45
-
LibVulpes Version: 24
-
**is this the latest curseforge build?**  Yes

Explain issue in detail:
I "built" station 2 on "Earth" in the station builder.
I flew to another solar system using station 1.
Landed the rocket with a satellite bay to a planet.
Put the second ID chip and package in the rocket.
Tried to take off, and it complained that the destination was not in the same planetary system.

I call foul, since the station is not currently anywhere yet.

IMarv

**Comment by nonenothing** [comment]
Sure thing - station (dimension) N2 in fact already existed at orbit of Earth.

**Comment by zmaster587** [comment]
It shouldn't make a difference, I'll take a look

**Comment by zmaster587** [comment]
I was unable to replicate the error preventing takeoff, however it created a space station in perpetual warp instead.  Odd indeed.

**Comment by zmaster587** [comment]
Because the station's orbiting body is defined by the dimension you take off from, if you take off from space, then the station ends up orbiting space rather than the planet the station is orbiting around.  That being said, I still cannot figure out how you'd get destination not orbiting same planet unless the space station was already built.  All space stations that are unbuilt have their parent planet set to -1.

**Comment by zmaster587** [comment]
@IMarvinTPA Did you close the game at any point between creating the space station and attempting to get there?

**Comment by IMarvinTPA** [comment]
I am not sure if I restarted the game.
My space station builder machine is on the Overworld.  I built it there.
I put the chip and package into the rocket, then took them out because I didn't want to accidentally put it there.
I put them in an Immersive Engineering crate, and took that with me.
I flew my existing station with a warp core to a Wolf planet.  (In this case it was assigned to 111 which is the Lost Cities dimension)
I flew my main rocket to the planet.
I got it all set up to put the station in orbit of the Wolf planet.
It said NO.
I took everything home with me.
I then launched it to orbit over the Overworld where it allowed me to.

IMarv

PS, I'm glad I didn't put the Nether as a planet in any of the systems.

**Comment by zmaster587** [comment]
Alright, I changed it so that if it's launched from a station that it'll use the planet the station is in orbit around.  I've also enforced dimid being invalid if the station is not built yet.  Side effect is that unbuilt stations that actually have been built upon (legacy stations, imported from pre 1.2.x) may run into some issues, however warping at least once with the station will force it to the 'built' state.

I've tested and verifed that building the station works, in addition to fixing going from station to station using the station ID chip and not the linker.

**Comment by IMarvinTPA** [comment]
BUT I DIDN"T LAUNCH FROM A STATION!
I took everything down to another planet than where the builder was, then launched from there.
I appreciate making it work properly for launching a station from a station though.  That means I can just put all of my new gear infrastructure on a station and move it around as needed.

**Comment by zmaster587** [comment]
Either way, it's the same issue in the code that's preventing you from launching the station.  If it were launched from a planet, and it wasn't initiallized to -1, it would throw the same error message.  I'll test that too just to verify.

**Comment by zmaster587** [comment]
Tested the following with the modified build:
Build space station on overworld
flew to station 1
used station 1 to go to another star system
built rocket on the surface of a planet in the other star system
launched the rocket and rode it to the new space station
the new station was orbiting the planet the rocket took off from in the 2nd star system

**Comment by IMarvinTPA** [comment]
Interesting test.  I didn't build a rocket on the second planet, I just used the existing rocket that I landed on the alien planet.  I'm not sure why it would matter where the rocket was built though.

**Comment by zmaster587** [comment]
The rockets do not save the state of where they came from, nor do they need to, any state is kept in the chip in the guidance compute.  But since you said you swapped it out for the 2nd id chip, that would be a non issue anyway.
