### ISSUE TITLE
How do planets choose biomes?

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1055]
I was just wondering if every planet randomly selects which biomes will generate on it. Or does it even generate biomes or has it its own generation code for planets?

**Comment by zmaster587** [comment]
The biomes are chosen here https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/dimension/DimensionProperties.java#L844  Basically pulls random biomes that fit the planet's characteristics.  Because it's only a subset (not supposed by vanilla), the terrain generator also has to be custom to account for that.

AR's terrain generator is basically a copy of vanilla's with a method to limit the biomes shoehorned in and some decoration changes.  (craters, geodes, villages removed, strongholds removed, random lava and water pits removed, etc)
