### ISSUE TITLE
Question: Pressurizing Massive Stations

### ISSUE THREAD

**Issue by TheCowKing-moo** [zmaster587/AdvancedRocketry#1093]
I've been searching the internet for tips/solutions to this to no avail. I didn't see any links to a forum / discord so my apologies if this is not the right space to ask questions.  

I'm trying to pressurize a space station with a total volume of about 2 million blocks with multiple different sections comprising different shapes. The biggest section is the real killer, a sphere with a volume of about 900k blocks and multiple floors cutting through. 

I was hoping maybe someone here could give me some tips/tricks to modify the station in such a way that doesn't kill my servers TPS. 

Maybe a config change to have the station only check for holes only once a day or something to that effect? Multi-block oxygen vent machine that requires insane amount of power / new resources to change the air regardless of seals?

I'm doing my best here to try and not just change the config to not require air.

Any advice would be appreciated.

**Comment by zmaster587** [comment]
setting atmosphereCalculationMethod to 2 or 3 may help somewhat with the TPS as it will spawn off a seperate thread to run the calculations rather than hang the server thread.

Something like this is really a difficult problem because no matter what, for the O2 system to work, it needs to check the entire volume to determine whether or not a leak exists and that's gonna take CPU time.  That's why the limits exist in the first place.    The checks are incremental, so that if an area is sealed and you break or place a block that doesn't cause it to unseal, there shouldn't be much overhead.

The problem with checking once a day is still that it'd still cause a massive lag spike.  Are you looking for survival solutions or would a creative mode solution be ok?

**Comment by TheCowKing-moo** [comment]
I was trying to shoot for survival methods, but its looking like its not going to be a possibility. I really should have thought this through....

The creative O2 provider sounds ideal and a survival element could be implemented to make it much more expensive (like 10k rf/t) vs the oxygen vent/scrubber setup in order to make it something only people in similar situations would want to use it. 

Love your mod and appreciate the time and work you put into it.

**Comment by CTH999** [comment]
I don't know if this would work, but maybe you could make the station in 2 different locations. The one that you are in, and another one that is just (Any one block) Instead of all blocks, and void instead of air. It would then check the walls, and only the walls. Also, doors might be cobblestone instead of stone if it's open. That way it can see if it's open, and also only check the walls.

**Comment by smmarkvard** [comment]
I have a lot of trouble adding villagers in the configs so they won't die in vacuum

**Comment by scribbler957** [comment]
I have a suggestion. What about a high-volume O2 system that could bypass the problem by requiring duct work/air vents that would only check within a limited (configurable) range (say 16 block raadius). This would limit how much any 1 duct would have to check and more realistically simulate pressurizing and maintaining an atmosphere in a large area. Note the term duct isn't meant to imply conduits or anything, just a node for O2 distibution (although actual ducts would be cool).
It won't stop heavy resource use on a server, but that's always a problem with giant modded builds, plus the distribution system could be made expensive or killed by the op. Either way, it would probably be better than creating 100 smaller areas each with it's own O2 system, cartridge refurbisher, etc. Plus the pathing issues in that kind of environment.
The question is whether the O2 check would act as little bubbles that stick to walls (forcing each unit to check the entire sphere) or work on an air "map" (which could prevent duplicate checks at the expense of overhead).

@TheCowKing You have got to share some pictures. :)

**Comment by derrekschuurman** [comment]
@scribbler957 
I fear that this may be a little bit underwhelming for you as all I have left are pictures of it are unfinished and in pretty rough shape.  A lot of work was done after these pictures were taken unfortunately. 

[link](https://photos.app.goo.gl/cDYdXNo6DnPABhq3A)

That first picture there where you can see the whole station is touching y = 1 and the top is hitting whatever the ceiling was if I recall correctly. 

I don't even have any pictures left of my Advanced Rocketry setup :\

**Comment by TheCowKing-moo** [comment]
@scribbler957
I fear that this may be a little bit underwhelming for you as all I have left are pictures of it are unfinished and in pretty rough shape. A lot of work was done after these pictures were taken unfortunately.

[link](https://photos.app.goo.gl/cDYdXNo6DnPABhq3A)

That first picture there where you can see the whole station is touching y = 1 and the top is hitting whatever the ceiling was if I recall correctly.

I don't even have any pictures left of my Advanced Rocketry setup :\

**Comment by Dominic-Kua** [comment]
Also you tagged the wrong @thecowking :P

**Comment by scribbler957** [comment]
@Dominic-Kua Yup, got truncated on my system. Oops.

**Comment by scribbler957** [comment]
@TheCowKing-moo Mostly empty or not, I think it's cool and quite the undertaking if built in survival. I think I'm going to build an Acclamator in E2E...
