### ISSUE TITLE
Oxygen Gas Charge Pads

### ISSUE THREAD

**Issue by TheCowKing-moo** [zmaster587/AdvancedRocketry#1111]
Minecraft Version:
-1.12.2
Advanced Rocketry Version:
-AdvancedRocketry-1.12.2-1.2.6-52
LibVulpes Version:
-LibVulpes-1.12.2-0.2.8-27-universal
Explain issue in detail:
Gas charge pads are taking a very long time to charge up oxygen. Hydrogen charging pads seem to be fine, but oxygen pads will take up to 2 min to fill up a default suit tank and then will just stop. Having extra tanks in your suit seem to just not be filled at all.

**Comment by zmaster587** [comment]
There was actually an issue with H2 filling faster than it should, #1088, resulting in a duplication issue.  The tanks other than the designated slots don't fill by design.  The problem is that then players would need to be careful about when to stop otherwise they could accidently crowd out the hydrogen.  Granted, O2 filling does need to be sped up a bit.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
