### ISSUE TITLE
Configurable time travel between planets

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#113]
The time travel between different planets could be slightly different by default (just a few seconds) but if you multiply the time (maybe through config file?), the difference increases.

**Comment by zmaster587** [comment]
That would be doable

**Comment by dmodoomsirius** [comment]
For that you will need a tardis rocket

**Comment by Tarkov** [comment]
Maybe using the "orbitalDistance" of the XML config file you could have a number for the time required to travel between any planet.

**Comment by zmaster587** [comment]
What I plan on doing is using both the orbitalDistance and the angularOffset variable, convert from polar to cartesian coordinate then use the distance formula to find distance, then multiply that by some number and then by a number specified by the config to get the total delay in ticks.  Otherwise it'll seem kinda strange that the planet on the other side of the sun takes less time to travel to comared to one near the edge of the solar system.

**Comment by Tarkov** [comment]
Ooh! I see you have everything under control here. I am looking forward to spend some time looking through the window of the rocket while I approach the moon.
