### ISSUE TITLE
Rocket dupe, thermos server. Suggestions on fixing the issue without involving Thermos API.

### ISSUE THREAD

**Issue by EasterncheesE** [zmaster587/AdvancedRocketry#1147]
Hello. First of all, i know the author of this awesome mod show very little support to Thermos users and it's not in priority. And similar topic has already been closed on issues. I just want to propose a way to fix or help with this issue also adding more functions to Advanced Rocketry mod.
Server info - 1.7.10, Thermos based.

As for now, the rockets can be easily duped on thermos (and bukkit) servers with just flying back to station from some other dimension (not from overworld). I know, it's been Thermos problem, as author stated Forge servers don't have this problem. However, Thermos is pretty popular and helping to solve this issue is greately appreciated.

As soon as you don't want to check API and find out why thermos behave so stupidly (and i clearly understand that it's not your job to check the shitcode of somebody else), can you please check if you can implemet some "hacks" that will help to diminish the problem?

Is it  possible to make a config option to show the whitelist/blacklist of blocks, possible for rocket and station assembling? This, by the way, can help a lot with people, trying to add IC2 macerator to rocket thus crashing the server.

**Comment by EasterncheesE** [comment]
This is not mainly Thermos compat issue. The problem of assembling the rocket with macerator making crash does also exist on Forge, without bukkit.

My suggestion will both help address the issues of Thermos and Forge with rockets.

**Comment by EasterncheesE** [comment]
Please remove Thermos Compat tag as it's not only thermos issue, thus shouldn't be considered as lowest priority thing.

**Comment by CTH999** [comment]
However, you have to admit it has to do with Thermos. Also, it's there mod. If you add it in, they'll be happy. However, if you don't, then you can't blame them for not adding it in immediately.

P.S. What is Thermos?

**Comment by zmaster587** [comment]
Thermos is a bukkit compat layer essentially, so it's kinda the same thing.  If there's two seperate issues, please create two seperate reports, tagging is a primary reason why.

The problem with fixing the thermos issue is that I cannot diagnose the problem without spending a lot of time looking at their backend, even if the fix is in AR itself.  If I knew exactly what Thermos did that causes the issues, I could have a fix in 10 minutes.  From what I've gleaned from a surface look in the past (an hour or two of time) it appears that they do some override in teleportation/dim changing code.  The code that transfers the rocket from world to world is quite literally a copy of vanilla TP code with a method to call the built in teleporter on any riding entity.

If what I suspect is happening, is actually happening (Thermos using an ASM transform to modify teleportation code of Vanilla minecraft classes), it would be impossible for AR to even make a fix that does not involve just getting rid of rockets or some fairly deep Thermos support.

I will go ahead and add the blacklist now though.

**Comment by EasterncheesE** [comment]
Thank you on your reply. Also, many thanks for Thermos API explanation.

Please see the crash-report from singleplayer 1.7.10. Mod version is 1.2.5 (not the latest alpha build)
Forge 1614. 
https://pastebin.com/2f987Vsp

For now on, i added the Thaumcraft mirror to the rocket assembling pad and pressed "build".
As for now, i can say that any mod-related tile entity (like machines, storages etc) make a CTD with "ticking block".

That's why i did write about 2 things in the same post:
1) My sugestion will help with those crashes on Forge
2) It will help fix that duping issue Thermos have without involving the digging into Thermos API.

Means if you agree to implement it, you address 2 things with 1 action from your side.
