### ISSUE TITLE
Cannot stay inside the rocket

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#115]
When I build a rocket and get into it, it places me above the seat but at the level of the highest block of the rocket. It is usually a couple blocks over the seat, but half outside.

**Comment by zmaster587** [comment]
I think this may have been fixed by https://github.com/zmaster587/AdvancedRocketry/commit/0bd524fea805780e1e5fbb2977696971ffee0d2a
I'm going to leave this open, if it occurs in the (near future) 0.5.2 release, let me know and post a screenshot.  If it is fixed in that build it would be kind of you to also notify me via this post.

**Comment by Tarkov** [comment]
Sure, I´ll let you know.

**Comment by Tarkov** [comment]
I have already tried the new update. Now, it always puts you two blocks above the seat, no matter the other blocks of the rocket. Much easy to deal with it in the building of the rocket.

![2016-05-23_13 43 15](https://cloud.githubusercontent.com/assets/19404111/15469972/d143c908-20ed-11e6-8333-bb6c8cd69bc5.png)

**Comment by zmaster587** [comment]
Investigating...
