### ISSUE TITLE
Rocket becomes invisible and gets stuck when descending

### ISSUE THREAD

**Issue by RiggedToExplode** [zmaster587/AdvancedRocketry#1158]
Minecraft Version: 1.12.2
-
Forge Version: 14.23.2.2618
-
Advanced Rocketry Version: 1.2.6.-55
-
LibVulpes Version: 0.2.8.-27
-
**is this the latest curseforge build?**
The latest build for 1.12, yeah.

<Not a crash>
Explain issue in detail:
I will build a rocket and fly to another planet or space station, only to get stuck in the same spot above the planet/station without the rocket visible below me. The altitude and velocity bars will change, but nothing else will happen and I have to /kill and try again. This seems to only happen on the first flight to the planet/station, though I haven't tried enough times to confirm that.

I can provide a mods list if needed, because I am playing Advanced Rocketry in a custom built pack via Twitch.

**Comment by RiggedToExplode** [comment]
I did three tests with just AR and libvulpes, and everything seems to works fine.

I tested it with all of my mods, and nothing happened at first. Flying to the moon worked, but on my way back to Earth the glitch appeared. I managed to get a recording, which will be attached alongside a .txt file containing the list of mods and the log, in case you need it.
[Mods List.txt](https://github.com/zmaster587/AdvancedRocketry/files/1737995/Mods.List.txt)
[Game Log.log](https://github.com/zmaster587/AdvancedRocketry/files/1737996/Game.Log.log)

[Video is on Google Drive because Markdown doesn't support MP4](https://drive.google.com/file/d/1EbqztBsujcUr7Nx4Hd-U4oATnK8VvoSA/view?usp=sharing)

**Comment by zmaster587** [comment]
From the video, it looks like the state on the integrated server is different from the state on the client.  this can happen if a packet isn't recieved properly about player tracking, the server is lagging, etc.

Would it be possible for you to go through them and check, unfortunately I do have nearly 300 issues to go back through, but i would like to at least ID the mod(s) causing the problem so a possible resolution can be made.  If you would be able to test I'd really appricate it (I'd suggest something akin to a binary search, start with half the mods, if it's not broken, switch to the other half of the mods, if it is broken, remove half the mods currently in use, repeat until one or two are left).

I don't see anything in particular that stands out on the mod list.  If I had to take a guess I'd say maybe Vic's Modern Warfare Mod (mostly because there's some exceptions with regard to player tracking being thrown from this mod around the time the rocket changes dimensions.  So I'd say this is the one with highest certainty), malisiscore, Quark, or foamfix, but it may be something else.

The onRocketLanded event from AR is throwing some errors too, but that's only run when the rocket has actually touched the ground and the only thing that handles is changing the skybox from a planet skybox to the overworld skybox.

**Comment by dillydirkes** [comment]
I have the same problem and the portal gun mod (and all its dependencies) is the only mod in your mods list that i also have installed, it does make sense also because the portal gun mod some way interacts with rendering because you can see through the portals, also has I've had this happen when i built the rocket on the launch pad. just throwing that out there

**Comment by zmaster587** [comment]
I do know there was some packet ordering issues that were fixed within the last two weeks, it's possible that that may have fixed it since it depends on the block data for the rocket existing when the rocket is built.  I can say I've experienced it occationally, but I cannot replicate it on demand in the past, tho last time I saw it myself was in MC version 1.10.2.

With the portal gun mod installed, does it happen every time, or just sometimes?

**Comment by dillydirkes** [comment]
well right now i can't even get my rocket to build, i am running 1.12.2 and it happens every time i have forge 14.23.5.2775 heres a list of my mods: SecurityCraft, Buildcraft, crayfish device mod, crayfish furniture mod, valkyries warfare, computer craft, advanced rocketry 1.4.0 (of course), LibVulpes 0.2.8-27-universal, stupid things mod, compact machines, placeable items, GitWeb builder (for the device mod), and ichunutil which i forgot to uninstall i hope this helps. I'm kinda new to github sorry

**Comment by zmaster587** [comment]
@dillydirkes Does the issue occur with only advanced rocketry installed, if not, what is the minimum required set of mods to replicate the issue?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
