### ISSUE TITLE
Terraformer still not changing overworld atmosphere.

### ISSUE THREAD

**Issue by Tedyhere** [zmaster587/AdvancedRocketry#1170]
Minecraft Version:
- 1.12.2
Forge Version:
- .2617
Advanced Rocketry Version:
- 1.2.6-57
LibVulpes Version:
-0.2.8-27
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------------------
Crash Report:
na
----------
Explain issue in detail:
After testing again with newest build, the Terraformer still does not seem to work in the overworld.  I will do more testing if needed.  Works fine on the moon, I did check the config and changed line 112
allowTerraformingNonARWorlds to true.  If you need me to do more testing I am more than willing.

**Comment by Axieum** [comment]
Yeah, a modpack I am helping develop heavily relies on this atmosphere terraformer (since the story is restoring a dead planet; also, we are trying to figure out how to get a biome that isn't Ocean [since the world only has wasteland biome in it, help much appreciated!]). 

We cannot get the terraformer to work on the overworld (it just lights up blue and does nothing).

**Comment by zmaster587** [comment]
looking into it

**Comment by zmaster587** [comment]
There was an extra check, I must also mention that due to the fact the overworld uses its own provider for terrain generation, the terrain generation in the overworld won't be effected, and there's not really too much I can do about that without risking breaking a lot of mods.

As another note, the biome slot thingy in the terraformer UI has been moved down and the missing texture is fixed in the next build of libvulpes

**Comment by Tedyhere** [comment]
Seems to work now.. Atmosphere has gone from .15 to .17 so far.. thank you

**Comment by Tedyhere** [comment]
Ok Fixed my issue.. it was the asteroidConfig.xml file.  I had an open <asteroid> tag without a closing </asteroid> fixed that and the world loaded up fine.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
