### ISSUE TITLE
Texture missing with tiny progression installed

### ISSUE THREAD

**Issue by cabbby** [zmaster587/AdvancedRocketry#1176]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.2.2611
Advanced Rocketry Version:
- 1.12.2-1.2.6-57
LibVulpes Version:
- 1.12.2-0.2.8-27

**is this the latest curseforge build?**
yes

fml-client-latest.log:
https://pastebin.com/dXPjFwF2

only Tiny Progression installed except libvupes & advanced rocketry

**Comment by dmodoomsirius** [comment]
very similar to #1174

**Comment by cabbby** [comment]
yes. looks like something goes wrong with ModelLoader. from the log

**Comment by zmaster587** [comment]
3 things, that log always prints, is only related to nitrogen and the astrobed, and because MC is designed to work with texture packs that may or may not have a given texture included, if it's a problem with loading models using vanilla's model loader, that indicates a problem with vanilla/forge itself.  Given the fact that textures work fine in AR without other mods installed despite printing those same errors, I think it unlikely that vanilla/forge is playing a part.

While testing with other mods (#946), I have found the textures are indeed properly loaded, so it appears it is presumably deleted or some other manipulation occurs after the original texture loading event.

**Comment by zmaster587** [comment]
Does this issue still exist in build 60?

**Comment by cabbby** [comment]
yep I have tested again with the new build and the problem still exists

**Comment by wamc2017** [comment]
Have you tried the beta version (1.12-3.2.10 - Beta) of TinyProgression?
I only have this issue with tinyprogressions-1.12-3.2.6...

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
