### ISSUE TITLE
Missing Stars

### ISSUE THREAD

**Issue by JoeSGT** [zmaster587/AdvancedRocketry#1187]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.2.2615 
Advanced Rocketry Version:
- 1.12.2-1.3.0-60
LibVulpes Version:
- 1.12.2-0.2.8-27
**is this the latest curseforge build?**
no 1 version behind
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
when i load up singleplayer it crashes with this and tell me in the logs to report it 
in the logs is a said this 
```
[advancedrocketry]: !!!!!!!!!!!!!! An error has occured saving planet data, please report to the mod dev with the entire fml-latest.log file!  This report may contain information relevent to solving a longstanding bug.
```
ERROR:  https://gist.github.com/JoeSGT/4df49a42dbed61be37124522684f3f95
Fml-junk-earlystartup: [fml-junk-earlystartup.log](https://github.com/zmaster587/AdvancedRocketry/files/1776994/fml-junk-earlystartup.log)

**Comment by zmaster587** [comment]
Is this your first time loading up the world with the mod?  Had you just changed a config?  or did this seemingly come out of nowhere?

Also, would you be able to upload a copy of the "saves/New World----/advRocketry/planetDefs.xml" and saves/New World----/advRocketry/planets.dat file as well?

**Comment by JoeSGT** [comment]
when i updated the mod to 1.12.2-1.3.0-60 i was at 1.12.2-1.2.6-54 the config is all default
i didn't mess with it, and also this came out of nowhere 
http://www.mediafire.com/file/0t8ad7cdg834xgp/planetDefs.xml
I don't have planets.dat but only planetDefs.xml

**Comment by zmaster587** [comment]
Are you sure you uploaded the right file?  This is 31KB of just the null character, can you verify this on your end?

**Comment by JoeSGT** [comment]
Yes it is null when i attempt to open it with botepad++ i assume needec something else to open it, but i guess i was wrong

**Comment by Tedyhere** [comment]
Same Issue
Forge 2624
Advanced Rocketry 1.3.0-61
LibVulpes 0.2.8-27

Error
https://pastebin.com/2xV3Z6CE

planetDefs.xml
https://pastebin.com/TdwvEUSv

I do not have a planets.dat file either in save/world/advRocketry I do have a temp.dat file.. I will upload that instead.

https://drive.google.com/open?id=1lVhK1fJkMhyMZs29V3wsuvm2eHQ0L_0n

Forge Log
[fml-junk-earlystartup.log](https://github.com/zmaster587/AdvancedRocketry/files/1778735/fml-junk-earlystartup.log)

**Comment by scytherswings** [comment]
This may be anecdotal, but I saw this error also after my server ran out of disk space. I thought it might have been caused by a partially written `temp.dat` file. Now my server is crashing for a different reason. Looks like my `planetDefs.xml` might be corrupted too.

**Comment by zmaster587** [comment]
@JoeSGT That's very strange...  I've got no idea how that could even happen in all honesty.  A large portion of the data written is hardcoded strings, so Im thinking the underlying system for the fileStream in the JVM itself broke, or maybe even the system level commands.  I really don't know.

@Tedyhere Sorry for the delay, I meant to say temp.dat, I made a mistake, sorry.  Also I looked over your crash report, it looks to be caused by a syntax error in the asteroids file.  Judging by "config/advRocketry/asteroidConfig.xml; lineNumber: 22; columnNumber: 4; The element type "asteroid" must be terminated by the matching end-tag "</asteroid>"."  You may be missing an ending tag?  Which looks like the issue cascaded into the planetDefs loader as well.

@scytherswings I think you're probably spot on with the issue there.  I also think it's very likely that the file wasn't fully written.

**Comment by Tedyhere** [comment]
I saw that and meant to reply with the fix I found for my particular issue.. dang xml
