### ISSUE TITLE
DIMID causing missing and buggy planets

### ISSUE THREAD

**Issue by epicdude312** [zmaster587/AdvancedRocketry#1199]
Minecraft Version: 1.12.2

Forge Version: 14.23.2.2624

Advanced Rocketry Version: 1.12.2-1.3.0-61

LibVulpes Version: 1,12,2-0.2.8-27

**is this the latest curseforge build?** Yes

Explain issue in detail: When I use the DIMID tag in my planetDefs.xml file, most of my planets are in the wrong star system or missing altogether. Some moons also disappear. Also, when I go to the planets, they do not follow what I had set in the XML file -- for example, a moon that is supposed to be rocky and barren is heavily forested. I won't paste the XML file here, because it clearly has something to do with the DIMID tag itself.

Mods installed:
- Advanced Rocketry
- Biomes O' Plenty
- Immersive Engineering
- RFTools (but not RFTools Dimensions)
- All 4 Thermal mods
- All mods required to run those mods (e.g. CodeChicken Lib, Redstone Flux, libVulpes)

**Comment by dmodoomsirius** [comment]
Can you Upload a copy of your planetDef.xml and the temp.dat in a zip to say either dropbox or google drive and link that here?

**Comment by zmaster587** [comment]
Planets in the wrong starsystem is not DIM related, but hierarchy related, the hierarchy is solely determined by the ordering in the planetDefs.xml rather than the dimid tag, so I would say it's highly relevant.  A few additional questions, are you using a planetDefs.xml file in the config folder, if so did you change the one there or in the <world>/advRocketry folder.  Second, when exploring these worlds, did you make sure you loaded new chunks after you made the changes.  AR does not delete or modify existing chunks when a change is made.

If this occured when modifying the planetDefs.xml on a pre-existing world, I may also need the xml file you modified from, since it's possible it may be a problem with loading and modifying an existing save.

**Comment by C1ffisme** [comment]
Okay, I tested this myself, and I can confirm that the DIMID tag does some strange things...

In my XML file, I set up 6 planets around the Sun, Mercury to Saturn. Earth and Jupiter had 1 moon and Saturn had two. I also set up a few other stars, including a planet around another star, Proxima Centauri. I set up Proxima b with a DIMID of 4, which would have otherwise been reserved for Earth's moon.

First off, when starting the game, there was no moon orbiting the Earth. Secondly, and probably the most strange, Proxima b was orbiting the Sun, and not Proxima! Strangely though, it wasn't orbiting the Earth despite the fact that it was overriding the dimension spot where the moon would have been. Strangely, when I clicked on the Proxima star, the planet was orbiting Proxima as well!

But it doesn't end there. I teleported to Mars and found a Moon biome waiting for me, instead of a Hot Dry Rock biome, which was what I had set it to. This bug didn't seem to affect any other planets, though.

Lastly, and while it might be unrelated, I found the strangest terrain on Proxima b... Biomes seemed to not have their usual effect on the height of the terrain, because I found an ocean above sea level!

![2018-03-08_19 54 40](https://user-images.githubusercontent.com/9893266/37186779-c17c3dac-230c-11e8-9124-3263a8815998.png)

(This might be the forested terrain described in the issue.)

So yeah, weird things happen with this tag. Just for the sake of it, I'm going to start another world without using the DIMID tag on Proxima b just to see if this last issue is related.

If you could provide some information, like more specifically which biomes are wrongly spawning on planets, that would be very helpful. And just for the sake of it, I still want to see your XML file so I can fully reproduce this issue.

**Comment by C1ffisme** [comment]
Okay, I don't know if this is good or bad news, but after removing the DIMID tag from Proxima b, the biome height bug and Moon-biome Mars bug still remained, so I don't think that's related. (I'm still dimmapping the Earth to 0, though. So I dunno if that has anything to do with it.)

As far as I can tell, this bug affects which star a planet is orbiting around. I'd say the Earth being Dimmapped to 0 would have something to do with this, but I haven't really had this issue while playing in 1.10.2.

**Comment by zmaster587** [comment]
I don't mean to sound testy, but I have very limited time, would it be possible to post the XML file where things are not working as expected so I can debug the issue?

**Comment by C1ffisme** [comment]
Just for the record, here's my XML file that I used:
```
<galaxy>
    <star name="Sol" temp="100" x="0" y="0" numPlanets="0" numGasGiants="0">
		<planet name="Mercury" customIcon="moon">
            <orbitalDistance>50</orbitalDistance>
            <gravitationalMultiplier>38</gravitationalMultiplier>
            <atmosphereDensity>0</atmosphereDensity>
            <biomeIds>110</biomeIds>
        </planet>
        <planet name="Venus">
            <orbitalDistance>72</orbitalDistance>
            <gravitationalMultiplier>90</gravitationalMultiplier>
            <atmosphereDensity>200</atmosphereDensity>
            <biomeIds>112</biomeIds>
            <fogColor>0xC4A000</fogColor>
            <skyColor>0xD6B72D</skyColor>
        </planet>
        <planet name="Earth" DIMID = "0" dimMapping = "">
            <orbitalDistance>100</orbitalDistance>
            <planet name="Luna">
                <orbitalDistance>15</orbitalDistance>
                <gravitationalMultiplier>12</gravitationalMultiplier>
                <atmosphereDensity>0</atmosphereDensity>
                <biomeIds>110</biomeIds>
            </planet>
        </planet>
        <planet name="Mars" customIcon="marslike">
            <orbitalDistance>150</orbitalDistance>
            <gravitationalMultiplier>37</gravitationalMultiplier>
            <atmosphereDensity>1</atmosphereDensity>
            <biomeIds>112</biomeIds>
            <rotationalPeriod>24500</rotationalPeriod>
            <skyColor>0xE46C3A</skyColor>
        </planet>
        <planet name="Jupiter" customIcon="gasgiantred">
            <orbitalDistance>175</orbitalDistance> 
            <GasGiant>true</GasGiant>
            <gas>hydrogen</gas>
            <planet name="Europa">
                <orbitalDistance>15</orbitalDistance>
                <gravitationalMultiplier>13</gravitationalMultiplier>
                <atmosphereDensity>0</atmosphereDensity>
                <biomeIds>115,10</biomeIds>
            </planet>
        </planet>
        <planet name="Saturn" customIcon="gasgiantred">
            <orbitalDistance>200</orbitalDistance>
            <hasRings>true</hasRings>
            <GasGiant>true</GasGiant>
            <gas>hydrogen</gas>
            <planet name="Titan">
                <orbitalDistance>20</orbitalDistance>
                <gravitationalMultiplier>14</gravitationalMultiplier>
                <atmosphereDensity>145</atmosphereDensity>
                <biomeIds>112</biomeIds>
                <fogColor>0xC4A000</fogColor>
                <skyColor>0xD6B72D</skyColor>
            </planet>
            <planet name="Enceladus">
                <orbitalDistance>30</orbitalDistance>
                <gravitationalMultiplier>13</gravitationalMultiplier>
                <atmosphereDensity>12</atmosphereDensity>
                <skyColor>0xAAAAAA</skyColor>
                <biomeIds>115</biomeIds>
            </planet>
        </planet>
    </star>
    <star name="Proxima" temp="10" x="-70" y="-40" numPlanets="0" numGasGiants="0">
        <planet name="Proxima b" DIMID="4">
            <orbitalDistance>92</orbitalDistance>
            <gravitationalMultiplier>96</gravitationalMultiplier>
            <atmosphereDensity>96</atmosphereDensity>
            <biomeIds>14,15,0</biomeIds>
            <skyColor>0xF2BA5B</skyColor>
        </planet>
    </star>
    <star name="Ross 128" temp="15" x="-210" y="56" numPlanets="0" numGasGiants="0">
        <planet name="Ross 128b">
            <orbitalDistance>89</orbitalDistance> 
            <gravitationalMultiplier>96</gravitationalMultiplier>
            <atmosphereDensity>119</atmosphereDensity>
            <biomeIds>111,118,0</biomeIds>
            <fogColor>0xE98989</fogColor>
            <skyColor>0xE99989</skyColor>
        </planet>
    </star>
    <star name="Groombridge 34 A" temp="13" x="218" y="0" numPlanets="0" numGasGiants="0">
        <planet name="Groombridge 34 Ab">
            <orbitalDistance>89</orbitalDistance>
            <GasGiant>true</GasGiant>
            <gas>nitrogen</gas>
            <planet name="Groombridge 34 Ab - 1">
                <orbitalDistance>50</orbitalDistance>
                <gravitationalMultiplier>46</gravitationalMultiplier>
                <atmosphereDensity>163</atmosphereDensity>
                <biomeIds>2,130</biomeIds>
                <fogColor>0xFCD03E</fogColor>
                <skyColor>0xFCD03E</skyColor>
            </planet>
        </planet>
        <star name="Groombridge 34 B" temp="11" numPlanets="0" numGasGiants="0" seperation="100">
        </star>
    </star>
    <star name="Tau Ceti" temp="76" x="232" y="62" numPlanets="0" numGasGiants="0">
        <planet name="Tau Ceti g">
            <orbitalDistance>13</orbitalDistance>
            <gravitationalMultiplier>103</gravitationalMultiplier>
            <atmosphereDensity>193</atmosphereDensity>
            <biomeIds>112</biomeIds>
            <fogColor>0xF7EEA9</fogColor>
            <skyColor>0xF7EEA9</skyColor>
        </planet>
        <planet name="Tau Ceti h">
            <orbitalDistance>24</orbitalDistance>
            <gravitationalMultiplier>98</gravitationalMultiplier>
            <atmosphereDensity>166</atmosphereDensity>
            <biomeIds>112</biomeIds>
            <fogColor>0xFFC7F9</fogColor>
            <skyColor>0xFFC7F9</skyColor>
        </planet>
        <planet name="Tau Ceti e">
            <orbitalDistance>53</orbitalDistance>
            <gravitationalMultiplier>87</gravitationalMultiplier>
            <atmosphereDensity>123</atmosphereDensity>
            <biomeIds>37,165,36,112</biomeIds>
            <fogColor>0xF7EEA9</fogColor>
            <skyColor>0xF7EEA9</skyColor>
        </planet>
        <planet name="Tau Ceti f">
            <orbitalDistance>133</orbitalDistance>
            <GasGiant>true</GasGiant>
            <gas>nitrogen</gas>
            <gas>oxygen</gas>
        </planet>
    </star>
</galaxy>
```

@epicdude312 If you can send us your own XML file, that would be helpful.

**Comment by zmaster587** [comment]
Alright, thanks, looks like #1215 may also be related.

**Comment by zmaster587** [comment]
Confirmed the issue when editing XML for an existing world.  Fix for next update
