### ISSUE TITLE
Rolling machine crash report

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#120]
When I put water with pipes or cubes it does not take it, and when I switch it on with some ingots inside it crashes. I cannot make it work.

Everything works fine with new worlds, it only happens with my oldest games. I tried removing all the mods, leaving Advanced Rocketry, Buildcraft and Galacticraft (if I remove Galacticraft the games does not load saying something about a Dimension conflict) 

What could I do?

http://pastebin.com/ZpUGVXdB

**Comment by zmaster587** [comment]
Because I store a value on the server containing whether or not the machine is built and because of the structure change (addition of the water input hatch), the client thinks it's complete and not complete at the same time.  If you break and rebuild the machine it should fix it.  I'll look into adding something that prevents this from occuring in the future.

**Comment by Tarkov** [comment]
I tried to break it and rebuild it, I even built it in a different place, and it did not work. :-(

**Comment by zmaster587** [comment]
What version of the mod are you running?  If you're running 0.5.2 do you have the water input hatch placed?  If both those are true can you take a screenshot of the structure without the main machine block placed so I can see how it's build?

**Comment by zmaster587** [comment]
I was able to replicate the issue, I should have it fixed in a few hours

**Comment by dmodoomsirius** [comment]
\o/ bug reports z loves them so much!

**Comment by Tarkov** [comment]
It is solved for me now! I was taking a picture and noticed I was using a water OUTPUT hatch instead of a input one. However the machine can builds anyway so I did not notice before!
