### ISSUE TITLE
[1.12.2] Holo-projector not showing second layer of machines

### ISSUE THREAD

**Issue by BigJazzz** [zmaster587/AdvancedRocketry#1217]
The holo-projector seems to be only showing one layer of the machine when I use it. Two examples are listed below:

[Precision Assembling Machine](https://ss.ssby.me/1521813321.png)
[Lathe](https://ss.ssby.me/1521812471.png)

This appears to be somewhat similar to #652, but I'm not even getting stand-in blocks.

If there's something I can try, or if maybe I've done something wrong, I'm more than happy to try any suggestions.

EDIT: I didn't list the AR version, nor any other pertinent stats. Apologies.

I'm currently running:
AR: 1.2.6.-54
FTB Revelation 1.5
macOS 10.13.4 beta 6

**Comment by BigJazzz** [comment]
Also, based on this video, I tried right-clicking after each layer was built and I only got the bottom layer. https://www.youtube.com/watch?v=iWs07QEUwf0&index=2&list=PLAuCSZ7eBw3pUyJvfb0FGwXMa63PSz-1v

**Comment by zmaster587** [comment]
Did you hold shift while scrolling with the holoprojector selected?

**Comment by BigJazzz** [comment]
Hmmm. I don't think I did. I'll give that a crack next time I'm online.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by mind-overflow** [comment]
Hello - sorry, I know this issue is almost 3 years old, but I'm having exactly this problem as of today. MC 1.12.2, AR 2.0.0-257-universal, Forge 14.23.5.2860.
I'll be more than happy to help you debug this issue - I'm a developer and I'm familiar with Forge, so I should be able to report anything you need.  
  
Pinging you (sorry) as I don't remember if you get notifications for closed issues: @dmodoomsirius @zmaster587

**Comment by voidsong-dragonfly** [comment]
You need to shift+scroll for the machines to show their next layers, as was said above.
