### ISSUE TITLE
Mekanism compatibility issue

### ISSUE THREAD

**Issue by TDplai** [zmaster587/AdvancedRocketry#1239]
## Version of Advanced Rocketry
1.4.0-5
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
5.2.3
## Version of Minecraft
1.10.2

## Description of the problem
Machines do not accept Mekanism gases or their liquid forms.

**Comment by TDplai** [comment]
No, I do not think Mekanism gases are registered as liquids, as Pressurised
Pipes are required to transport them. However, there is a device that
converts them into liquid forms - "Liquid [gas]". I am not sure what needs
to be done about this.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by jameshforster** [comment]
Hi, figured I'd comment here rather than reopen a new request. With the latest unstable builds for 1.12.2 (1.6.0-151 and Lib 0.4.1-59) this issue still occurs. Mekanism gases are still treated separately from liquids and will not be compatible with Adv Rocketry but also cannot be used once converted to "Liquid" form as described above but then they have a different naming convention to Adv Rocketry. Minetweaker can fix some of the issues but cannot make things like the Gas Charge Pad work with any of Mekanism's versions of the gases/liquids.
