### ISSUE TITLE
"No Oxygen" when standing in partial blocks.

### ISSUE THREAD

**Issue by AlbinoBlackHawk** [zmaster587/AdvancedRocketry#1240]
## Version of Advanced Rocketry
1.10.2-1.2.5a
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.10.2-0.2.6
## Version of Minecraft
1.10.2

## Description of the problem
I have a space station, that is completely pressurized. However, whenever I step on/in partial blocks like conduits from EnderIO or open doors from MalisisDoors, it tells me I have "No Oxygen" when clearly I do. This is really annoying since I'm wearing draconic armour which makes an obnoxiously loud noise whenever I take damage.

Please let me know if you need anymore information.

**Comment by chrisjahn123** [comment]
I am also having this problem. I've been using the Malisis Hi-Tech Doors for my station, only to discover that standing in the middle of them registers as having no Oxygen. 

I found an old support thread of the exact issue. Judging by it, it seems this issue is well known and difficult to fix. 
https://github.com/zmaster587/AdvancedRocketry/issues/625

It would be nice to get an update from zmaster587 on if there's any fixes in the works for this. It's really quite a bothersome issue, but I do understand the complexity behind implementing a fix.

**Comment by ErdbeerbaerLP** [comment]
I tried to use an door of theese and the oxygen always leaked through it (even if closed)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by JoshuaWright42** [comment]
To my knowledge this issue was never resolved.
