### ISSUE TITLE
[Solved] Struggling to figure out a way to pressurize the room with my space elevator.

### ISSUE THREAD

**Issue by JoshuaWright42** [zmaster587/AdvancedRocketry#1242]
## Version of Advanced Rocketry
1.10.2-1.2.5a
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.10.2-0.2.6
## Version of Minecraft
1.10.2

## Description of the problem
So I've build quite a large and impressive space station that's completely pressurized, the main reason why I want the whole station pressurized is because I hate having to wear the space suit and much prefer wearing my armor (Would be nice if you could wear the space suit over your armor, like in galacticraft). I also want my friends who aren't following along with this mod to be able to visit my space station without having to make their own space suit. However, I'm struggling to find a good way, or any way at all, to keep the room with the space elevator pressurized. Here is what I have tried:

1. Sealing the room by building blocks from the roof to the elevator using the elevator as part of the seal. (Fault: No oxygen)
2. Placing blocks from floor to ceiling on each of the four sides and placing an airlock door to cover the entrance (for some inexplicable reason that didn't work), although this method was crude and looked like shit so I'm not fussed that it didn't work. (Fault: No Oxygen)
3. Using Ethereal glass as the ceiling, figuring that since the elevator is an entity it might be able to pass through. (Fault: Elevator couldn't pass through)
4. Keeping on the entity idea, I then tried an rftools shield allowing "all" entities to pass through, this nearly worked, but what ended up happening was the elevator just rubber banded endlessly. (Fault: Elevator couldn't pass through)
5. My final idea, but I wasn't sure if or how to implement it since the elevator is not a block. Use block detectors to detect the elevator as it passes through and disable the shield momentarily (would work with with any kind of 3x3 horizontal door contraption if the elevator could be detected). (Fault: Don't know how to detect the elevator)

I'm posting this here to see if you could possible create a way to seal a room with the space elevator, whether it be by modifying the elevator, or introducing a new mechanic/thing entirely to handle this.

I'm also posting here to see if anyone can think of a way, using other mods (since I'm playing with a mod pack) to solve this problem, ideally as elegantly as possible.

Here's some pictures of my setup:
![image](https://user-images.githubusercontent.com/13131343/38515877-e5a9702a-3c78-11e8-9f1e-d5275c20ed4c.png)
![image](https://user-images.githubusercontent.com/13131343/38515890-f2a0c864-3c78-11e8-84ae-e638ad0ea77f.png)
![image](https://user-images.githubusercontent.com/13131343/38515900-fdb5dc3a-3c78-11e8-8be2-b514e200754f.png)
![image](https://user-images.githubusercontent.com/13131343/38515910-070c6ef2-3c79-11e8-9ac1-e2ad02aba7ec.png)
![image](https://user-images.githubusercontent.com/13131343/38516002-47e635d4-3c79-11e8-891d-bb63d8a407e3.png)

**Comment by AlbinoBlackHawk** [comment]
Although I still think there should be changes to the mod in order to make this less of a pain in the ass, I did find a way to solve the problem. Entity and block detectors couldn't detect the capsule, but the entity detectors had no issue detecting players. So I hooked my RFTools shield to a Draconic Evolution entity detector and set it to detect only players within a 3 block range (2 block range was to small), I also set the shield to be disabled when receiving a redstone signal. The shield now works like a charm allowing the capsules to pass through as they hit the shield.

However, since I'm on the 1.10 version of the mod, all this testing caused the known bug with capsules getting stuck at the destination, anyone know a way of clearing the capsules with a console command or something? Because I don't think updating is an option since this is a server.

**Comment by zmaster587** [comment]
The duplication elevators thing is fixed in 1.3.x builds and later I think.  There was never expected to be an issue with entities pling up, so getting a command from AR to clear them would require and update anyway.  I think there are some utility mods that let you kill all entities by type though.

If the entity detector is set to a larger radius does it detect it?  I'm looking here and seeing no limitation on entity type https://github.com/brandon3055/Draconic-Evolution/blob/507aad9803aa2567bcb46133ab1d53cc2e2d6a65/src/main/java/com/brandon3055/draconicevolution/blocks/tileentity/TileEntityDetector.java#L120

As to why its colliding, it looks to have to do with the built in movement system.  The minecart suffers from the same issue.  from what it looks like, if something actually can collide with the player (nesessary for the minecart and space elevator) then it cannot go through the blocks.

Only method I can think of would be some entity detector and forcefield (or some other togglable block).  Other than that without rewriting MC collision (or making it a pain to get out of the capsule).  I'm not sure there's really much ease of use I can do.  I suppose some automatic door thingy isn't out of the question though.  Would just need to find time to add such a thing.

**Comment by AlbinoBlackHawk** [comment]
The duplicated elevators isn't a big deal since the location of the space elevator in the overworld was just for testing anyway, so I just moved it.

As to your suggestion, I didn't actually test that, since the entity detectors from other mods didn't pick it up I didn't bother trying it with the draconic evolution version. I imagine it would need to be the advanced entity detector though, cause that's the only one that let's you enter specific entity types. I just tested that, the advanced entity detector from draconic evolution does detect the elevator capsule.

I understand how fixing the issue by removing the collision would be more effort than it's worth.

I have solved my problem now by using the entity detector from draconic evolution. However, having something incorporated into the mod itself would be nice. To save others having to go through the pain I just went through. So this issue is more of a feature suggestion.

**Comment by AlbinoBlackHawk** [comment]
I've left this open in case you do want to add a new feature to the mod to deal with this, otherwise, feel free to close this.

**Comment by DVorriose** [comment]
Albino:  I swear I saw a youtube video of someone who solved it by placing blocks around (against?) the top/outside of the elevator, while the rest of the elevator was indoors.  Will look around, but worth a try.

Also, nice looking space station, love the last pic.


ZMaster, could you make a (near?) invisible block with no collision that acted as an oxygen solid/sealed block?  Something akin to Star Wars (and other sci-fi) hangar bays?  Maybe a take on the shield generator?


Albino, do you control the configs?  That is, is it solo play or your own server?  AR has a config option for AR oxygen solid blocks.  If you have a mod that adds a non-collision block, you might be able to throw that into AR's config option.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by dhkatz** [comment]
> Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

I'd say this is somewhat still an issue. Can't seem to find any way to pressurize a room with a space elevator.

**Comment by JoshuaWright42** [comment]
I agree with @dhkatz . Although I managed to come up with a solution using other mods in the modpack, the problem within Advanced Rocketry was never fixed.

**Comment by Nomad7** [comment]
@JoshuaWright42 I'm trying to solve this same problem and stumbled on this thread - the RFTools shield + Draconic entity detector is a viable workaround for me but it doesn't seem to work...
RFTools shield template blocks create an airtight seal, but as soon as I click the Shield Projector to switch from template to actual shield blocks I lose the seal. Any suggestions?

**Comment by Nomad7** [comment]
To answer my own question, someone in RFTools discord suggested adding the shield blocks to the sealableblockwhitelist list in /config/advRocketry/advancedRocketry.cfg.

However, I haven't even tried that since shortly after my previous comment I realized that AdvancedRocketry has its own solution in the form of [force fields](http://arwiki.dmodoomsirius.me/AdvancedRocketry/blocks/ForceField.php) which specifically address this problem.
Although I do still need to figure out a way to keep my space elevator from killing me on impact with the force field... :)

**Comment by DatMinecrafterThere** [comment]
you can try to make a sealed chamber of glass aroundnd the elevator and make an airlock with airlock doors
