### ISSUE TITLE
Invisible Rockets with Little Tiles.

### ISSUE THREAD

**Issue by TacoRedneck** [zmaster587/AdvancedRocketry#1275]
## Version of Advanced Rocketry
[1.4.0-77]
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
[0.2.8-29]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
NA

## Description of the problem
In this version, the latest version, and every other version I've tried for 1.12.2, blocks made with Little Tiles or Chisels & Bits render as invisible when built into a rocket. 

I don't know if it's a bug or just unsupported, but I would really love for it to be possible for a build I plan on doing.

**Comment by BasieBrinkie** [comment]
I can confirm this.
It also happens in 1.10.2 i have tested 1.0.1 and up because i really would love to see this.
Still love the mod. Awesome work guys. It is one of my favorites!

**Comment by ZyorTaelon** [comment]
I tried to turn a Chisels & Bits build into a rocket and experienced the same issue.
![2018-07-27_10 47 36](https://user-images.githubusercontent.com/1486566/43311812-c1924370-918b-11e8-85bc-1561a9da97ba.png)
![2018-07-27_10 47 57](https://user-images.githubusercontent.com/1486566/43311831-cb2f4a7c-918b-11e8-87b7-a0d9533406b3.png)
turned out as:
![2018-07-27_10 48 03](https://user-images.githubusercontent.com/1486566/43311839-d313d74e-918b-11e8-928f-3458b142f325.png)
Using:
AdvancedRocketry-1.12.2-1.4.0-93-universal
chiselsandbits-14.20
LibVulpes-1.12.2-0.2.8-36-universal

I did notice this line appearing in my logs:
[10:55:30] [Netty Epoll Client IO #0/INFO] [STDOUT]: [zmaster587.libVulpes.network.PacketEntity:readClient:153]: oh no...

**Comment by zmaster587** [comment]
It's been unsupported since 1.7.10, support for chisel and bits should be coming soon.
