### ISSUE TITLE
Metamorph Chicken On Space Station issue

### ISSUE THREAD

**Issue by FoxBotGames** [zmaster587/AdvancedRocketry#1291]
## Version of Advanced Rocketry
1.4.0-80
## Have you verified this is an issue in the latest unstable build
What?
## Version of LibVulpes
0.2.8-31
##Version of Metamorph 
1.1.5-1.12.2
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
Not Applicable

## Description of the problem
By either morphing into a chicken on a space station or by being a chicken when entering a space station (any way possible) the chicken's slow fall doesn't go down, it goes UP (on space station), have not tested on low gravity planets due to limited mapping caused by incomplete modifications to creating new planet things (Im not on that so Im dont know much)
(Many other mods are included other than metamorph, find us over on github.com/grimco under CoopLife2)

**Comment by FoxBotGames** [comment]
This has been expanded upon, Vanilla chicken and Chickens (mod) chickens both have the same effect.

**Comment by Rightfuldeathray** [comment]
all entities with a slow fall effect have this, along with flying entities, falling sand entities aren't effected by low gravity, if a gravity controller is effecting the area falling sand entties fall up, and dont turn back into blocks (even if they hit a ceiling) because they haven't hit the floor yet. all slow fall/ flight entities behave awkwardly in a gravity controllers range.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
