### ISSUE TITLE
Vacuum damage config?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#132]
currently the vacuum damage can be easily bypassed using other mods
like using am2, you can regenerate faster than the damage dealt without wearing spacesuit
and with witchery. you can't even die as a vampire :P
So I'd just suggest adding a damage scale option for vacuum, or does anyone have better ideas?

**Comment by zmaster587** [comment]
I can add a config, however I think the unable to die as a vampire may be a bug with wtichery as vacuum damage should ignore armor similarly to void damage as I have bypass armor and damageIsAbsolute flags set.

**Comment by wormzjl** [comment]
Vampires can only die when dealt with lethal damage with certain conditions (like using silver weapons, or burned by sun)
Even kill command don't work :P

**Comment by zmaster587** [comment]
That defiantly sounds like a witchery problem to me, I'll look anyway though.

**Comment by wormzjl** [comment]
Never mind, I think a damage slider is the best solution

**Comment by DarkGuardsman** [comment]
@zmaster587 https://github.com/zmaster587/AdvancedRocketry/issues/93 would be a good solution for other mods. Add heavy debuffs the player over time, as well I think a vampire should be immune to 50% of space effects. After all it able to regenerate quickly and doesn't really have a living body. However, it should get 300%-1000% sun exposure due to no longer being protected by the atmosphere.
