### ISSUE TITLE
Nether doesn't work as a planet

### ISSUE THREAD

**Issue by CaptainStalfoss** [zmaster587/AdvancedRocketry#1320]
## Version of Advanced Rocketry
1.12.2-1.4.0-81
## Version of LibVulpes
1.12.2 0.2.8-30
## Version of Minecraft
1.12.2

## Description of the problem
I made the Nether into a planet, the planet cannot be selected on the Planet selector.
when ever i chose it, it resets to SOL (over worlds star).
on the server we tried going to it with the space station warp, but we ended up stuck in space and the warp controller was unclickable (even newly placed ones.) causing a Soft lock of the station.

[planetDef.txt](https://github.com/zmaster587/AdvancedRocketry/files/2059897/planetDef.txt)

Also another issue, some trees doesn't seam to spawn on a planet on the server.
(biomesoplenty origin island trees did not spawn, but they DO on singleplayer)

**Comment by CaptainStalfoss** [comment]
Updated to latest version, and i can confirm the problem is still there.

**Comment by zmaster587** [comment]
Because the nether has a bedrock ceiling, it's intentional that it cannot be used as a planet since players would not be able to get into it.  Additionally the nether is often thought of as a deep underground section of the overworld.  The nether (id -1) is also used as a placeholder for invalid dimension due to the above.  

Additionally, there was an issue with planet data being slightly different on the server until the most recent build.  Can you test with the BOP trees with the most recent build with identical dat and defs?

**Comment by CaptainStalfoss** [comment]
Shouldn't that be up to each mod pack maker? for instance i can remove the bedrock roof easily.
also no nether portals since im customizing everything to fit space travel.

Updated to latest, Tree's spawn now, awesome work =3
and the planet icons also work correctly.

**Comment by zmaster587** [comment]
Fair point, I wasn't aware anyone had made anything to remove the bedrock ceiling.  But I suppose I can look into it.  Because -1 is treated as an invalid id (and I used magic numbers instead of a constant) it may take me a bit of time to get around to fixing and there may be a few odd issues that crop up at first.  I'll likely change the invalid id to MIN_INT instead.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/2100515/AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip)

Can you test this build and let me know if it works as expected?

**Comment by CaptainStalfoss** [comment]
I tested it, it crashes when you chose "UP" in the planet selector

[crash.txt](https://github.com/zmaster587/AdvancedRocketry/files/2102519/crash.txt)

**Comment by zmaster587** [comment]
The Up button is also id -1, I'll change that

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/2104641/AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip)

Second and hopefully last attempt.

**Comment by CaptainStalfoss** [comment]
it works now, thanks!
haven't tested it on server yet, but i'll get back to you if i find any issues.

**Comment by zmaster587** [comment]
No problem!
