### ISSUE TITLE
Holo-Projector Bug

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1332]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-84-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-32-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
The Holo-Projector places the red X that appears when a multiblock has a wrong blocks on the wrong block.
I was building an Electric Arc Furnace, and had placed the Arc Furnace block on the wrong side - The red X appeared on the wrong block, see image.

![billede](https://user-images.githubusercontent.com/21295394/41205091-7c02cfae-6ced-11e8-9939-ebf3e73f17ce.png)

The same thing happened when I built the Rolling Machine wrong. I had placed the Rolling Machine itself rotated the wrong way, and the X appeared on an Input Hatch a few blocks from it.

**Comment by zmaster587** [comment]
The X appears to be in the correct spot, you have the energy inputs in the wrong spot.  You should have two on the same face as the controller (as displayed by the holo projector in my testing).

I've also tested the rolling machine facing north, south, east, and west and the X still appears to be in the correct locations no matter which blocks I swap out or how it faces.
It should be built like this (hologram on the right for comparison)

![image](https://user-images.githubusercontent.com/3536685/41386777-40bf549c-6f51-11e8-8b6e-b4785b5ed3ff.png)

Since I've been having no luck with the rolling machine, can you upload a screencap of that too?

**Comment by NillerMedDild** [comment]
I'm well aware of how its built, I moved the Controller to the wrong side to show the error. (Thus making the energy inputs seem wrong). I suppose the X is right then, I just assumed it would show the Controller as the mistake, my bad.

**Comment by NillerMedDild** [comment]
I'm guessing the Rolling Machine error is on my side aswell.
