### ISSUE TITLE
Performance issue with RocketBuilder

### ISSUE THREAD

**Issue by Sir-Will** [zmaster587/AdvancedRocketry#1333]
AdvancedRocketry-1.12.2-1.4.0-84
LibVulpes-1.12.2-0.2.8-32

The event registration seems to cause huge performance issues with the RocketBuilder.

![](https://i.imgur.com/A1ykuNY.jpg)

**Comment by dmodoomsirius** [comment]
Does this issue still occur without Sponge installed?

**Comment by Sir-Will** [comment]
There is no indication that it wouldn't happen without sponge.

**Comment by Sir-Will** [comment]
@dmodoomsirius I was able to reproduce this now and this happens without sponge too, just place multiple rocket builder in a chunk and load/unload it.

![](https://i.imgur.com/Moek9I3.jpg)

**Comment by zmaster587** [comment]
How many calls were made to it?

**Comment by Sir-Will** [comment]
? The reproduction was done on chunk load. Why not register one event for all blocks instead one for each?

**Comment by zmaster587** [comment]
Registering the event once for all blocks would just be kicking the can down.  I'd still need to register each  block with that handler so the performance would actually be slightly worse because you have the same amount of events being added to the list, but with the addition of the overhead of the extra handler.  Because location is required to determine if there's a rocket landing at a pad, I cannot just register it with a single block.

As for the first screenshot, that also appears to occur on chunkload for one.  Secondly, that's indicating that java reflection is taking a long time, which means there's either something wrong with the setup, or something else is causing the tile to be duplicated many times.  Event registration is quite literally just inserting into a list, the same operation occurs when any mob is spawned.  In my own tests, unless I have a ridiculous amount of of rocket builders, it's not noticable.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
