### ISSUE TITLE
Client sometimes crashes when opening the Guidance Computer. Seemingly BetweenLands related.

### ISSUE THREAD

**Issue by DestinyPlayer** [zmaster587/AdvancedRocketry#1358]
## Version of Advanced Rocketry
1.12.2-1.4.0-90
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-33
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/CN7xWigm

## Description of the problem
Every now and then, my game crashes when I look at the Guidance Computer GUI. Normally it happens at the second time I open the interface. Judging by he log, it's some kinda incompatilibility between AdvancedRocketry and BetweenLands.
## Additionally:
http://prntscr.com/k80wrg
My full modpack

**Comment by DestinyPlayer** [comment]
Maybe it's something to do with unsupported dimensions in general?

**Comment by myles438a** [comment]
I'm also receiving this error.
Attached my crash log as well.

https://pastebin.com/uDESyqX7

**Comment by zmaster587** [comment]
That appears to be an issue with betweenlands expecting the rocket world to have a betweenlands capability when it does not, then failing to handle that case.

**Comment by myles438a** [comment]
This doesn't make sense though, because I've completely removed thebetweenlands from the server I'm running. Including the client.

**Comment by zmaster587** [comment]
java.lang.RuntimeException: World  (zmaster587.advancedRocketry.world.util.ProviderDummy) does not have BetweenlandsWorldStorage capability
    at thebetweenlands.common.world.storage.BetweenlandsWorldStorage

This is definitely a betweenlands issue.

Perhaps more than one thing is going on, can you submit the crash report you are getting when betweenlands is not installed?

**Comment by myles438a** [comment]
> This is definitely a betweenlands issue.
Perhaps more than one thing is going on, can you submit the crash report you are getting when betweenlands is not installed?


That was a crash from after I removed the mod from both server and client, I also went and deleted the config folder for thebetweenland and some entries in Applied Energistics 2 and we haven't had a crash yet. 

The people over in Thebetweenlands github believe this to be an issue with AdvRocketry. They said this - 

> This appears to an error within Advanced Rocketry. Their ProviderDummy is constructed such that it remains in an invalid state from being a capability provider which has not gone through capability initialization.

**Comment by pau101** [comment]
@zmaster587 It is invalid to offer a capability provider instance to outside code which has not had its capabilities gathered. Certain capabilities can be required to be present for all instances of a capability provider in order to maintain mod functionality. Particular code that expects capabilities yet chooses to ignore erroneous absence leads to observable bugs in game.

**Comment by zmaster587** [comment]
@pau101 Niether worldProviderDummy, nor WorldProvider (the vanilla class which it extends), nor WorldDummy have any capability code whatsoever.  In fact, all worldProviderDummy does is return DimensionType as Nether, everything else is left up to vanilla code.

https://github.com/zmaster587/AdvancedRocketry/bob/1.12/src/main/java/zmaster587/advancedRocketry/world/util/ProviderDummy.java

However, because the rocket world is never really actually loaded, since it's more a workaround for storage rendering, the world load event is never called (it doesn't have to be, it's not intended to be a dynamic world and a lot of special handling has to be done) the capability from thebetweenlands will never be registered.  Allowing registration of cababilities and doing a full world load could cause some very strange errors with the rockets as well as increase overhead.

**Comment by pau101** [comment]
A world without our capability would mean the something is broken and errors would occur in-game. The correct behavior is to crash for our missing capability. It is required for capability provider instances to have capabilities initialized, as it is against the capability contract otherwise. The [WorldDummy](https://github.com/zmaster587/AdvancedRocketry/blob/b9733aaa946a6c4315a74b8e4d15a087dbff2324/src/main/java/zmaster587/advancedRocketry/world/util/WorldDummy.java) class can be modified as below to correct the behavior.

Add this field:
```java
private final CapabilityDispatcher capabilities;
```
Add initialization in constructor:
```java
this.capabilities = ForgeEventFactory.gatherCapabilities(this, null);
```
Add `ICapabilityProvider` implementation:
```java
@Override
public boolean hasCapability(net.minecraftforge.common.capabilities.Capability<?> capability, @Nullable EnumFacing facing) {
	return capabilities != null && capabilities.hasCapability(capability, facing);
}

@Override
@Nullable
public <T> T getCapability(net.minecraftforge.common.capabilities.Capability<T> capability, @Nullable EnumFacing facing) {
	return capabilities == null ? null : capabilities.getCapability(capability, facing);
}
```

**Comment by zmaster587** [comment]
Thanks for the input @pau101 I'll give that a shot
