### ISSUE TITLE
In case of disk full condition, AdvancedRocketry destroys it's files and prevents reloading of the world

### ISSUE THREAD

**Issue by bothie** [zmaster587/AdvancedRocketry#1388]
In case of disk full condition, AdvancedRocketry destroys it's files and prevents reloading of the world

Current world (after attempt to reload):
```
$ ls -l planetDefs.xml temp.dat
-rw-r--r-- 1 minecraft users       0  2. Sep 16:49 planetDefs.xml
-rw-r--r-- 1 minecraft users       0  2. Sep 16:49 temp.dat
```

Last backup:

```
$ ls -l planetDefs.xml temp.dat
-rw-r--r-- 1 root root   28082  2. Sep 14:02 planetDefs.xml
-rw-r--r-- 1 root root    3901  2. Sep 14:02 temp.dat
```

**Comment by zmaster587** [comment]
Gonna change it to save to a temp file, then copying to the actual save file.  That way in the case of out of disk you'll either have a full copy in the server folder and a partially overwritten main save or a partially written copy and an untouched main save.

While testing with a full disk would have beena  bit hard to do without breaking other stuff I have running, I settled for changing file permissions during testing (in theory either one should throw an IOException).

**Comment by bothie** [comment]
Thank you for addressing this issue.

I'd like to have this issue readdressed for two reasons:

1. In case of a MC crash / disk full, this solve the problem but in case of an OS crash during the copy operation, things can go wrong again (old file truncated, new file not synced to disk). Solution: Add a call to java.io.File.sync().
2. Instead of copying the file, first try to java.nio.file.Files.move(tmp, target, java.nio.file.StandardCopyOption.ATOMIC_MOVE, java.nio.file.StandardCopyOption.REPLACE_EXISTING) the file. Together with sync, this leaves the file in a consistent state in any case.

**Comment by zmaster587** [comment]
I think having two seperate files at any given time fixes this, no?  In the case of an OS crash, the conditions are the same as the disk becoming full halfway through a write.  You still have two seperate files.  One temp file in the world directory (so it's not deleted on reboot/OS failure) and a main file.

The reason i went with the copy instead of a move is actually because of the risk of an OS crash.  In the case of a move during a crash or power failure, you could end up losing the file (file table corruption).  In the case of copying the data, you still have at least one full copy somewhere.

**Comment by bothie** [comment]
You go by the assumption, that after closing the file, all it's contents are synced to disk. This assumption is wrong. By copying this file (whiches contents have not made it to stable storage yet) over the other file can again render both files corrupt. (At least, this now can only happen in case of an OS crash or power failure, not just if MC crashes, but the solution I pointed out is not that hard to implement). Also, with all modern file systems (including NTFS on windows) a rename is always an atomic operation obeying the POSIX requirement, that at any given time, the file to be renamed is either visible by the old name or by the new name (or both at the same time) but there are no times, where the file is not visible at all. So: Write the new file, sync it to disk, then rename it over the old file. Or: After writing and syncing the new file, delete the old file, then rename the new file to the old name. During load: If the file does not exist, check for a new version of the file and if it exists, rename it and then go on.

**Comment by zmaster587** [comment]
In java the implementation of the close() function flushes the stream, this is explicit in the java docs.  The flush method in turn ensures all contents are synced to disk.  Because close is called before the copy on the same thread, this also ensures that the file has been committed to disk before the copy operation starts.

**Comment by bothie** [comment]
Cool. One little problem left: ```sync()``` only ensured data to be written to storage that have been sent to the OS already. So: ```write```, ```flush```, ```sync```, ```close```. In your code, ```flush``` is still missing. It's as easy as adding ```bufoutStream.flush();``` right before ```getFD().sync();``` (and likewise for ```outStream```).

**Comment by zmaster587** [comment]
Thanks for the help!
