### ISSUE TITLE
Rolling Machine outputting plates

### ISSUE THREAD

**Issue by Rongmario** [zmaster587/AdvancedRocketry#139]
Coal plates are being outputted even when nothings being inputted, but the coal plates are from TechReborn, not sure why, no other mod's coal plates are outputted, just TechReborn's.

**Comment by zmaster587** [comment]
What version of Advanced Rocketry are you using?

**Comment by Rongmario** [comment]
0.5.4 of Advanced Rocketry + 0.7.17.1109 of TechReborn + 1.1.0.15 of RebornCore

**Comment by zmaster587** [comment]
alright, will check.

**Comment by zmaster587** [comment]
TechReborn is adding a mapping of ["ingotCoal", null] to the ore dictionary so that OreDictionary.doesOreNameExist("ingotCoal") returns true even though there's no real item mapped to it.  This is caused the recipe of null input to coalPlate to be added to the rolling machine causing it to make plates from nothing.  It turns out the same is happening to most of techReborn's items.  I'll add an extra check for 0.6.0 but i really shouldn't have to.

**Comment by Rongmario** [comment]
Thank you!
