### ISSUE TITLE
[Suggestion] Should certain planets with atmosphere should not be breathable?

### ISSUE THREAD

**Issue by MrEyeballs29** [zmaster587/AdvancedRocketry#1410]
## Version of Advanced Rocketry
advanced-rocketry 1.4.1-103
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
lib vulpes 0.2.8-39
## Version of Minecraft
1.12.2
## Description of the problem
I found some planets where I looked online where certain planets are not breathable. It should not only be oxygen only. Like you should add on CO2 atmosphere (not breathable), Helium atmosphere (also not breathable), hydrogen atmosphere, and many more gases that needed in the planet config (XML).

### Questions
Also why did you put some config files in XML rather than JSON which every else is using?

**Comment by zmaster587** [comment]
It's planned that there will be other atmosphere types, it's just not high priority at the moment.  I'd like to get some more of the planet gen flushed out first otherwise I fear every planet without a breathable atmosphere would look too similar.  just piles of rock.  So I'd at least like to get around to adding alien flora and fauna first.

Java has had libraries for XML parsing built in since at least java 6, JSON parsing didn't exist in built-in libraries until later versions.

**Comment by MrEyeballs29** [comment]
Thanks for that I am just curious about how each of the non-earth-like planets are not supposed to have oxygen rich though.

**Comment by MrEyeballs29** [comment]
That is my idea. If Mars and Venus could have CO2, Some exoplanets could have H2, SO2, H2O, and Many more types of Gases that are not breathable to the players. Looks boring and makes it so unrealistic with only O2.
