### ISSUE TITLE
Crashing when joining to a server

### ISSUE THREAD

**Issue by JoeSGT** [zmaster587/AdvancedRocketry#1445]
## Version of Advanced Rocketry
1.12.2-1.4.1-1
## Have you verified this is an issue in the latest unstable build
Y,N, N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.3.0-44
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
[crash-2018-11-24_22.44.48-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/2612840/crash-2018-11-24_22.44.48-client.txt)

## Description of the problem
I had update the mod today and this happens when i join the server i crash im not sure what going on here

**Comment by zmaster587** [comment]
The log you posted here is for version 1.4.1.-1, which is a very old build, the latest is 1.4.1-113.  Would you be able to try that build?  Secondly, I see you're using sponge.  Advanced rocketry does not support sponge all that well since they modify a lot of things.  I know there's some activity going on here that may be related though
https://github.com/zmaster587/AdvancedRocketry/issues/1439

**Comment by nullpointspace** [comment]
Это та же ошибка.  #1415 and #1433

**Comment by takarabako** [comment]
I saw the latest release on CurseForge is indeed version 1.4.1-1, uploaded on Novenber 16th.

**Comment by JoeSGT** [comment]
Yea on the curseforge i click download latest and that was it that it gave me very confuse

**Comment by zmaster587** [comment]
@JoeSGT @takarabako Sorry, the workaround for sponge was not meant to be uploaded to curse and messed with the versioning system.

**Comment by JoeSGT** [comment]
Looks like it happen to another player of mine i had compile it this commit and use the jar for testing it fix few other player but other are still having the issue https://github.com/zmaster587/AdvancedRocketry/commit/96d54b071c819bd0d01b2cf6654f69b0e91744b0

[crash-2018-11-25_20.33.57-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/2613802/crash-2018-11-25_20.33.57-client.txt)

**Comment by JoeSGT** [comment]
Also i hope this is more information on the error 
https://pastebin.com/raw/kjw42M4a

**Comment by JoeSGT** [comment]
okay it seem if any of my players are in their space stations or anything within space they crash only way to prevent them from crashing when joining is when i teleported them back to spawn point which is in the overworld

**Comment by takarabako** [comment]
> okay it seem if any of my players are in their space stations or anything within space they crash only way to prevent them from crashing when player joining then when i teleported them back to spawn point which is in the overworld

Since you are using sponge, see #1439. You need to compile sponge_login_fix branch for you server, and apply some additional code fix mentioned down in the comment to the client jar to make it fully working.

**Comment by JoeSGT** [comment]
@takarabako i manage to get someone to edit the mod using your code it work can confirm that thanks you also @zmaster587 why won't you use his code to fix these issues?

**Comment by tenten8401** [comment]
Here's my attempt at compiling Advanced Rocketry from the `1.12.2` branch along with the following patches applied for anyone else that needs it:
- https://gist.github.com/takarabako/b5c6c2a93e9f25063b90d3e82ac61b59
- https://github.com/zmaster587/AdvancedRocketry/commit/2159fac300281c49ae33e15afd731df2b49d0b36

Literally all I've tested is that it boots and that I can enter singleplayer, use at your own risk. If your PC explodes, dog dies or thermonuclear war breaks out because of it, I am not responsible. **MAKE A BACKUP.**
[AdvancedRocketry-1.12.2-1.4.1-UNSUPPORTED-universal.zip](https://github.com/zmaster587/AdvancedRocketry/files/2617684/AdvancedRocketry-1.12.2-1.4.1-UNSUPPORTED-universal.zip)

If I forgot to apply a patch please let me know.

**Comment by zmaster587** [comment]
@JoeSGT It's more a workaround for a bug in sponge that does not exist with standard forge as opposed to an issue in AR.  I've also not yet had the time to vet and make sure that it doesn't break stuff in installations where sponge does not exist.  Changing the order in which packets are sent during initial connection is not exactly a trivial change and is not something I can just throw at people without testing in a variety of environments.

**Comment by takarabako** [comment]
@JoeSGT Looks like sponge have fixed the issue and already compiled a new build on their website. Now we don't need these workarounds :)

**Comment by JoeSGT** [comment]
Going to try it
