### ISSUE TITLE
mod force changes config settings making it impossible to add new planets

### ISSUE THREAD

**Issue by Heyo13579** [zmaster587/AdvancedRocketry#1508]
## Version of Advanced Rocketry
127
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0-51
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
B:resetPlanetsFromXML=false this line when set true gets forcefully changed back to false making it impossible to add new planets from the base config file

**Comment by zmaster587** [comment]
This is intentional.  If it is not set back to false, it would be very easy for a user to mistakenly overwrite other saves that may have a different configuration.  The setting exists so that pack makers can forcibly update a solar system in a given pack ONLY upon an update.  That way the user can more easily customize worlds.  

It gets set to false only after the world is loaded at least once.  Although after that it should have loaded the planet xml from the config folder instead of the world folder.

If you're not making a pack or releasing a pack and just running a server.  I suggest changing the XML in the world folder instead of the one in the config folder.

**Comment by Heyo13579** [comment]
it is for a mod pack but the setting changes back to false upon starting the pack before you even see the menu screen but in order for the pack to work properly it needs to use the file that we have made for every world. if it only works for one world then it would break the pack. i need a way to keep that option set to false. maybe make a config setting for pack developers to be able to select wether or not they would like the mod to prioritize the main config or the world config. if the player would wish to make custom planets then they can go in and change it themselves but like i said to most pack developers the way it is currently set up is a migraine and a half

**Comment by zmaster587** [comment]
When the game loads, it's not possible to really tell which was modified.  If the user modifies one on their save.  All the game knows is that the file in the config and the file in the save differ.  Currently if a config in the save folder exists, it will use that.  I can make it so that it always loads from the config folder.  But then any user made changes to the individual world will be overwritten by what is in the config folder.

I can add an option that prevents `resetPlanetsFromXML` from getting automatically reset to false, that will, in essence, make the game always use the copy in the config folder.  However the user will be unable to make changes to individual worlds without turning the config setting to false.

**Comment by Heyo13579** [comment]
That would be great for pack developers. just like in my case where i need a forced planet to be included for questing. that way its up to the player to disable the intended game play of the pack rather than to enable the intended game-play of the pack if that makes more sense.
