### ISSUE TITLE
[Bug] Satelite bay crashes/freezes game after rocket assembly

### ISSUE THREAD

**Issue by TheonlyTazz** [zmaster587/AdvancedRocketry#1509]
## Version of Advanced Rocketry
V1.12.2-1.5.0-126.jar
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.12.2-0.4.0-49.jar
## Version of Minecraft
1.12 Forge-14.23.5.2795
## Crash report or log (if applicable)
No Crashreport bcause game freezes until crashes, but log from the Freeze
https://pastebin.com/raw/9sETesEh

## Description of the problem
When assembling a rocket with a satelite bay, after building it and wanted to put in the satelite, you get disconnected and your game freeze

Log also mentions MEK(anism) so posting this on their github aswell
https://github.com/aidancbrady/Mekanism/issues/5271

placing in the satelite BEFORE pressing build on the rocket builder is fine

**Comment by zmaster587** [comment]
Bit of background.  When accessing chests and items in the rocket, AR temporarily switches users to a dimensionless "temp world" so that the coordinates of the tiles accessed match up with the coordinates of the tiles on the rocket.  It appears that Mekanism is sending/recieving some data while the user has been moved to the temp world.  The Temp world is not a `ServerWorld` nor is `isRemote` true.  Because the world must be able to be loaded from NBT, sometimes without access to a world object, I've not found a viable way to properly set isRemote.  I've considered using proxies, but that seems to break down in single player.

Mekanism is expecting a `WorldServer` on packet recieve if `isRemote` is false and the player in `handlepacket` is not null.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.5.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/2826366/AdvancedRocketry-1.12.2-1.5.0-universal.jar.zip)
Would you be able to try this build and see if the issue continues?

**Comment by TheonlyTazz** [comment]
I have seen that the packdevs have pushed 1.5.0-127 to the dev-instance... Once the server gets updated I'll report back if the bug still occurs

**Comment by TheonlyTazz** [comment]
Still crashes after using 1.5.0-127

**Comment by Tntdruid** [comment]
Crash in 1.5.0-131 too

**Comment by dizzyd** [comment]
@TheonlyTazz could you provide a save file, minimal mod list and  list of instructions to trigger this bug? I'm happy to investigate why Mek requires a WorldServer instance on my fork (https://github.com/dizzyd/Mekanism) if I have enough data to reproduce reliably. :)
