### ISSUE TITLE
Get stucked after downloading terrain screen

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#151]
I always get stucked in Y=1000 after the downloading terrain screen. Does not matter what planet I go to. If I leave the rocket or disassemble it I can fall to the new planet. Sometimes it crashes with the "Exception ticking world entities" issue.

**Comment by zmaster587** [comment]
It's intentional that the rocket sticks after loading terrian, I have not got a chance to document changes in the new builds yet, pressing space bar should start the descent.  The Exception ticking worlds issue is also on my to-fix list.  Minecraft does not like moving two entities between dimensions in the same tick and sometimes has a fit, I should have that fixes relativly soon.  What I probably can do is add an overlay to instruct the user to hit space again...

**Comment by zmaster587** [comment]
Fixed in 236bdb0d463ee23883a8778765bb51d735bd36c9

**Comment by Tarkov** [comment]
Many thanks for the fix! I think the customer service is even better than the mod, and I am spending lot of hours lately!
