### ISSUE TITLE
Odd blocks that rockets logically shouldn't work with/should have different behaviour with

### ISSUE THREAD

**Issue by C1ffisme** [zmaster587/AdvancedRocketry#1529]
## Version of Advanced Rocketry
1.5.0-131
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
0.4.0-52
## Version of Minecraft
1.12.2

## Description of the problem

Rockets can be built with a plethora of blocks which they probably shouldn't be for the sake of logical sense.

**Unbreakable Blocks (Bedrock)**
(see also #774 )

![2019-03-03_20 01 19](https://user-images.githubusercontent.com/9893266/53716148-8fd95400-3e19-11e9-9d66-1fbf4fdb3493.png)

This specific bug seems like it'd be useful for griefing if you were smart enough.

**Fire**

![2019-03-03_22 39 38](https://user-images.githubusercontent.com/9893266/53716227-da5ad080-3e19-11e9-80ae-47671e7f7de2.png)

Doesn't make sense oxygen-wise of course, but it also doesn't exactly seem like a safe thing to put on a rocket.

Also in this screenshot: Redstone and Pistons seem to be incorporated into the build without problems?

**Piston Arms**

![2019-03-03_22 43 20](https://user-images.githubusercontent.com/9893266/53716550-ed21d500-3e1a-11e9-94f3-4cf2be219257.png)

You can actually destroy pistons using the rocket this way. The piston will pop off as an item which disappears after only half a second. Mining the arm drops nothing.

**Water**

![2019-03-03_22 55 29](https://user-images.githubusercontent.com/9893266/53716613-180c2900-3e1b-11e9-9774-013f8277b68d.png)

Seems like an unsafe thing to keep unchecked in a spacecraft...

**Horizontal Engines**

![2019-03-03_23 01 19](https://user-images.githubusercontent.com/9893266/53716692-57d31080-3e1b-11e9-9280-3c422da0c341.png)
![2019-03-03_23 02 25](https://user-images.githubusercontent.com/9893266/53716693-57d31080-3e1b-11e9-8ad0-75c3c0bd102f.png)

I'm kinda disappointed that this didn't work exactly the way I would have expected it to, but to be fair I had to rotate these using an Immersive Engineering hammer.

I'm sure there are more blocks I haven't tried, but these are some of the obvious ones.

**Comment by ViciousGamer** [comment]
Not related, but the horizontal engines gave me a chuckle for some reason😆

**Comment by Archilyte** [comment]
pls dont stale this guy has a point

**Comment by zmaster587** [comment]
This was the reason the `rocketBlockBlackList` config option was added, granted it's not populated by default, but it's for modpack makers or server owners to prevent certain blocks from be allowable on rockets.  I'd also argue the sideways engines are an exception to that rule, but that only can happen because the Immersive Engineering hammer doesn't care about what's valid and what's not really when it comes rotations.  It can mess with vanilla chests even.

While it's not feasible for me to go through every single mod, i could add weird vanilla blocks as blacklisted by default.

**Comment by Archilyte** [comment]
> i could add weird vanilla blocks as blacklisted by default.

Please do. Also add all fluids on the list too (if thats possible)

**Comment by C1ffisme** [comment]
> While it's not feasible for me to go through every single mod, I could add weird vanilla blocks as blacklisted by default.

That's okay with me, I wouldn't expect someone to accidentally build a Tinkers' Construct smeltery or something else possibly breakable on the launch pad.

**Comment by Archilyte** [comment]
Also make it have two lists in the config for disabling(this lists may stay empty so that pack devs can add blocks in):
1) This list will have fire, snow, sand piles(some weather mod in Forever stranded disturbed me a lot), taint vines, basically anything that can be automatically placed on the launch pad by the game where these blocks get removed when rocket is built.
2) blocks on this list will prevent the rocket from building (to prevent block loss)

This is just to make things convenient, obviously is is ur decision if this will get added or not

**Comment by zmaster587** [comment]
> Also make it have two lists in the config for disabling(this lists may stay empty so that pack devs can add blocks in):
> 
>     This list will have fire, snow, sand piles(some weather mod in Forever stranded disturbed me a lot), taint vines, basically anything that can be automatically placed on the launch pad by the game where these blocks get removed when rocket is built.
>     blocks on this list will prevent the rocket from building (to prevent block loss)
> 
> This is just to make things convenient, obviously is is ur decision if this will get added or not

The 2nd list already exists in the config as "rocketBlockBlackList".  Is there any reason a block that can automatically be replaced such as snow, fire, grass would want to not be allowed on the rocket but not automatically removed?  If not, any block that could be replaced that is in the blacklist could automatically be destroyed on rocket build.

**Comment by Archilyte** [comment]
Snow can be counted as part of the rocket, but not realized. For example, once I thought my rocket had too much mass, while it was just snow. I spent 5 hours brainstorming a better rocket. I realized what was going on later. 

then again, I may just be really dumb.

**Comment by zmaster587** [comment]
The above commit adds "minecraft:portal","minecraft:bedrock", "minecraft:snow_layer", "minecraft:water", "minecraft:flowing_water", "minecraft:lava", "minecraft:flowing_lava" as blocks that cannot be placed on the rocket by default.  Blocks that can be replaced, like water, lava, or grass will not prevent the rocket from building, but will vanish when the rocket is built if they are in the blacklist.

**Comment by Archilyte** [comment]
wait, so any block in that list will vanish?

what if a modpack creator decides to put an expensive block on this list to prevent breaking progression (warp drive)? would that just vanish?

**Comment by C1ffisme** [comment]
> what if a modpack creator decides to put an expensive block on this list to prevent breaking progression (warp drive)? would that just vanish?

This would be the fault of a modpack creator not correctly reading configs. There are two lists mentioned by zmaster, one that the game will prevent being used in a spacecraft at all, and one that the game will remove from a spacecraft once built.

**Comment by zmaster587** [comment]
> wait, so any block in that list will vanish?
> 
> what if a modpack creator decides to put an expensive block on this list to prevent breaking progression (warp drive)? would that just vanish?

@Archilyte, no, only blocks that are in the list AND are replacable (meaning that if you right click them with another block like dirt, it replaces the block instead of putting it next to it, think grass, fluids, etc).  So if it was a block like say, a diamond block, and the diamond block was in the blacklist, the rocket would fail to build and it would put a big red X where the diamond block is located.

> This would be the fault of a modpack creator not correctly reading configs. There are two lists mentioned by zmaster, one that the game will prevent being used in a spacecraft at all, and one that the game will remove from a spacecraft once built.

With the way it's implemented now, there's only one list, but it "intelligently" determines if the block should be deleted or prevent the rocket from building depending on whether it can be replaced.  At least, pending an answer to this:

>  Is there any reason a block that can automatically be replaced such as snow, fire, grass would want to not be allowed on the rocket but not automatically removed? If not, any block that could be replaced that is in the blacklist could automatically be destroyed on rocket build.


Maybe it would be better phrased as the following:
Is there a situation where anyone would want a replaceable block (like fluids, fire, snowcover) to not get removed automatically?  Or is there a situation where you'd want a NONreplacable block to get removed automatically (torches, redstone, pistons, etc)

**Comment by Archilyte** [comment]
> only blocks that are in the list AND are replacable (meaning that if you right click them with another block like dirt, it replaces the block instead of putting it next to it, think grass, fluids, etc).

well, that answers my questions, but it is still scary for it to remove fluid source blocks. ~~i can already imagine one of my friends placing molten infinity metal while the rocket is being built~~ im overthinking too much again

**Comment by C1ffisme** [comment]
> With the way it's implemented now, there's only one list, but it "intelligently" determines if the block should be deleted or prevent the rocket from building depending on whether it can be replaced.

That's fair, albeit Archilyte does bring up a good point with the fluid source blocks (Albeit I might not even add that to the list anyway since it might be cool to have a ship with a glass-block fluid tank)
