### ISSUE TITLE
(Suggestion) Torches pollute spacecraft atmosphere and sucks in oxygen

### ISSUE THREAD

**Issue by Tronzoid** [zmaster587/AdvancedRocketry#153]
I think it's kinda unrealistic how you can place a torch in a sealed off room, stand there for an hour and not be affected, what if torches needed oxygen to burn so if you placed a torch in an airtight room it would suck in oxygen and release CO2, making it dangerous to use torches in spacecraft so you needed to use Redstone lamps or electric light?

**Comment by DarkGuardsman** [comment]
I like the idea but its a bit rough to code in things like that. As you need to make the torch update, or make a handler do logic code for the torch. Both of which will slowly tank performance for large stations. That being said I support the idea of implementing pollution for things like this.

**Comment by Tronzoid** [comment]
To make it more simple, what of the torch went out as soon as there was no oxygen in the room?

**Comment by DarkGuardsman** [comment]
> To make it more simple, what of the torch went out as soon as there was no oxygen in the room?

It should already go out, though the code for this might be bug out every so often. Especially on modded torches

> To make it more simple, what if the block update could be toggled?

I hope @zmaster587 codes it with a disable option as a few of the servers I run already lose out on CPU cycles to O2 mapping

> or it was coded so it would drain oxygen faster?. 

I think this could be added as a config option with a float value representing a precentage

**Comment by Tronzoid** [comment]
I like the idea of an adjustable percentage value, Zmaster should add a block update toggle for slower computers.

**Comment by DarkGuardsman** [comment]
That should be easy to add as well, but most likely it will be multi-threaded to avoid slowing the main thread.

**Comment by Tronzoid** [comment]
What do you mean by multi threading?

**Comment by DarkGuardsman** [comment]
I thread can be thought of a single list of orders by the application to do a task, Having more threads allows the application to do more task at once. When a server is grinding to a slow and tps is low it is due to the main thread having too much to do between update ticks. To get around this developers can make more threads to do tasks outside of the main thread(main game). Then at the end of each update tick apply changes to the main game.

Also it is good to note that threads are not CPU cores but normally do run on different cores of a computer. So more cores your computer has the faster the game can run. As each thread will have its own little machine to do task on. If you do not have a lot of cores threading doesn't make the game run any faster. As threads have to share the same core with each other. This is the reason why running a lot of applications on your computer can slow each other down. As each application has to take turns accessing the core they are using.

As well MC has several built in threads:
Main Thread - Runs all worlds, entities, blocks, etc
Network Thread - gets data from connected players
File Thread - loads and saves the world, can sometimes stop the main thread to add chunks to the world

**Comment by zmaster587** [comment]
In theory there'd be only one update per atmosphere blob, so performance impact would be near 0.
