### ISSUE TITLE
Cannot make Astrobody Data Processor program planet ID chip

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [zmaster587/AdvancedRocketry#157]
I'm probably doing something wrong, but I can't seem to get my planet selector to communicate with my Astrobody Data Processor. I tried placing the Planet Selector inside the ADP multiblock in place of one of the stone slabs, but the multiblock would no longer form then.

**Comment by zmaster587** [comment]
The ADP is not required to program a planet ID chip anymore which is why it no longer requires a Planet Selector, planet ID chips are now programmed inside the rocket.  To do this you can put an unprogrammed Planet ID chip into the guidance computer on a constructed rocket and then shift right click the rocket and press the select planet button to program the chip.

**Comment by TheGuyRunningSouth** [comment]
Okay. That makes sense. Thanks.
