### ISSUE TITLE
[BUG] Very frequent lagspikes when saving dimensions 

### ISSUE THREAD

**Issue by TerminatorNL** [zmaster587/AdvancedRocketry#1589]
## Version of Advanced Rocketry
> `1.5.0.-139`

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A

## Version of LibVulpes
`0.4.0-56`

## Version of Minecraft
`1.12.2`

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A - Not tested, SpongeForge may play a role here.
## VisualVM results
![image](https://user-images.githubusercontent.com/13693773/57982344-673e1f00-7a44-11e9-8fc0-9df826872fee.png)

## Description of the problem
Frequent stutters that can last for up to 7 seconds give or take. Whenever the overworld is saved, this occurs. This ranges from every 10 seconds to 1 minute between lag spikes.

I have included a VisualVM profile screenshot that indicates that whenever PlanetEventHandler receives the WorldSaveEvent it spends alot of time saving the dimensions.

https://github.com/zmaster587/AdvancedRocketry/blob/555b8cb131a69a46f609a46364c77bdc9a8aa932/src/main/java/zmaster587/advancedRocketry/event/PlanetEventHandler.java#L517

Which calls:

https://github.com/zmaster587/AdvancedRocketry/blob/555b8cb131a69a46f609a46364c77bdc9a8aa932/src/main/java/zmaster587/advancedRocketry/dimension/DimensionManager.java#L538

I do not have a clear solution to fix this, but would it be possible to redesign the world saving mechanism or create a cooldown between saves to minimize the frequency of the lag spikes? I don't mind having a lagspike every 10 minutes, but one lasting for 7 seconds every 20 seconds can be quite annoying.

By the way, I like this mod, so thank you for making it.

**Comment by zmaster587** [comment]
The bit that's taking time seems to be committing to disk `java.io.FileDescriptor.sync`.  I kinda have to call this because otherwise things may not get saved since this function is responsible for committing data to the disk.  It is dependant on the speed of your disk typically.

Unfortunately I'm not really sure there's much I can do to space out saves.  The timing mechanism is controlled by vanilla, I just hook onto it.  The file that's saved is generally only a few hundred kilobytes so it shouldn't be taking that long.  Even most conventional drives can do megabytes per second usually.

Can you get me the size of the world/advRocketry/temp.dat and world/advRocketry/planetDefs.xml?  I'm wondering if they're abnormally large or something?  Also does it take a noticeable amount of time to copy files on your computer?

**Comment by TerminatorNL** [comment]
`./world/advRocketry/planetDefs.xml` = 11.4 kB (11397 bytes)
`./world/advRocketry/temp.dat` = 1.6 kB (1595 bytes)

Disk speed storage:

```
$ dd if=/dev/urandom of=test bs=1048576 count=2048
2048+0 records in
2048+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 9.69346 s, 222 MB/s
```

We have not ventured to any of the planets yet either.

**Comment by wisestump** [comment]
This issue still persists in:
Advanced Rocketry 1.16.5-2.0.0-10 build-10 for 1.16.5 (alpha)
LibVulpes-1.16.5-1.0.2-18-universal.jar
minecraft version: 1.16.5.

The problem, I think, can be in the fact that the manager syncs all dimensions. In my case (on default config) I have 94 files ~4kb each, which results in "Can't keep up! Is the server overloaded? Running 5456ms or 109 ticks behind" every 5 mins. Flushing and syncing so many files on HDD can be substantial. I've came up with a couple of ideas, if it's of any help.

- This task be offloaded to another thread. This way main thread won't freeze while manager flushes, synces and closes file handles.
- All dimensions can be dumped into a single large json file instead of a bunch of small ones.

**Comment by voidsong-dragonfly** [comment]
That's..... not how our stuff works. We have our single XML file, which is what we're saving to. Not those.

**Comment by wisestump** [comment]
But the lag spike happens in JSON flushes. Take a look at [this profile info](https://spark.lucko.me/NpdDkl4eB9). If I'm not mistaken the problem is syncing of many JSONs

**Comment by voidsong-dragonfly** [comment]
Riiiight... make a _new_ issue with that highlighted, don't do this in the future. Old issues about different things are closed for a reason

**Comment by wisestump** [comment]
Sorry, I'll make a new issue
