### ISSUE TITLE
[BUG] Glitches with Ender IO

### ISSUE THREAD

**Issue by Poxorosa** [zmaster587/AdvancedRocketry#1593]
Ender IO conduits doesnt working after rocket assembly and dissambling. Ender IO machines lost capacitors and items inside after dissasembling.
Minecraft version: 1.12.2

**Comment by Silfryi** [comment]
This is because you are trying to use non-simple TEs on rockets. EIO machines likely store their data somewhere not copied over, and because of that you are lucky you did not have worse corruption problems. As a general note, if the blocks you are trying to put on a rocket are TEs, if they are _not_ storage, it's probably a bad idea.
