### ISSUE TITLE
Collapse while building a rocket！！！

### ISSUE THREAD

**Issue by JackMeds** [zmaster587/AdvancedRocketry#1606]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-139-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-57-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/kVjGh3s4

## Description of the problem
crash while building a rocket

**Comment by zmaster587** [comment]
Does this occur without any other mods installed?

**Comment by JackMeds** [comment]
> Does this occur without any other mods installed?

No,I'm playing a modpack , called omnifactory
But，I don't think it's the other mods‘ problem.

**Comment by zmaster587** [comment]
The stack trace you gave me looks like it's a coremod or something, none of the code being run at the time of the crash is from advanced rocketry (See Stacktrace: in the crash report).  Additionally I've built a ton of rockets with just AR and libvulpes installed and cannot really invest the time in trying to debug a possible forge issue without knowing for certain that it definately something that occurs with only AR installed.

Due to the large number of issues I have to go through the time I spend is critical so it may take a lot longer for me to fix if I have to troubleshoot this without some degree of help.  (15 minutes x 260 issues just to get close to what's wrong is over 60 hours).

I would really appreciate it if you could give it a try though.  I've play tested the mod quite a number of times and have never encountered this issue while building a rocket, so I'm guessing it either the way you built it or what you built it with (neither of which I know, I cannot read minds) or it has to do with a mod in the pack.

What I would advise that you do is to make a copy of the modpack, remove all the mods from the mods folder except libvulpes and AR.  Test it with that exactly the same way you did when it crashed.  If it does crash, perhaps take a video or something or a screencap of the blocks you placed before hitting build in the assembler.

If it doesn't crash, add mods back until it does.  Once you get it to crash, try to run the game with just the most recent mod you added and AR.  If it crashes then.  Then please post here with that mod.

**Comment by JackMeds** [comment]
> The stack trace you gave me looks like it's a coremod or something, none of the code being run at the time of the crash is from advanced rocketry (See Stacktrace: in the crash report). Additionally I've built a ton of rockets with just AR and libvulpes installed and cannot really invest the time in trying to debug a possible forge issue without knowing for certain that it definately something that occurs with only AR installed.
> 
> Due to the large number of issues I have to go through the time I spend is critical so it may take a lot longer for me to fix if I have to troubleshoot this without some degree of help. (15 minutes x 260 issues just to get close to what's wrong is over 60 hours).
> 
> I would really appreciate it if you could give it a try though. I've play tested the mod quite a number of times and have never encountered this issue while building a rocket, so I'm guessing it either the way you built it or what you built it with (neither of which I know, I cannot read minds) or it has to do with a mod in the pack.
> 
> What I would advise that you do is to make a copy of the modpack, remove all the mods from the mods folder except libvulpes and AR. Test it with that exactly the same way you did when it crashed. If it does crash, perhaps take a video or something or a screencap of the blocks you placed before hitting build in the assembler.
> 
> If it doesn't crash, add mods back until it does. Once you get it to crash, try to run the game with just the most recent mod you added and AR. If it crashes then. Then please post here with that mod.

hey,I think I found the problem.
It seems that the AR is incompatible with the cat-server-pro（a bukkit-forge server core）

**Comment by zmaster587** [comment]
> > The stack trace you gave me looks like it's a coremod or something, none of the code being run at the time of the crash is from advanced rocketry (See Stacktrace: in the crash report). Additionally I've built a ton of rockets with just AR and libvulpes installed and cannot really invest the time in trying to debug a possible forge issue without knowing for certain that it definately something that occurs with only AR installed.
> > Due to the large number of issues I have to go through the time I spend is critical so it may take a lot longer for me to fix if I have to troubleshoot this without some degree of help. (15 minutes x 260 issues just to get close to what's wrong is over 60 hours).
> > I would really appreciate it if you could give it a try though. I've play tested the mod quite a number of times and have never encountered this issue while building a rocket, so I'm guessing it either the way you built it or what you built it with (neither of which I know, I cannot read minds) or it has to do with a mod in the pack.
> > What I would advise that you do is to make a copy of the modpack, remove all the mods from the mods folder except libvulpes and AR. Test it with that exactly the same way you did when it crashed. If it does crash, perhaps take a video or something or a screencap of the blocks you placed before hitting build in the assembler.
> > If it doesn't crash, add mods back until it does. Once you get it to crash, try to run the game with just the most recent mod you added and AR. If it crashes then. Then please post here with that mod.
> 
> hey,I think I found the problem.
> It seems that the AR is incompatible with the cat-server-pro（a bukkit-forge server core）

That's possible, Advanced rocketry was built against Forge alone.  Forge bukkit server cores are not supported because of the extensive changes they make to the server core that can sometimes interfere with functionality Advanced Rocketry requires to run.

I would not be opposed to merging a pull request with a fix.  But unfortunately I do not have time to support sponge, cat-server-pro, etc in addition to forge.
