### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by Rambo1636** [zmaster587/AdvancedRocketry#1621]
## Version of Advanced Rocketry
1.12.2-1.6.0-151-UNSTABLE build -151 for 1.12.2
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.4.1-59-UNSTABLE build -59 for 1.12.2
## Version of Minecraft
1.12
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
log of lag goggles mod, look at "Event Subscribers"
https://gyazo.com/883f9dd8361859ced39835bf74d66a52

## Description of the problem
when two players are not in the same place it causes lag. Look at the lag goggles results at the event subcribers

**Comment by zmaster587** [comment]
Could you use a tool like visualvm please?  The screenshot you have is cut off so I cannot read what class is even causing the problem.  Lag goggles also is missing some important diagnostic info like what is actually calling the code.  And 3rd... I'm wondering if lag goggles is even working right.  It's saying the advanced rocketry is taking up 417% of server tick time.  A number over 100% simply isn't possible for objects executing on the server thread.

Objects not executing in the server thread don't contribute to lag.

Unfortunately I need more info to figure out what's going on.  If you're using threaded atmosphere a 417% tick time can happen, however it will not contribute to server lag since it does not stop stuff on the server from happening.  However I cannot confirm that this is what's indeed happening without more information.

**Comment by zmaster587** [comment]
see #1624
