### ISSUE TITLE
[BUG] Exception ticking world : updateTimeLightAndEntities : updateWeather

### ISSUE THREAD

**Issue by Rsslone** [zmaster587/AdvancedRocketry#1633]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.6.0-155-universal

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y

>Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)

## Version of LibVulpes
LibVulpes-1.12.2-0.4.1-60-universal

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.

## Version of Minecraft
1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!

## Does this occur without other mods installed
- [x] N
Likely not, but each mod added for the test could take 20+ minutes to test, as the bug is not instant. Could be helpful to describe what types of mods could cause something like this.

>Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.

## Crash report or log or visualVM (if applicable)
https://gist.github.com/Rsslone/79485674e66fb153b2d9b475dda5999c

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.

## Description of the problem
The problem occurs after the server is running for about 20 mins to 2 hours.

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.

**Comment by cybmp3** [comment]
[crash-2019-07-22_14.06.06-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/3415907/crash-2019-07-22_14.06.06-server.txt)
same

**Comment by zmaster587** [comment]
@cybmp3 and @Rsslone Have you tried it without sponge?  Sponge tends to mess with a lot of internals so a crash report with sponge in it tends to not be all that helpful.

**Comment by Rsslone** [comment]
No I have not @zmaster587 but I might give it a test. I was able to get v1.5.0 to work however if that helps.

**Comment by janutemi** [comment]
Having the same problem on my forge (sponge) server on the latest version (161), all mods are working apart from this one

**Comment by cybmp3** [comment]
I think it is very important to be compatible with sponge.

**Comment by janutemi** [comment]
Tested version 1.5.0 and, just like Rsslone, I'm no longer having issues.

**Comment by zmaster587** [comment]
@cybmp3 It's unfortunately not easy to be compatible with sponge when sponge changes a good deal of minecraft's internals compared to just forge alone.  A mod like Advanced Rocketry unfortunately relies on some internal things other mods don't often use due to the complex and unconventional nature of the mod.

Things like rearranging weather to have different effects in different dimensions beyond just normal rain and snow for instance.

Keeping the mod compatible with forge and forge alone, is a higher priority than sponge compat due to the fact it is more difficult and time consuming to guarantee support multiple platforms at once and time is unfortunately something I have been very short on the last few years.  If you're willing to help or know somebody willing to help maintain AR for sponge, by all means support is very welcome.  But at least while it's just me working on this project, bugs that affect the forge version or things that make the game difficult to play will have priority over sponge support.

@janutemi @Rsslone The reason this cropped up in 1.6 is because the weather system was not working properly prior to 1.6.  Rain and snow would occur in places it shouldn't because the code to disable the rain/snow on airless planets wasn't being run.  Unforunately, sponge has changed how the world its data in `worldinfo`.  `worldinfo` is responsible for controlling weather.  If I fix it for sponge, there's a good chance it'll break it for people NOT using sponge unless I start implementing a different solution for sponge and forge, effectively doubling the amount of code to maintain for this feature.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.6.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/3449865/AdvancedRocketry-1.12.2-1.6.0-universal.jar.zip)

Can @janutemi or @Rsslone report whether or not it still crashes with this build?

**Comment by janutemi** [comment]
Alright I'm letting it run with the sent version, will reply in a few hours if it functions properly (or soon if it crashes).

**Comment by janutemi** [comment]
Haven't experienced a crash or any issues, seems like the sent build works fine.
