### ISSUE TITLE
[Request] Custom planet icons!

### ISSUE THREAD

**Issue by eagleyes005** [zmaster587/AdvancedRocketry#1637]
Is it possible to add custom planet icons? Like make it load from the resource folder?

**Comment by Poxorosa** [comment]
PlanetDefs has customIcon tag. U can set custom icons like lava, marslike, earthlike, waterworld, moon or ice

**Comment by eagleyes005** [comment]
But no external icons, and that is what i mean.

**Comment by ThrowawayIssueTeller** [comment]
I second this request. Having custom Icon's would be awesome.

**Comment by BasieBrinkie** [comment]
quote from zmaster:
> in future you will be able to put a texture in assets/advancedrocketry/textures/planets/ in a resource pack and just use the name of the png

Which would mean it is possible using a resourcepack or with the mod resourceloader

**Comment by TripTripy** [comment]
Sooo This is implimented?

**Comment by Deliphin** [comment]
Just to voice my support of this idea:

With custom planet icons, we can have a lot more interesting variety revealed from the map itself. Not every planet is going to look the same before you go there, just like how every planet IRL seen through a telescope looks somewhat different from most of the others.

We could have earth's graphic be a flat earth.
We could have a planet be a void world with a space station, and show as that on the map.
We could have special planet textures for modded worlds like Twilight Forest.
We could have broken up planets for sky island planets, like the Aether.
We could have useful icons embedded in the graphic, denoting risks like no oxygen or hostile mobs.
We could have it look like the terrain on the planet, matching dark green oceans with dark green water on a swamp planet.

Lastly, this means people wouldn't complain about the fact the mod only has 6 icons, just because other people would then be able to make third party ones.
