### ISSUE TITLE
[BUG] Crash on doWeatherStuff

### ISSUE THREAD

**Issue by MuteTiefling** [zmaster587/AdvancedRocketry#1670]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.6.0.-162

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>0.4.1.-1

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N

At least, not that I've been able to discern. I'm using AdvancedRocketry for the basic dimension, JustEnoughDimensions for a series of tweaks, including making this the spawn dimension. I'm also using BiomeTweaker to create the two biomes permitted on this world. At first, weather was allowed in those biomes but now it's disabled via BiomeTweaker and this still occurs. 

JustEnoughDimensions 1.6.0-dev.20190711.220109 
BiomeTweaker v3.2.354  

## Crash report or log or visualVM (if applicable)
>https://gist.github.com/MuteTiefling/04d1252e3d7d5e8e3a936e567747c3f3
>https://github.com/maruohon/justenoughdimensions/issues/47

## Description of the problem
After sitting around in the world for a period of time, the game crashes with the attached errors. Including snippet here for ease of future searches.

If you'd like to see any configs, I'll happily provide them. 

> Thread: Server thread
> Stacktrace:
> 	at zmaster587.advancedRocketry.world.provider.WorldProviderPlanet.doWeatherStuff(WorldProviderPlanet.java:132)
> 	at zmaster587.advancedRocketry.world.provider.WorldProviderPlanet.updateWeather(WorldProviderPlanet.java:124)
> 	at net.minecraft.world.World.func_72979_l(World.java:2564)
> 	at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:1236)
> 	at net.minecraft.world.World.func_72835_b(World.java:2541)
> 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:179)
>

**Comment by maruohon** [comment]
This crash happens because JED allows using per-dimension WorldInfo overrides, ie. dimensions can have their own separate WorldInfo object, with their own separate values. JED does this via reflection, by changing the WorldInfo object of those dimension from the default `DerivedWorldInfo` into a custom `WorldInfoJED` object (which extends the base `WorldInfo` class).

It looks like AR has a check for Sponge in that piece of code, but if that is false, then it just assumes the WorldInfo to be `DerivedWorldInfo` without checking `instanceof`. (Off-topic: I kinda find it odd that it would change the weather of the overworld to get the planet to not rain... but I guess it's just due to the vanilla "all dimensions share everything" philosophy.)

**Comment by MuteTiefling** [comment]
Well, I've managed to get around this by using JED to disable weather in just the one dimension by applying the gamerule doWeatherCycle false there. @maruohon thanks for the comments, they got me to this workaround
