### ISSUE TITLE
[BUG] Airtight Seal doesn't work with non-ItemArmor armor

### ISSUE THREAD

**Issue by Archengius** [zmaster587/AdvancedRocketry#1675]
## Version of Advanced Rocketry
>1.12.2-1.6.0-162

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>1.12.2-0.4.1-59

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N (vanilla armor uses ItemArmor only)

## Description of the problem
Many mods providing advanced armor (Dark Steel armor from EnderIO, Manasteel armor from Botania, Nano Suits from IC2 and so on) don't use ItemArmor because of different ways of handling durability and armor damage. Such armor still falls into armor enchantment category and Airtight Seal enchantment can be applied to it. However, it doesn't work for any armor not extending ItemArmor. Relevant line of code:
https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/util/ItemAirUtils.java#L168

**Comment by Archengius** [comment]
Still relevant.

**Comment by zmaster587** [comment]
it appears as though darksteel armor does indeed use `ItemArmor` https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/java/crazypants/enderio/base/item/darksteel/ItemDarkSteelArmor.java#L82

IC2's nanosuit extends `ItemArmorElectric` which in turn extends `ItemArmorIC2`, which in turn extends `ItemArmor`.

Manasteel armor also extends ItemArmor, https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/armor/manasteel/ItemManasteelArmor.java#L50

If those armors are not working, I think it pretty unlikely it's https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/util/ItemAirUtils.java#L168 that is the cause since they should all pass that check, I suspect there's probably something else going on if it's not sealing.

If you're using an enchanted chestpiece, have you made sure to try to put O2 into it using the gas charge pad?

**Comment by zmaster587** [comment]
granted I did run it through the chemical reactor to get the item, but when I spawn in a new uncharged nano chest plate, process it in the chemical reactor with a diamond and super high pressure tank to get the sealed version.  Then fill it with O2 by stepping on a gas charge pad filled with O2.  It seems to protect me from space.  I have also partially charged it in an MFE after enchanting it to make sure it wasn't some weird thing with the amount of charge in the suit.  Still seemed to protect me from space.

Mods:
AdvancedRocketry-1.12.2-1.6.0-191-universal
industrialcraft-2-2.8.170-ex112
LibVulpes-1.12.2-0.4.2-69-universal


![image](https://user-images.githubusercontent.com/3536685/71639038-fe0ac500-2c3c-11ea-9078-55ffb8278d3c.png)

![image](https://user-images.githubusercontent.com/3536685/71639042-0a8f1d80-2c3d-11ea-9fc6-5e8070cadf5a.png)


Would you be able to give me steps to get a specific piece of armor that's not working for you?
