### ISSUE TITLE
Villages are being generated on other planets, even though the config is set to false.

### ISSUE THREAD

**Issue by Gliese-832-c** [zmaster587/AdvancedRocketry#1725]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>Latest 186

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>Latest 68

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A

## Description of the problem
>Villages spawn on my habitable planets, even though it's set to false in the config. Those planets have biomes o plenty biomes, if that matters.

**Comment by zmaster587** [comment]
Should be fixed by 76e4d611a2e25842731367a2d60de579f2da27e9.

Originally the intent was to completely move the setting over to the planetDefs.xml `generateStructures` tag, but I can see how that might get confusing.  After next release the setting in the config should act as a master toggle of sorts.
