### ISSUE TITLE
worldedit crash

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#173]
When moving space station with worldedit i get the following crash
http://paste.ee/p/2ox7z

might be that i have done something wrong but i thougth i would report it incase it might be some other problem.

**Comment by zmaster587** [comment]
What number is the atmosphere handling set to in the advanced rocketry
config file?

On Aug 7, 2016 10:21 AM, "bludde" <notifications@github.com> wrote:

When moving space station with worldedit i get the following crash
http://paste.ee/p/2ox7z

might be that i have done something wrong but i thougth i would report it
incase it might be some other problem.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zmaster587/AdvancedRocketry/issues/173>, or mute the
thread

**Comment by bludde** [comment]
I:atmosphereCalculationMethod=3

**Comment by zmaster587** [comment]
If you set it to 0 or 1 does it still happen?

**Comment by bludde** [comment]
will try it later to confirm

**Comment by bludde** [comment]
works on atmosphereCalculationMethod 1 and 2 but on 3 it crash on so i will close this!

**Comment by zmaster587** [comment]
Still needs to be fixed though
