### ISSUE TITLE
[BUG] Mob Property Randomness Compat

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#1730]
## Version of Advanced Rocketry
>1.6.0-187

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
0.4.2-68

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
Compat issue

## Crash report or log or visualVM (if applicable)
https://paste.dimdev.org/cafepuzihe.mccrash

## Description of the problem
When using mob property randomness I tried to whitelist a planet in their json file but it ended up crashing.  When I asked the author he said he used GetDimensionType to find the dimension and apparently advanced rocketry doesn't really use it.  I tested with other modded dimensions and it worked fine so it seems to be because ar dimensions aren't registered to the getdimensiontype thingy.  The author of mob property randomness told me he was going to fix it but he also told me I should report it here anyways so that's what I'm doing right now.

**Comment by mxnmnm** [comment]
They released an update to fix it but you should probably register them correctly so it doesn't cause other mod compat issues

**Comment by mxnmnm** [comment]
I guess you can close this if you won't use GetDimensionType for whatever reason although I'm not in case u wanna do that

**Comment by zmaster587** [comment]
I'm not convinced that's the issue since dimension type is something AR implements already, it's a hard requirement for the mod to even work with 1.12 since the "registerDimension" function requires the dimensiontype to be passed.

For reference they're registered here: https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/dimension/DimensionManager.java#L54

and created with the dimension here: https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/dimension/DimensionManager.java#L759,
and here https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/dimension/DimensionManager.java#L418

Given the crash report though, I'm almost wondering if Mob randomness compat is confusing dimension ID and dimensionTYPE ID.  153 is WAY too high for what I'd expect for dimension type.  Unfortunately I can't verify if this is the case or not because his 1.12 code isn't on github

**Comment by mxnmnm** [comment]
I guess it makes sense for you to do things differently because of the amount of dimensions needed (although idk exactly what since I barely understand basic code lol) but since you're aware of whatever he was suggesting I think I'll just close the issue especially because they did something on their end to fix it.
