### ISSUE TITLE
[BUG] Observatory not working on space station(s)

### ISSUE THREAD

**Issue by sossololpipi** [zmaster587/AdvancedRocketry#1755]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.6.0

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
No

## Version of LibVulpes

0.4.2-69

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N/A . Seen on Enigmatica 2 non-expert.

## Description of the problem
>[How can you reliably reproduce the problem

Start up Enigmatica 2

Go on a space station

Try to make an observatory work on said space station

Fail at it

**Comment by dmodoomsirius** [comment]
does this happen with the latest Advanced Rocketry versions? as that is very old versions?
https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/2853719
https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/2841976

**Comment by Silfryi** [comment]
@sossololpipi Is the station in darkness? That can also be the cause.

**Comment by sossololpipi** [comment]
> @sossololpipi Is the station in darkness? The station being in the light (IE not using the rotational controller) can also be the cause.

Yes it is. I've moved it to Earth, where there is much more light and less space, but it worked when I moved it.

**Comment by sossololpipi** [comment]
> does this happen with the latest Advanced Rocketry versions? as that is very old versions?
> https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/2853719
> https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/2841976

The version is 1.6.0 ; I think that's the latest non-unstable version of AR.

**Comment by zmaster587** [comment]
is the sun underneath the station when you're testing?

**Comment by sossololpipi** [comment]
> is the sun underneath the station when you're testing?

yes it is. also tried when the sun is over. wouldn't make sense that the observatory works through a planet though

**Comment by zmaster587** [comment]
> > does this happen with the latest Advanced Rocketry versions? as that is very old versions?
> > https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/2853719
> > https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/2841976
> 
> The version is 1.6.0 ; I think that's the latest non-unstable version of AR.

Which version of 1.6.0, though?  there should be a build number after it.

I went ahead and tested it with AdvancedRocketry 1.12.2-1.6.0-193.  It appears to be working.

![image](https://user-images.githubusercontent.com/3536685/72196463-37ce8f00-33e6-11ea-81a9-4f9cf29150e5.png)

What I did here was 
- build the observatory from the holoprojector layout (one creative power supply, one databus)
- rotated the station approx 95* so that the planet was slightly above
- I went into the observatory's mainblock by rightclicking it, then toggled the enabled state in the top right so that it showed line and black O.  At this point the observatory visibly opened up.
-  I then put 1000 distance data into the databus
- I went back into the UI in the observatory, clicked on the asteroid tab up top.
- In the asteroid tab I put a brand new asteroid chip into the bottom left slot, then I hit "Scan!".  At this point a list of asteroids shows up
- I selected an asteroid, then hit the gear icon between the two slots.  At this point the chip moved from the left most slot to the slot to the right of it.  The chip now reads Asteroid Chip Asteroid-50656 and a bunch of unfilled data.

If you replicate these instructions, does it still fail to work?  At what point does it fail?

**Comment by sossololpipi** [comment]
> does this happen with the latest Advanced Rocketry versions? as that is very old versions?
> https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/2853719
> https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/2841976
> 
> The version is 1.6.0 ; I think that's the latest non-unstable version of AR.
> 
> Which version of 1.6.0, though?  there should be a build number after it.
> I went ahead and tested it with AdvancedRocketry 1.12.2-1.6.0-193.  It appears to be working.
> 
> What I did here was
> 
> build the observatory from the holoprojector layout (one creative power supply, one databus)
> rotated the station approx 95* so that the planet was slightly above
> I went into the observatory's mainblock by rightclicking it, then toggled the enabled state in the top right so that it showed line and black O.  At this point the observatory visibly opened up.
> I then put 1000 distance data into the databus
> I went back into the UI in the observatory, clicked on the asteroid tab up top.
> In the asteroid tab I put a brand new asteroid chip into the bottom left slot, then I hit "Scan!".  At this point a list of asteroids shows up
> I selected an asteroid, then hit the gear icon between the two slots.  At this point the chip moved from the left most slot to the slot to the right of it.  The chip now reads Asteroid Chip Asteroid-50656 and a bunch of unfilled data.
> 
> If you replicate these instructions, does it still fail to work?  At what point does it fail?

I can't replicate those instructions at the moment, I'll tell you the results once I can

**Comment by zmaster587** [comment]
> I can't replicate those instructions at the moment, I'll tell you the results once I can

That's fine, no need to rush

**Comment by ChristiaanG** [comment]
@sossololpipi where you able to solve this issue? I'm having the same problem that the observatory won't open on my space station even when rotated away from the sun. The versions that I run are:

Advanced Rocketry: 1.7.0-208
Minecraft: 1.12.2
Vulpes library: 0.4.2-74

Thanks for the help.

![2020-04-06_20 55 00](https://user-images.githubusercontent.com/17250855/78594703-0d576b00-7849-11ea-9a77-ea38f2194d06.png)
![2020-04-06_20 55 25](https://user-images.githubusercontent.com/17250855/78594706-0df00180-7849-11ea-9e36-266cc98c08d5.png)

**Comment by sossololpipi** [comment]
no, I forgot about it, and lost the save where it happened
