### ISSUE TITLE
Server Crash with lasted version [SPONGE] [SERVER CRASH]

### ISSUE THREAD

**Issue by Javichuuu** [zmaster587/AdvancedRocketry#1772]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-204-universal

## Have you verified this is an issue in the latest unstable build

- [x] N/A

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-74-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed

- [x] N/A

## Crash report or log or visualVM (if applicable)

https://pastebin.com/vujKLit5

## Description of the problem

Forge version: forge-1.12.2-14.23.5.2847-universal
SpongeForge version: spongeforge-1.12.2-2838-7.1.8

When you started the server for the first time everything works correctly, but if it turns off and on again the server crash.

I don't know why it could be the mistake, thanks in advance.

**Comment by Javichuuu** [comment]
UPDATE

Without spongeforge issue continue

**Comment by dmodoomsirius** [comment]
Can you provide the crash report without sponge please?

**Comment by Javichuuu** [comment]
NEW PASTE

https://pastebin.com/2LJsGYNh

**Comment by zmaster587** [comment]
Does this occur with only advanced rocketry and libvulpes installed?

**Comment by Javichuuu** [comment]
I have a server with a map started out. So if quite mods breaking the map. Advanced Rockertry added later, but I like much this mod, So added it. Sorry for my bad english

**Comment by zmaster587** [comment]
> I have a server with a map started out. So if quite mods breaking the map. Advanced Rockertry added later, but I like much this mod, So added it.

Would it be possible to make a copy of the world and test on that so you don't need to destroy the existing world?  I want to rule out the possibility of it being something other  than a mod compat issue.  Because the approach to fixing the issue could be much different.

If it no longer occurs with only AR installed, im thinking it could be a config issue, AR could be having its worldProvider assigned to a dimension that's not created by AR for instance.  The fix for that would just be a config edit.  If it's not that, it could be some mod replacing world providers or something, and that's it's own rabbit hole.  But determining whether or not the issue occurs with just AR installed is a the first step.

> Sorry for my bad english
No worries

**Comment by Javichuuu** [comment]
Thank you very much for your immediate attention, I will try what you have told me and I tell you

**Comment by Javichuuu** [comment]
Hello again, I just tried what you told me, I made the backup of the world, and I tried to generate a new one, and the crashing is the same

**Comment by dmodoomsirius** [comment]
my recommendation on the backup world is to without spongeForge add one or two mods at a time to see what mod is causing that issue. that will help narrow down. then once you find the offending mod. try with just AR, LibVulpes and the offending mod.

**Comment by Javichuuu** [comment]
I think I have detected the problem.  And as strange as it may seem, it is the world that gives the problem, because I have tried with all the mods, generating a new world and no longer gives the error, but nevertheless with my world it continues giving the error.  Any recommendation ?
