### ISSUE TITLE
[BUG]Nuclearcraft oxygen lakes spawning in moon

### ISSUE THREAD

**Issue by EnderN3x** [zmaster587/AdvancedRocketry#1773]
## Version of Advanced Rocketry
>1.12.2-1.7.0-204-universal

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
>1.12.2-0.4.2-74-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N

## Description of the problem
>Nuclearcraft Oxygen is spawning in pool and lakes in the MoonDark biome. Oxygen is a fluid that flows up to the sky. When it spawns in pools and lakes the incredible number of flowing blocks causes the game to freeze and sometime crash.

**Comment by Silfryi** [comment]
This is a side effect of some of the planet generation code, due to Advanced Rocketry spawning liquid oxygen there. It's using NuclearCraft's block instead of Advanced Rocketry's. What needs to happen is to have a blacklist for NuclearCraft oxygen.

**Comment by EnderN3x** [comment]
Is there a config where I can blacklist the nuclearcraft fluid? I spent a couple hours looking last night but wasn't able to find anything.

**Comment by EnderN3x** [comment]
I found a closed issue from a while back that covers the conflict with nuclearcraft. https://github.com/zmaster587/AdvancedRocketry/issues/931#issue-272062389 

In this Thutmose covers how when the fluid is getting registered twice and it is getting overridden. I have also confirmed in my testing that there is no recipes that use AdvRocketry Oxygen as well as it being impossible to spawn in to the world. Whenever I attempt to spawn the AdvRocketry it automatically spawns the nuclearcraft oxygen that flows up.

**Comment by zmaster587** [comment]
@EnderN3x The behaviour you're experiencing is a result of of #931.  Since two fluids cannot exist with the same name one or the other gets chosen.  For the most part that's determined by forge mod loading order.  If nuclearcraft is loaded before AR is, nuclearcraft's O2 will be used for all O2 in AR.  If AR is loaded before nuclearcraft, is nuclearcraft handles fluid correctly, then AR's fluid would be used for everything in nuclearcraft.

> Is there a config where I can blacklist the nuclearcraft fluid? I spent a couple hours looking last night but wasn't able to find anything.

No, there's not, doing so would be a violation of convention (and was the whole reason for #931).

I suppose one resolution to the issue would be to create another O2 fluid (LOX or something?) and have that spawn instead.

**Comment by EnderN3x** [comment]
I appreciate the fast response. Is there a way I can do that on my end? It isn't the end of the world or anything if I can't, but if possible I would like to allow the random generation of planets with all the normal biomes.

**Comment by zmaster587** [comment]
Idk if there's a mod out there that can let you mess with load order or not, but if that's a thing you can enforce AR loading before nuclearcraft.  Otherwise you may just have to remove all the O2 oceans from the planetDefs.xml.  That'll at least make it playable.  You could maybe replace it with nitrogen, it wouldn't be too far off from default gameplay since either have a chance to spawn.

**Comment by zmaster587** [comment]
I'll see if creating a 2nd O2 fluid is viable to prevent this issue again in the future.
