### ISSUE TITLE
Planet Assets big

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#178]
In update 0.6.8 the planet assets ar big, maing the mod bigger then it needs to be.
![big](https://cloud.githubusercontent.com/assets/1352518/17690218/63b5b51c-638d-11e6-9b84-f73bf869b91e.png)
 is it possible to downscale them abit?

**Comment by bludde** [comment]
did not see the amazing looking planet, this is AMAZING:D

**Comment by zmaster587** [comment]
You're right, they are a bit large, what I'd like to do is use a jpeg rather than a png,  (A Jpeg uses lossy compression so some information is lost for the sake of space, but it looks more or less the same unless high compression levels are reached)  However, I need to make sure minecraft can even load a jpeg first.

**Comment by bludde** [comment]
yeah to strip it down abit would be nice, but the planets looks soo good so it doesn't matter.

**Comment by zmaster587** [comment]
By converting to jpg i was able to reduce the total size of the mod down to 7.1MB from 28MB without any visible loss in quality (and a touched up earth, looks less jagged now...)  I would close this but... it's already closed.

**Comment by bludde** [comment]
Dont worry there will always be alot of cases to close with me around:D
