### ISSUE TITLE
[Request]- New Planet Def features

### ISSUE THREAD

**Issue by CTH999** [zmaster587/AdvancedRocketry#1848]
Okay, I am just getting started using the planet.def file, and while I bet this can be done, I want to request it if not. I generated a world, and I noticed that the planet file inside that world has things like "Craters enabled" and "Geodes enabled" and "Structures enabled". I think we should be able to define features like that the planet.def file (I am making the solar system, so I need a moon of jupiter that has volcanoes. Also, better documentation would help, such as, what are the structures? (Add them to the [Wiki](https://github.com/zmaster587/AdvancedRocketry/issues/1847)).

Also, I think it could be neat if the planets.def file generated by default in the config, and that was how AR got the default star systems. That would sure make editing easier!

**Comment by Silfryi** [comment]
You can define those structures in the actual planetDefs file. Neither Z nor I has infinite time on our hands, so we cannot handle all the documentation. If you want better documentation that isn't reading the source, I suggest you update the wiki which is perfectly viable for others to update. Because AR makes unique planets for each world, having a config-level planetDefs be generate by default makes no sense.

**Comment by CTH999** [comment]
fair enough. I just ment like allow villages to generate on a planet, which I am looking mor in depth and it appears like a yes (I still have more testing. How bout a temporary second moon of the earth with villages... oh, is this still on? 

Also, I would close this now but, well... your ahead of me
