### ISSUE TITLE
Breathable Space not possible

### ISSUE THREAD

**Issue by Yenlon** [zmaster587/AdvancedRocketry#1867]
## Version of Advanced Rocketry
>1.7.0.-227

## Have you verified this is an issue in the latest unstable build
- Yes

## Version of LibVulpes
> 0.4.2.-75

## Version of Minecraft
> 1.12.2

## Does this occur without other mods installed
-  N/A

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
> No crashs

## Description of the problem
First of all, YES I know that breathable air in space is illogical, but I'm also sick tired of the current oxygen system. All I want is to breathe in my quite giant space station without spacesuit and oxygen vents. So I go to the saves folder to the advanced rocketry folder and then finally to "planetDefs" in order to configurate the space dimension (I made sure that the DIMID is the same as in the general config) and edit the "atmosphereDensity" to 100 (zero by default) and the "avgTemperature" to 287 (earthlike, just to be sure). But whenever I do all this and then join my world all the edited settings for the space dimension go back to default, also both tags go to 0. It doesnt matter if I join the world in the overworld or in space or somewhere else, all tags will go to default and I still cant breathe in space without oxgen system or spacesuit. Is this issue a bug or is this intentionally?

**Comment by zmaster587** [comment]
Space is treated as a "special dimension" because properties vary from space station to space station.  That's also why the planetDefs has no effect on space stations, it's a totally different system.  Long technical story but TL;DR, it's not feasible to make one dimension per space station.

So while it's not quite an intentional design choice, there's not really an easy fix either.
That said if you don't like the oxygen system, you can just turn it off entirely by setting `EnableAtmosphericEffects` to false in the advancedRocketry.cfg file.

**Comment by Yenlon** [comment]
Is there really no other way to change it? As I have no problem that hazardous planets require a spacesuit it would be pretty annoying to change "EnableAtmosphericEffects" to false whenever I enter my space station and then back to true when I enter a dangerous planet, because I have to restart the game in order for the changes to come into effect!

**Comment by Silfryi** [comment]
Yes, that is the only way. The oxygen system was only designed to be enabled or disabled as a whole.... though some atmospheric effects I don't think will obey that specific config, actually, because I didn't think of it when I added them. Vacuum damage might be the only thing that is affected (which is a bug that I should fix).
