### ISSUE TITLE
[Request] More Planet Distance and Question

### ISSUE THREAD

**Issue by CTH999** [zmaster587/AdvancedRocketry#1903]
**What do you think is missing or what do you think can be done better**

So, I think that heating should be done more realistically, and that distances past 200 for planets are still visible (Just zoom out, you can zoom in on a different area)

As for the heating, could you use the solar system to make a relistic model (Take the tempatures of the planets, and make the changes based on those), so a ratio-based solar-system with a star that has a temp of 100, and earth at 100, is just like earth. Murcury, at 23.9973 (Let's call it 24) The values for distance based on the sun being 100, and earth being 100 are: (I totally didin't make a spreadsheet) (I could connect it, but the numbers don't quite work out, since some of the time I found the perigee (Closest point), other times the apogee (Farthest point), and still more the semi-major accses (The average between the too, and the value I want to use. I'm thinking of using the numbers from universe sandbox 2.

So, if you get the temps to to match with logic and those values, perfect!

Then, could you make it where the star temp variable isn't linear, (Since halfing the rate of fusion decreases the solar energy output way more), so make it to where if I half the sun, I just need to half everthing, not move everything based on an exponent (It will make determining what temp to use harder, but you can always show the equation!)

Then, what number is the moon from earth (right now) (Basicly, what number must I input to the moon to make it look like the moon)

**Comment by Silfryi** [comment]
I am using the equations used for IRL average temperatures for temperature, there's no more realistic that I can get for that. They're missing albedo currently, but that can't be done without biomes - which depend upon temperature. Star temp not being linear is dumb because it's exactly that, temperature.... it's not the rate of fusion. And making it nonlinear would confused the _hell_ out of people while making my job harder. Rate of fusion would be something different/ Earth-moon distance is 100. It's normalized to Luna for planetary satellite distances and Sol and Earth for solar distances.
Zooming out is something that _could_ happen but has not yet. It's on the todo and IIRC there are other issues for it. 
Since I've answered all your questions, could you kindly close this issue?

**Comment by CTH999** [comment]
great! and for the fusion, what I meant is that as a star drops in energy creation, the luminosity drops much quicker (I honestly don't understand the reason), but I can see how that would cause an issue. I get that zooming is not a high priority, so, just glad it's there. And, i'm pretty sure authors are able to close issues (I haven't made anything on github yet...)

and, what, you don't want to spend hundreds of hours making the relistic atmosphere calcs?!
fair enough

thanks!

**Comment by Silfryi** [comment]
I cannot because I don't have commit perms I think. It's not so much "I don't want to" (though I don't, and wouldn't know how to anyway), it's "AR doesn't have the computing power to run the scientific models for it", because that'd be the realistic way.
