### ISSUE TITLE
[BUG] Compatibility issue.

### ISSUE THREAD

**Issue by Boscpeing** [zmaster587/AdvancedRocketry#1910]
## Version of Advanced Rocketry
>[232 build]
## Have you verified this is an issue in the latest unstable build
- [x] N.
## Version of LibVulpes
>[0.4.2-1]
## Version of Minecraft
>[1.12.2]
## Does this occur without other mods installed
- [x] N/A
## Description of the problem
>[This is a compatibility problem with Galacticraft. The reason i am posting it here is because. the problem doesn't happen when 
   I removed Advanced Rocketry to find which mod was doing it.
   When I go to the Galacticraft space station gravity is broken. It pushed me into the air the first time and then did the opposite after putting Advanced Rocketry back in .
## Version of Galacticraft mods(the three base one's)
>[4.0.2.288]

P.S By the way when Galacticraft oxygen was not on. it wasn't replaced by Advanced Rocketry mod's one. You didn't need oxygen stuff . (this was only tested on galacticraft moon.) I was going to change it to work on there system for there mod any way but just to let you know.

**Comment by MetallicMatte** [comment]
This is definitely a confirmed bug, galacticraft themselves said they know it happens. The two mods have different spaces and different moons and “advanced rocketry sometimes takes over”. Its a known bug and an annoying one. The Galacticraft page said the Advanced Rocketry wrote a config to fix this exact problem in 1.7.10 (which i can’t find anywhere) so they should fix there mod interfering by doing the exact same thing for more versions. I play on 1.10.2 right now and I have the same problem as you. Even with full oxygen tanks and all the equipment and any galacticraft space suit it still kills me because of pressure. Advanced rocketry please fix your mod.

**Comment by Silfryi** [comment]
Advanced Rocketry is not supporting 1.10 anymore - or 1.7.10, for that matter. Please update to the latest version on 1.12 and test whether or not this happens - if it does, then please report it.

**Comment by dmodoomsirius** [comment]
for both of you is this config option set to true,

![2020-09-23_14-37-38](https://user-images.githubusercontent.com/4022743/94055011-5fb22700-fdaa-11ea-8d42-9da4e5785cad.png)

**Comment by Boscpeing** [comment]
dmodoomsirius Yes the config wastrue when I posted it, but I have since changed it .when it was set to true i could walk on the Gc moon with no oxygen system it did override the gc one but didn't replace it with the advanced rocketry one .
