### ISSUE TITLE
Dies from death.attack.Heat when i start a new world . 1.16.5

### ISSUE THREAD

**Issue by kirillka77734** [zmaster587/AdvancedRocketry#2026]
## Version of Advanced Rocketry
1.7.4-4 
1.16.5

## Have you verified this is an issue in the latest unstable build
- Y 

## Version of LibVulpes

1.0.1-6
1.16.5
## Does this occur without other mods installed

idk , Y 
![image](https://user-images.githubusercontent.com/74816322/112719005-855deb80-8f07-11eb-9e4b-49c6f8921e98.png)

## Crash report and log, or VisualVM snapshot (if applicable)
https://imgur.com/a/F8fn7V9

## Description of the problem
When i create a new world , all entites start to burn and getting slow poition and if i die i see 
" death.attack.Heat " 
This " death.attack.Heat " from advanced rocketry

**Comment by redgoblin88** [comment]
i am also having this bug.

when i make a new world every single animal dies from slowness IV and burning.
when i go into survival mode i also spontaniously combust and get the debuff

upon removing advanced rocketry the "issue" (spontanious combustion and slowness) goes away and everything lives with no burning.

advanced rocketry version: 1.16.5 - 1.7.1.4
lib vulpes version: 1.16.5 - 1.0.1.6
forge version: 36.1.0
![2021-03-28_16 35 39](https://user-images.githubusercontent.com/13396472/112758213-f9ba8c80-8fe4-11eb-83ae-60532a6091a7.png)

**Comment by Nooska** [comment]
![AdvRockBurn](https://user-images.githubusercontent.com/36108100/113190177-4f4c9e80-925c-11eb-8e71-5cef0f8607bf.png)
Also experienceing this, with other mods installed. The last 2 additions are Advanced Rocketry (and LibVulpes - had to manually install this) and Chunk-Pregenerator added in the same batch.

* Happens anytime anything spawns (unconfirmed for hostile mobs)
* Does not happen after disabling Advanced Rocketry (in a world where it happened before)
* Does not happen in the same world after re-enabling Advanced Rocketry
* Does not happen in another world after reenabling Advanced Rocketry
* Does happen after quitiing and reloading a newly created world (both before dieing to it and after)

Edit:
AdvRocketry version: 1.16.5-1.7.1-4-universal
LibVulpes: 1.16.5-1.0.1-7-universal
Forge: 36.1.3

Edit 2:
Does NOT happen with justy Advanced Rocketry and LibVulpes, so clearly an interaction bug.

Edit 3:
Going back to the original pack, it does happen on creating a new world, also after quitting to title and going back in, but it stops after quitting and restarting minecraft for the particular world.

Edit 4:
Copying just the 6 mods that are in common with kirillka77734 does NOT cause the issue when starting a new world.
Common mods: 
- Advanced Rocketry 1.16.5-1.7.1-4-universal
- Architectury 1.10.139-forge (kirrilka is on .138 but happened to me on .139 as well)
- FTB GUI 1605.2.1.41
- JEI 1.16.5-7.6.1.75
- Journeymap 1.16.5-5.7.1
- LibVulpes 1.16.5-1.0.1.-7-universal

These are the only common mods between me an Kirillka, but just using these does NOT cause the problem (unless its something with the seed, and I haven't seen it, but it is persistant between generations on the pack that I've screenshotted)

**Comment by zmaster587** [comment]
> Going back to the original pack, it does happen on creating a new world, also after quitting to title and going back in, but it stops after quitting and restarting minecraft for the particular world.

this is particularly telling.

Bit of an explainer as to why real quick: with the update to 1.16 it was no longer possible (as far as I can tell) to use code to create AR's planets, so the workaround is the first time you load a world, AR creates a datapack for that world.  However that datapack doesn't do anything until you load the world the NEXT time.  So AR also has a fallback dimension property set it uses if it can't find the properties for the world you're currently on, it's supposed to be earthlike.

This makes me wonder if there's something related to the "fallback planet" properties.

It definitely sounds like AR applying the effects though.

Two followup questions though that'd be incredibly helpful.  Could either of you find a minimum set of mods that DOES trigger the issue.  Also would you be able to test with AR 1.16.5-1.7.1-4-universal and LibVulpes-1.16.5-1.0.1-8-universal.jar?  There's an issue that got fixed there that does affect overworld properties being overwritten in certain circumstances and I could see that having caused this bug.

**Comment by Nooska** [comment]
I've started testing.
One oddity to mention, that I'm now very aware of, but probably missed the first time around, is that it does not happen with the first world you create after starting the instance, only subsequent worlds.

I went back to the minimal pack, with just JEI, JourneyMap and FTB GUI Library to double check whether it was simply not encountering the bug because of restarts and not creating more than 1 world per restart.
I found it does indeed happen with that set of mods;
* Advanced Rocketry 1.7.1-4.universal
* LibVulpes 1.0.1-7 universal
* FTB GUI Library 1605.2.1.41
* JourneyMap 5.7.1
* JEI 7.6.1.75

So before updating LibVulpes I disabled the other mods to check if just AR+LV would cause it, and it did, so minimum modlist is:
* Advanced Rocketry 1.7.1-4 universal
* LibVulpes 1.0.1-7 universal
* Forge 36.1.3
![AR-list](https://user-images.githubusercontent.com/36108100/113391365-bb7dee00-9393-11eb-9a80-6bf54a57f2da.png)
But only happens on second world creation after starting minecraft (and onwards) (worlds set at cheats on, easy difficulty, no other changes from default)

Now for updating LibVulpes to 1.0.1-8 universal
The modlist is thus:
* Advanced Rocketry 1.7.1-4 universal
* LibVulpes 1.0.1-8 universal
* Forge 36.1.3
and it still happpens, though I have to note that Architectury 1.10.139 was added and enabled when updating LibVulpes, so rerunning the test, with that disabled, but still burning on the second world created (so architectury did not interfere)

I see there is an update to AR as well, so updating that as well to test
* Advanced Rocketry 1.7.1-5
* LibVulpes 1.0.1-8
* Forge 36.1.3
And I still burn in the second world

To note, it does take a second or two before entites are lit on fire, whether that is simply because of generation "lag" (the world needs to catch up) or because its something that runs shortly after creation, I can't tell.

To make 100% sure its not some residual corruption, I then created a completely new instance adding only AR 1.7.1-5 and LV 1.0.1-8 on a forge 36.1.3 world, adding the versions manually from the version list.
After doing a clean instance, the bug is still there.
As noted, all worlds have been with cheats on and difficulty easy, and no other changes from default (apart from GUI scale, being moved from auto by clicking twice on it, though I havbe a hard time seeing how that could interfere, I'll still mention it)

Hope this helps.

**Comment by zmaster587** [comment]
Ok, that's very strange, it definitely isn't happening o the first world that's created, but definately on the second.

**Comment by zmaster587** [comment]
So it appears that for some reason on subsequent world generation, the overworld is never added as a planet in the `planetDefs.xml`, good news is that that also means you can recover the save by adding the overworld as a planet in manually.

On the other hand, the fallback properties are not supposed to make you catch fire, so that'll need to be fixed.
