### ISSUE TITLE
Trying to make plates

### ISSUE THREAD

**Issue by Bravo420GoingDark** [zmaster587/AdvancedRocketry#2043]
## Version of Advanced Rocketry
1.16.5 1.7.1

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N

## Version of LibVulpes
1.16.5 1.0.1

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [ ] Y
- [x] N
>If Y, what is the MINIMUM set of mods required.

## Crash report and log, or VisualVM snapshot (if applicable)
>http://pastebin.com is a good place to put them
>crash reports that are put in the issue itself are impossible to read

> If it's an issue involving lag, please submit a VisualVM sampler snapshot.  Mods like lag goggles cannot provide all of the information needed to debug lag in any useful capacity.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

## Description of the problem
I've watched countless videos explaing how to make plates for each material and when I put for example a iron block under the small pressure plate block with a obsidian block under, it doesn't want to make the plates. It doesn't do anything. Now, I'm not sure since its 1.16.5 its something different but could anyone tell me if I'm doing something wrong?

**Comment by zmaster587** [comment]
Which build of advanced rocketry are you using?  There should be a -SOMENUMBER at the end.  This was a known issue that should have been fixed in build 6, if the number after the - is less than 6 (or you don't have a number there), updating will almost certainly fix your problem (if it does, please close this issue and you should be good to go). 

If it's 6 or large, please try testing with the latest build and let me know if it's still an issue.

1.16.5 is still pretty unstable and is being updated rapidly so things may change fast.

**Comment by VariantMouse** [comment]
I'm on build 10 and I'm still getting this bug.

**Comment by zmaster587** [comment]
alright, I'll give it another look over.

**Comment by zmaster587** [comment]
It seems to be working fine for me on build
AdvancedRocketry-1.16.5-2.0.0-10-universal.jar
LibVulpes-1.16.5-1.0.2-18-universal.jar


Also are you applying a redstone signal to the press _after_ putting the iron block under it? (I usually just stick a lever on top).
if you're already doing that, can you send a pic of your setup?

**Comment by voidsong-dragonfly** [comment]
This should be fixed in latest. If it reappears, reopen issue
