### ISSUE TITLE
Crash with Futurepack installed

### ISSUE THREAD

**Issue by jelaw21** [zmaster587/AdvancedRocketry#2053]
## Version of Advanced Rocketry
1.16.5-1.7.1-8

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.16.5-1.0.1-14

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] N
>If Y, what is the MINIMUM set of mods required.
Futurepack

## Crash report and log, or VisualVM snapshot (if applicable)
https://pastebin.com/3BYRUVt7

https://pastebin.com/32kJRqEE

## Description of the problem
After the build process of a rocket completes, the game crashes. I have reported this to Futurepack as well: https://github.com/mcenderdragon/Futurepack-API/issues/788

**Comment by mcenderdragon** [comment]
Is AR internal using fake chunks or worlds ? because `zmaster587.advancedRocketry.util.StorageChunk.<init>`
passes a `World ` object with null for its Dimensions `RegistryKey<World>` and this then causes the NUllPointer exception

**Comment by voidsong-dragonfly** [comment]
Yeah, our rockets/space station containers (only on launch) use a fake chunk to store/render/allow the player to interact with blocks.

**Comment by mcenderdragon** [comment]
Does it use a null RegistryKey<World> as Dimension key ?

**Comment by voidsong-dragonfly** [comment]
@zmaster587 You'd need to weigh in on that, I haven't touched it other than knowing some of the absolute basics.

**Comment by mcenderdragon** [comment]
I think I can work around this, but I did not realy expect it to be null. You should be able to create a unregistered instance pretty easily if you want.

**Comment by zmaster587** [comment]
There's no registration done at all for the world, it only exists really as a hack (originally built in 1.7) to be able to sync inventory contents so the player's world is swapped only for a few frames to get the tile reference ( and then swapped back. ).

I didn't think it would really cause any issue because unless you're doing stuff on the rocket itself anyway it shouldn't really be called at all.  Though apparently given the report here it looks like gatherCapabilities or something is called.

Truth be told, I've not figured out how to actually register worlds in code in 1.16 yet since that's all seemed to have changed from 1.12 and most of it still appears obfuscated/private.

**Comment by jelaw21** [comment]
AR Version: 1.16.5-2.0.0-12 

Conflict with FP still causes a crash when trying to build a rocket. 
[crash-2021-05-12_08.39.19-server.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6466201/crash-2021-05-12_08.39.19-server.txt)
