### ISSUE TITLE
[BUG]Server crash with mechanical pipes from mekanism

### ISSUE THREAD

**Issue by SirEndii** [zmaster587/AdvancedRocketry#2073]
## Version of Advanced Rocketry
- 2.0.0-10

## Have you verified this is an issue in the latest unstable build
- Yes

## Version of LibVulpes
- 1.0.2-18

## Version of Minecraft
- 1.16.5
- Forge: 36.1.13

## Does this occur without other mods installed
- Yes, only this mod, lib vulpes and mekanism.

## Crash report or log or visualVM (if applicable)
Stracktrace: https://gist.github.com/Seniorendi/7e9bbd11e75b4a558ffa3bde841c11ff
Issue report at mekanism: https://github.com/mekanism/Mekanism/issues/7141
Full log: Coming soon 

## Description of the problem
The Server crashes when we try to place a mechanical pipe from mekanism next to a fluid hatch.
1. Place fluid hatch
2. Place Mechanical Pipe
3. Crash

**Comment by pupnewfster** [comment]
Took a quick glance and not fully sure if this is the issue but a few issues with [this class](https://github.com/Advanced-Rocketry/AdvancedRocketry/blob/1.16.4/src/main/java/zmaster587/advancedRocketry/tile/TileFluidTank.java):
- Fluids are nonnull in 1.14+ similar to itemstacks, You should be checking if the fluid is empty or not and returning FluidStack.EMPTY instead of returning null in places
- This shouldn't be related but the NBT of fluid stacks seems to be entirely ignored.

**Comment by zmaster587** [comment]
Could you test with libvulpes build 22 and advanced rocketry build 11?  They should be pushed shortly.

**Comment by SirEndii** [comment]
Yes! I will try that in a few hours

**Comment by agentwolf88** [comment]
Where can i found AR Build 11?

**Comment by SirEndii** [comment]
Good question, can't find it on curseforge. https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/all
I will try to build the jar myself.

**Comment by zmaster587** [comment]
Sorry, I forgot to manually start a build last night, I'll start one now.
