### ISSUE TITLE
[BUG] Consistent server freeze

### ISSUE THREAD

**Issue by wisestump** [zmaster587/AdvancedRocketry#2083]
## Version of Advanced Rocketry

>1.16.5-2.0.0-10

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A

## Version of LibVulpes
>1.16.5-1.0.2-18

## Version of Minecraft
>1.16.5

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A

## Crash report or log or visualVM (if applicable)
>https://spark.lucko.me/NpdDkl4eB9

## Description of the problem
>Server consistently freezes for a short period of time. In my case (on default config) I have 94 files ~4kb each, which results in "Can't keep up! Is the server overloaded? Running 5456ms or 109 ticks behind" every 5 mins. See profiling info above

**Comment by zmaster587** [comment]
Looks like it's related to waiting for disk write.  This is a really tricky one I think because in order to determine if the files are stale I'd still need to read from the disk, which would also cause lag.  These json files are generated from the planetDef.xml, and I can't think of any way to reliably determine if that file has been editted.

I suppose what I could do is only write the JSONs the first time the world is saved, so instead of lagging every time the world is saved, it only lags the first time.

Ideally I'd like to do away with the datapack thing entirely but have not found a way to load dimensions in minecraft directly yet since they changed everything.

**Comment by wisestump** [comment]
Is there a way to read/write dim files using another thread? I don't know whether it's a good idea in minecraft ecosystem or not, just curious.

**Comment by zmaster587** [comment]
yeah, it's possible and honestly not something I'd really thought about because all the other save things called in the same method can be edited in game, but the .json datapack config doesn't really change outside of some command being executed.

Worst case I suppose is that the time it takes to save is longer than the interval between saves and it ends up hanging waiting for the previous save to finish.

**Comment by zmaster587** [comment]
Going to close this issue because the server freeze itself itself should be fixed, removing the JSONs entirely is a separate thing.
