### ISSUE TITLE
[BUG] Game sometimes crashes when interacting with the rocket entity

### ISSUE THREAD

**Issue by paypur** [zmaster587/AdvancedRocketry#2244]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-2.0.0-256-universal

## Have you verified this is an issue in the latest unstable build
- [] Y
- [x] N
- [] N/A

## Version of LibVulpes
>[LibVulpes-1.12.2-0.4.2-84-universal

## Version of Minecraft
>[1.12.2

## Does this occur without other mods installed
- [] Y
- [x] N
- [] N/A
>If Y, what is the MINIMUM set of mods required.

occurs even without optifine

## Crash report or log or visualVM (if applicable)

https://paste.ee/p/sSM0g

## Description of the problem

interacting with the rocket entity such as selecting a destination or adding fuel by hand crashes the game

**Comment by voidsong-dragonfly** [comment]
This isn't on us that I can see, this is an OOM. See:
`Caused by: java.lang.OutOfMemoryError: unable to create new native thread`
I'm not perfectly versed in OOMs like this, you either need more allocated RAM or you need more available CPU threads. Either way, it is not happening because of us, we simply happen to trigger it as it lies in wait; something else could easily trigger it.

**Comment by paypur** [comment]
I have plenty of resources available. 6c/12t , 8GB of allocated ram. I just tested this with out any other mods and it worked so now im trying to figure out which mod is causing problems.

**Comment by paypur** [comment]
It seems to be an issue with TOP. Just staring at the rocket entity crashes the game after a moment. I don't know why it crashes with an oom error when f3 says there's plenty of available ram.
