### ISSUE TITLE
I have a simple questions:

### ISSUE THREAD

**Issue by ShadowPlayerTTV** [zmaster587/AdvancedRocketry#2377]
Hello, I have some questions about a mod that I'm using. Can you help me with the following:

1. How can I make "**THE END**" appear as a moon of Jupiter?
2. Is it possible to make a rocket land on "**THE END**" at a specific location, like the **Obsidian Platform** or a custom location?
3. If "**THE END**" is considered a planet and I have a mod that automatically spawns the **Ender Dragon** upon entering "**THE END**", will this mod work or not? 

Thank you in advance for your assistance.

**Comment by Turrari** [comment]
1. In your config\advRocketry\planetDefs.xml file, add an entry for it as a moon of Jupiter with the DIMID="1" and dimMapping="" like this:
`        <planet DIMID="7" customIcon="GasGiantRed" name="Jupiter">`
`            <GasGiant>true</GasGiant>`
`            <orbitalDistance>330</orbitalDistance>`
`            <rotationalPeriod>24000</rotationalPeriod>`
`            <planet DIMID="1" dimMapping="" name="The End">`
`                <orbitalDistance>50</orbitalDistance>`
`                <rotationalPeriod>50000</rotationalPeriod>`
`            </planet>`
`        </planet>`
2. I believe the rocket will always land at the same coordinates in the destination dimension as it left from the departure one. In this case if you warp to Jupiter using a warp ship created using "Station 1" those coordinates will be x -1536 z -1536, which may or may not be on an end island. If you use "Station 2" then they will be x 512 z -1536, "Station 3" x 2560 z -1536, and "Station 4" x -1536 z 2560. It will be bad if you end up in the void. So if you want the rocket to come down at a specific set of coordinates, I think you would need to launch it from another moon of Jupiter at those same coordinates. Say create a moon called Ganymede and put the launchpad within 50-60 blocks of 0,0 so you land on the main island. I don't think you cannot land on the obsidian platform because its positions varies depending on the seed and it is only created when something goes through the end portal.
3. The Ender Dragon spawns fine already as it is the vanilla dimension so you do not need a mod. The only difference is Jupiter and the sun will be in the sky.
