### ISSUE TITLE
Problem installing AR onto existing modpack and world [1.7.10]

### ISSUE THREAD

**Issue by theTyrfing** [zmaster587/AdvancedRocketry#305]
When I installed Advanced Rocketry onto an existing modpack (Modifed Skyfactory 2.5), it overwrite one of the dimensions that I was in and result me being trapped under meters of moon rock and soils. This is partly a user error (I DERPED) as I forgot to change the config setting for the DIM min.

I apologized that I cannot provide any screenshots as I quickly deleted the world and restore the backup. However, you too can replicate this with:

1. Have existing world with one of the dimensions with the range of a overwrite.
2. Install AR without changing any setting.
3. Load world and enter dimensions somehow.
4. Profit! 

All in all, it is overwriting existing dimensions and I recommend patch it to mitigate more incidences as people typically would install mods without thinking too much about it...  

P.S. Sorry the long issue post, but do you have specific guidelines to posting issues on your project?

P.S.S If you need anymore information like logs, mods installed, and etc, simply reply to this thread.

**Comment by zmaster587** [comment]
I list of dimension mods you're playing with would be helpful.

Right now the only way I can see this working is checking against all possible dimension adding mods and figuring out what dimensions they are using from their configs/data storage or whatever, is not an easy task.

I'm putting this at low priority because the designed solution still works but I'm not discounting it because it is a common mistake and does require user effort.  Will see if something can be cooked up.

**Comment by theTyrfing** [comment]
> zmaster587 commented 13 hours ago • edited
I list of dimension mods you're playing with would be helpful.

Sure. ;)

**List of Mods that have Dimensions:**
ExU - Last Millennium
Twilight Forest
RFtools - For "Time to move" reasons
Witchery
Thuamcraft 
Dimensional Pockets
TARDIS Mod => Yes, I already have a spacefaring vessel. ;) 

> zmaster587 commented 13 hours ago • edited
Right now the only way I can see this working is checking against all possible dimension adding mods and figuring out what dimensions they are using from their configs/data storage or whatever, is not an easy task.
> I'm putting this at low priority because the designed solution still works but I'm not discounting it because it is a common mistake and does require user effort. Will see if something can be cooked up.

For better or worse, this is an end case that may pop up from time to time.  I brought it up as it might mess with some server admins or packmakers. Then again, I don't how hard is it to break this mod.

Also, this happened when I was in the TARDIS (DIM2) and had dig out my control room to revert the everything back to their original state. The TARDIS did not like that either.

**Comment by zmaster587** [comment]
None of the asteroids have bedrock by default, anyway.  Sorry I've taken so long to respond, but I think the new XML system might be a goold solution to this, in newer builds an xml file gets generated with the galaxy's properties in the world/advRocketry/planetDefs.xml file.  Because it also contains the dimids, it would be trivial just to modify the dimids in there to make things compatible.
