### ISSUE TITLE
POWER IS WONKY

### ISSUE THREAD

**Issue by jelaw21** [zmaster587/AdvancedRocketry#329]
So, the only way I have been able to produce power for the machines in this mod is by placing a Powercell from Actually Additions next to the power plug. But this is quite resource heavy. None of the RF cables I have tried actually link to the plug AND even the energy cable in the game does not transfer rf OUT of the Powercell, or Solar Panels. I can't get power to the machines. Please help.

**Comment by zmaster587** [comment]
What version of Minecraft are you running?  what cables have you tried?

Cables from Immersive Engineering 0.10 - 54 or above and EnderIO cables have been tested and appear to work fine.  For 1.10 I cannot garuntee cables from all mods will work because in 1.10 I use forge's energy capability.  Mods using the old API (RF only for example) may not work as they may not implement the new forge standard of energy.

I know for a fact at least as of Dec 25,  neither Quantum Flux nor Mekanism supported the energy API

AR also has its own (kinda crappy tbh, is there in case no other energy mod is installed) generators as well as it's own power cables.

**Comment by jelaw21** [comment]
I am running 1.10.2. Tried using cables from RFTools. Also tried to connect
Solar Flux Reborn solar panels with your energy pipes. Neither worked.

**Comment by jelaw21** [comment]
Oh and the biggest issue is that in order to make energy cables in AR, you
need to make a lathe,  which requires energy.

**Comment by TheGuyRunningSouth** [comment]
@zmaster587 do your RF plugs only support the new forge energy API or do
they still support the RF API? If they do support it still, a Mekanism
cable set to 'pull' on the generator connection and 'push' on the RF plug
should solve the transfer problem (barring an underlying error we haven't
noticed).

**Comment by zmaster587** [comment]
the 1.10 builds no longer support the RF API due to the fact that in order to support the RF API a tile entity must implement interfaces directly which leads to either hard dependancies, or a million copies of the RF API being loaded.

That being said, energy cables should not require a lathe to make.  I have apparently neglected adding crafting recipes for the metal rods.

I'll also take a look into RFTools and Solar Flux Reborn and if need be will try to submit a pull request to get Forge's Capability system supported.

I also know the Immersive Engineering's post-Christmas builds can transfer power as well as EnderIO.

**Comment by zmaster587** [comment]
Found an issue where the Generators from AR do not push energy as expected making the solar generator and coal generator not work with other mods' cables.

**Comment by jelaw21** [comment]
On a separte issue, did you re-institute researching?  I build a rocket,
put an unprogrammed planet chip into the guidance computer, selected the
moon, have fuel and it keep saying "Destination Unreachable"...

**Comment by zmaster587** [comment]
I have not re instituted reseaching.  But that was a known issue with AR 1.0.0RC1 to 1.0.3.  What version of AR and MC are you running?

**Comment by jelaw21** [comment]
1.0.4b and running MC 1.10.2.  I got to the Moon now, but I can select no
other planets. It seems like there is a rocket button just behind the "up"
button and it will not allow me to choose "up" to select other planets.

**Comment by zmaster587** [comment]
Rockets can only go to planet/moon systems.  You need warp to go to other planets in the same solar system.  I plan on implementing an impulse drive or something for rockets later to go to planets in the same solar system though.  I'm also not quite sure what you mean by there's a rocket button just behind the up button?
