### ISSUE TITLE
[Request] Coordinates in ID Chips

### ISSUE THREAD

**Issue by scottosx** [zmaster587/AdvancedRocketry#334]
This is based on an experience I cannot yet understand.

I went from my Space Station 1 to the Moon using the onboard planet selector. On the Moon, I noticed that it used just about half of the fuel to get there. I decided to test what would happen if I didn't refuel. I ran out of fuel on ascension and came back down to the Moon.

I then refueled and went back to the Space Station. After a while, I wanted to go back to Earth. I put back in the Space Station 1 chip which I assumed had the launch pad coordinates on Earth for the return trip. That always worked before.

What actually happened was that my rocket landed in the Overworld at the exact X and Z coordinates of Space Station 1. Luckily I could teleport back to base.
So, I thought after a journey then maybe I needed the Earth chip. I flew back to the Space Station on that rocket then changed the chip and flew back to Earth. It landed me in the same wrong place as before. I disassembled that rocket and made a new one at my base. Went to the Space Station and subsequently returned fine to base as expected.

I assume that point of launch and point of arrival are paired? 

As requested a tooltip with the dimension and coordinates for origin/return would be helpful.

**Comment by zmaster587** [comment]
the space station chip should take you to where you last took off from in that particular dimension.  Although you should not have arrived at the wrong place back on Earth.  I wonder if the Lunar coordinates overrwrote it or something.

**Comment by zmaster587** [comment]
Apparently I had completly forgot to add the ability to keep track of takeoff locations from multiple planets.
If you go to the moon it should take you to the space station coordinates, however if you try to land earth from a space station afterward it should take you back to where you took off from.

The landing coordinates are now displayed on a space station chip if you're on a space station.

Planet ID chips always go to the same location on the destionation as the location you took off from so i cannot see a reason to add coordinates to those.

**Comment by scottosx** [comment]
You were able to reproduce it somewhat then? Quite a strange experience. Had I not noted the Space Station coordinates I would have no idea where I was. A tooltip will be helpful to make an informed decision.

On a side note, I had a strange experience yesterday too. Not maybe worthy of a full bug report as another mod was the cause. So, I was leaving my space station and once I hit Earth's atmosphere the descent kept freezing periodically. Took like 2 minutes to land.  

On relaunch once I hit the orbit MC crashed. The crash log indicated that Fancy Fluid Storage was ticking and having a problem with the dimension. I have nearly 1,00,000 mB each of Hydrogen, Oxygen and Rocket Fuel stored at the station. So, of course I didn't want to uninstall that mod. I contacted the author and he fixed it right away and sent an update.

The interesting point from your end was that when I reloaded the world which had crashed in orbit my rocket had completely disappeared out from under me! I was floating in the middle of space high above my station. I was in creative so no biggie but truly the rocket was gone,  gone, gone. 

I rolled back to a previous save just to be sure that nothing was corrupted.

**Comment by zmaster587** [comment]
Yeah, I had actually had to deal with this a lot when testing planets and station -> planet ascent and descent.  I could have sworn I had fixed it before releasing space stations but I suppose I forgot.

I'm wondering if the freezing was being caused by loading chunks?  If it keeps happening try running Opis on it to see if you can figure out what's doing it.

I'll have to keep that in mind, I used Fancy Fluid Storage on one of my games, will have to make sure to update it.

Minecraft sometimes does weird things when it crashes, I've noticed sometimes blocks and entities get rolled back a few seconds to a few minutes but players do not (I admittedly abuse this effect a bit when debugging XD).  It's possible the rocket is trying to ascend in the other dimension again, but just set back 15-30 seconds.

**Comment by hagfelsh** [comment]
@zmaster587 , this seems remarkably relevant to something I discovered today.  I built a rocket on my space station on a pad in a spot I like better than where the original space station platform spawned when I sent it up in an unmanned rocket.

I added a planet id chip and pointed it at earth/overworld and launched.  It landed predictably on a landing pad a few blocks over from where my original rocket was launched.  

When I launched a return to the space station, I expected to land on my new pad at the station... but instead I landed back at the original spot at the station.  

I suspect that the space station chip was programmed with coords for that original landing spot.  I'd like to have rockets take off and land at my new pad on the station instead of stacking on top of each other (!) on the original landing spot.

I'm still running version 1.0.8.  Could this be something that's addressed in one of your commits above?  Or just a later revision altogether?

**Comment by zmaster587** [comment]
I don't believe that issue had been addressed but I had thought that was working for a while now.  I'll look into it and see if I can figure out what's going on, though I'm just going to copy this to a new report so it doesn't get lost as #447
