### ISSUE TITLE
Issue for 1.10 regarding DimensionType

### ISSUE THREAD

**Issue by ArtixAllMighty** [zmaster587/AdvancedRocketry#350]
after downloading a copy of the mod, and looking trough the code, I cannot find where the dimension is registered to the DimensionType enumclass.

am i looking in the wrong places ?
One of my mods uses the DimensionType as a way to retrieve dimension names.
I'd love to resolve this issue !

**Comment by zmaster587** [comment]
I belive they are registered here: https://github.com/zmaster587/AdvancedRocketry/blob/MC1_10/src/main/java/zmaster587/advancedRocketry/dimension/DimensionManager.java#L49
I'm not sure how much it'll help as all the planets share the same type and therefore the same name.

Reason for this is because planets are dynamically created and destroyed and because DimensionType is an enum and every time the player closed and opened a world I'd have to create a whole new set of planets.  This would result in a memory leak, which I'd really like to avoid.  If needed I can try to put together some way to retrieve names in a better fashion other than the DimensionProperties class

**Comment by ArtixAllMighty** [comment]
no, that's okay. i'm just listing all the places people have placed down telepads, which is independant from any dimension, apart from the retrieval of the dimension's name, for showing telepads per dimension. 

thanks for that information ! now I know that the problem is more likely to be on my side.
