### ISSUE TITLE
Launching a gas miner crashes the server

### ISSUE THREAD

**Issue by mrgreaper** [zmaster587/AdvancedRocketry#360]
Launched a Gas rocket and the server went bye bye (a tech term)
http://pastebin.com/VhQKCyyc

possible cause: it was linked to a unloader but the unloader was removed to put it elsewhere, this could explain why it tried to set a redstone signal but found an "air" block but that is just a guess

Server loaded up and the miner is mining (36 minutes aparently) no idea if it will crash on return

EDIT: it came back full of resources

**Comment by zmaster587** [comment]
You're guess looks about right, it should have been removed as a valid infrastructure upon being broken so something is going wrong futher up the tree that leads to this.  Investigating...

**Comment by zmaster587** [comment]
I've been able to replicate this once, but have not had luck doing it demand as of yet

**Comment by mrgreaper** [comment]
It is in the same chunk as the disappearing chicken crew, so may be chunk related, though ender io is functioning well In that chunk.... Something wierd is certainly happening, given it crashes the server I have refrained from launching any further gas missions

**Comment by zmaster587** [comment]
The vanishing chickens thing looks more like a client side issue, and given they can still lay egg etc, they are definatly being processed on the server.  The rocket fluid unloader stores only a set of coordinates and as such should not be effected by chunk loading/unloading.  
On a test world (which I've not touched since Christmas and has seen AR 0.9.0 -> current without reset) I have found the fluid unloader had 'forgotten' the coordinates of the assembler,   Although upon further testing I found I is legit just not connected and doesn't crash like the issue you reported.

Maybe see if it happens again upon subsequent missions?

**Comment by mrgreaper** [comment]
Will test it after work,

Please note that later on the chickens in that chunk disappeared fully, not just stopped rendering but their boxes were empty, the one in the same room but just in the next chunk who did not have the rendering bug also did not disappear when this happened... It's a hard bug to describe and without knowing the cause an even harder one to fix of that I'm sure

**Comment by zmaster587** [comment]
Alright.
I'll reply on the #363 about the chickens to keep things organized.

**Comment by mrgreaper** [comment]
launched a second ship and the server remained uncrashed (however i had to relink the rocket monitoring station with the assembler as it had lost its link...may of lost the link with the broken block too)

**Comment by zmaster587** [comment]
Not how how the block changed between being referenced and having meta changed but that's the only way this can happen.  I expect it's exceedingly rare but I added a sanity check anyway
