### ISSUE TITLE
[Suggestion] Higher Pressure worlds should require a suit as well to breath

### ISSUE THREAD

**Issue by mallrat208** [zmaster587/AdvancedRocketry#371]
It'd be nice to have a few more instances where O2 is actively needed besides low pressure worlds and space, say anything over 125 would require a suit.  

Barring this it would also be useful to specifically tag whether or not a planet has a 'breathable' atmosphere in the planetDefs xml file

**Comment by zmaster587** [comment]
I was actually thinking of doing something like that orginally, but rather than a space suit, require a pressure suit.  Although now I think it may be doable with a high pressure module, though it wouldn't consume oxygen.

For exact implementation I was thinking either assigning another atmosphere type to the planet or start taking pressure into account directly.

**Comment by Xakorik** [comment]
I'd say if pressure is above certain amounts require high pressure suit or module to survive.
