### ISSUE TITLE
request/suggestion to fix/avoid Space Dim conflicts

### ISSUE THREAD

**Issue by Soyaro666** [zmaster587/AdvancedRocketry#373]
Hey there, I'm currently working on [my pack](https://minecraft.curseforge.com/projects/dimensional-nightmare)s next version. While warpdrive is in it I just added advanced Rocketry to my dev build and had a dim id conflict - nothing I couldn't handle but I had an idea in that moment.
Both mods are adding space. There are others doing the same. Why does every mod need an own space if they could be configurable to use an existing dim ID as Space?

I'm requesting one feature. I guess "RegisterARSpace=true/false" would work, while default is true. If false you could simply skip dim registration and on jump into space you could check if the dim that's set as space_dimension_id does exist. If it does, jump there, no matter where that dim comes from, if it doesn't the jump simply fails.

If you don't change anything in config Advanced Rocketry would act exactly like we're used to. but for mod pack authors it would add a lot of possibilities.

Note: I requested the exact same feature over there with almost identical text. Mentioning it to avoid confusion.
One thing that just came into my mind is TiC slime island which can spawn in any dimension. I guess a similar mechanic could be used to add important features to a space dim from another mod.

**Comment by zmaster587** [comment]
The biggest problem with something like is that each mod still needs to keep track of where its different sements are in that one dimension.  This would require each mod adding support for every other mod's location handlers.  If this was not done there's a high probablity of mod A and mod B trying to use the same location in space for different things.

If a mod is doing something more advanced than just handling space, for example changing the skybox as to render planets and moons, if another mod needs to modify the skybox as well then one of the mods will take precidence breaking functionality of the other unless compatability were added for every other mod sharing that same feature.

There might be an easier way to do it, but those are the problems I see at least with the way AR is designed, and mods like compact machines likely have a similar design (I've not explicilty looked at how that mod works but given what I've seen ingame it seems plausible that it follows a similar design).

It's a nice idea, but adding extra dimensions is not in reality all that much overhead (especially since unused dimensions are generally unloaded) and trying to share dimensions would just be a huge headache for everyone involved.

**Comment by Soyaro666** [comment]
You're thinking one or two steps further than me, I guess. I didn't think about changing another mods dim to look like yours. My idea was to add structures (asteroids, for example) to another dimension. Let's talk about Warp Drive for example. That mod generates abandoned shuttles in space. They don't neccessarily need to spawn in warp drives space, that dim could be disabled and their shuttles can be generated anywhere else. I'm not sure if your mod adds similar unique structures, if it does they could be generated in warp drives space, too. Your skybox, on the other hand, is a feature of your space. Disabling your space would disable that feature too, of course. That way the idea is way easier to implement.
