### ISSUE TITLE
[Mod Compatability] WTFExpedition (and similar)

### ISSUE THREAD

**Issue by Dragnier** [zmaster587/AdvancedRocketry#380]
I'm using WTFExpedition to control 99% of the oregen, not to mention other generation options, in a pack I'm building. However, when I generate planets from your mod, they don't get any of the world or oregen from WTFExpedition despite the fact that I have the WTFExpedition config files for oregen set up to work for the planets in question. Basically, I specified the planet DIMID's and made sure they were included in the other mod configs. Is there any way you could look into fixing this problem?

Or perhaps even add their oregen config options? I very much like the choice between vein, cluster, cloud, single, and the sub-specification where they only spawn in caves or underwater in conjunction with the spawn type. I can make some things huge veins rarely, others small clusters, and still others cloud dotting the chunk.

You might even go a step further and allow specifying the same ore multiple times provided it is only allowed to generate in specific biomes. Such as having Gold generate one way in Extreme Hills and another in Mesas. Another neat addition would be the ability to specify only generate under lava.

**Comment by zmaster587** [comment]
It may be that AR's oregen customization is overriding WTFExpedition's oregen on AR planets for some reason.  I'll take a look at it.

**Comment by zmaster587** [comment]
Upon looking into WTFExpedition a bit, I'm not 100% sure you can generate ores in any other dimension other than the overworld or the nether.  When registering an ore generator it looks like it is placed into a list in the WTFWorldGen class.  Though the only place I can see that list being accessed is in the CoreWorldGenListener class in the doChunk method.  But in the doChunk method there's a switch that checks to see if the current world is -1 or 0, otherwise scanner remains null and the generator instances are never called.

Perhaps I'm missing something but it's looking like something on WTFExpedition's side at this point.

**Comment by Dragnier** [comment]
Ok, I'll reference this to them then. Their config does have a spot for specifying dimension, so if that isn't working then they need to know.

**Comment by zmaster587** [comment]
It looks like it'll work fine for over world or nether at least

**Comment by WhiskyTangoFawks** [comment]
Huh.... completely forget I had that switch in there.  Easy enough to fix, I'll have a new version of WTFExpedition out this weekend that should work with other dimensions.

Thanks for finding that.

**Comment by zmaster587** [comment]
Easy enough to forget something small like that you added who-knows-how-long ago
