### ISSUE TITLE
enhencement ore ponderation

### ISSUE THREAD

**Issue by choum33** [zmaster587/AdvancedRocketry#381]
Hello,

If possible i'd like to be able to setup (or hardcoded) ore ponderation in asteroids.
For exemple during my last mission i got 8 stacks or iron and 8 stacks of iridium and this really unbalance the game. 1 or 2 iridium ore would be great ;) Of course i had maximum values in my asteroïd chipset, but it's still really too much. I know i can select the ores that can generate in the asteroids but i'd really need to be able to balance the quantity too ;)
I setup mining mission duration to some days already.

Maybe a way to make research points more difficult or slow to generate too would be great?
Need power to drill the asteroïds to make missions more expensive?
Another idea would be to research an asteroid that contain some elements like Fe or Cu to get iron or copper. And make iridium (or other ore as plutonium) asteroid rare, so harder to find in the galaxy or with really great distance that need a giant rocket to reach and come back?
Or maybe apply a % success to research of one element, 0,01% for iridium, 30% for iron, etc. So this could lead to use 30 000 data points to get the wanted asteroid.

(with only 1 mining asteroid mission (4 chests) we have enough ore to do everything in the game without need to explore or mine anymore and it's little sad).

My best regards

**Comment by zmaster587** [comment]
You do have a point.  When designing the system I had not thought of rare ores so I had built the system to return stacks at a time, but with rarer ores like iridium it really can mess up balance.  I do plan on implemeneting #349 and #300 in the next content update which should resolve this issue.  With those changes iridium in very small amounts could be put into asteroids that are very distant and therefore require high end equipment to find.

Definitly need to change granularity to allow stacks of less than 64 to be brought back as well.

I'm not really a fan of the idea of requiring power on drills because power gen on a rocket is kind weird to do right now, so for the time being I'd like to avoid that.

**Comment by choum33** [comment]
thanks zmaster587, you're the best ;)

**Comment by zmaster587** [comment]
More fine grain control is implemented in the 1.1.x builds.  Probably not going to do a research tree or anything right now but perhaps it would be a good long term goal.
