### ISSUE TITLE
[question] max station size

### ISSUE THREAD

**Issue by choum33** [zmaster587/AdvancedRocketry#384]
Hello,

I just wanted to know what is the max size for a station? and what is the max size for a station section?
Can i transform 1 full chunk (my factory with all storage and machines) to a spacestation by builing the pad below it and scan it?
Once my station built, can i modify it ? remove walls for exemple or all is locked to avoid void space ejection?

**Comment by zmaster587** [comment]
If I remember correctly the max station size is 1024x1024, however each module for the station including the initial launch must be less than 16x64x16 (same bounds as the [rocket assembling machine](http://65.78.115.159:8000/AdvancedRocketry/blocks/RocketAssemblingMachine.php).

And yes you should be able to take your factory with all the storage machines and make a module from them as long as it fits inside the above limit.  I've never actually tested on anything other than a furnace and chest but it should work.  Pipes and multiblocks may need to be replaced if they stop working, but as long as the machines do not need to track their location they should be fine.

Once you've built and launched a station you can travel to it and build/destroy it however you want.  You'll be able to modify it just as if you were on the moon, but without the ground other than the 1024x1024 limit per space station.  The main reason for having that limit is it allows me to put multiple stations in one dimension so that I don't need to register half a billion dimensions if people build a ton of space stations.

Explosive decompression is not a thing yet, but I would like to incorporate it eventually
