### ISSUE TITLE
[Question] O2 in big sphere

### ISSUE THREAD

**Issue by Valdiralita** [zmaster587/AdvancedRocketry#392]
I have build a dome with 300,000m³ in orbit, how can I fill it with oxygen?
The oxygen vent doesnt seem to be able to, even when setting atmosphereCalculationMethod to 3 "the Oxygen Vent can fill up to 32,768 cubic blocks".

Is this an oversight?
What about a setting in the config for the radius of the Oxygen Vent?

**Comment by zmaster587** [comment]
given https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/util/AtmosphereBlob.java#L91 and https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/tile/oxygen/TileOxygenVent.java#L323 I actually recalculated the max volume, turns out the number I provided is wrong it's actually 137,188 cubic meters.

See if the terminal is throwing errors with setting 3 and try it with setting 2 and see if it works with that.  If it still is not working try double checking for holes.

If I get some time I'll try it myself and report back.

**Comment by Valdiralita** [comment]
I poured water over my dome and it is indeed airtight.
Well, 300000 is still greater than 137188 blocks. So I doubt that method 3 will work.
... I just tried 3 and it gave me no errors and it doesnt work, just as i expected.

My dome is 101 blocks in diameter and 51 blocks high, like this:
http://oranj.io/sphere.html?width=101&height=51&depth=101&method=dome_hollow

**Comment by zmaster587** [comment]
alright.  Somehow I had it in my head that 300,000 was less than 137,188.  Is what i get for trying to multitask I suppose.  With the current implementation you'd have to section off the dome for the vent to work.

I could implement a conifg, though I'm kinda hesisitant because large volumes could lead to large calculation times in some cases.  But I suppose I can support an aribtrary size anyway and put a warning in the config.

**Comment by Divineaspect** [comment]
Howabout a field or shield generator  which breaks the space up with air
tight intangible blocks?

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by Valdiralita** [comment]
nice, ill give you feedback to the change ASAP.

also maybe another suggestion, nothing critical, just a nice-to-have:
Mods tend to tell you where your multiblock structures are wrong. Your machines already do this.
It would be nice that the oxygen vent tells you where a leak is when you place it.
Maybe a chat message "leak at X,Y,Z".

**Comment by zmaster587** [comment]
I have thought about doing that, but atm calculations are already expensive for large areas, and because the vent cannot know if it's failed until it calculates the entire volume and finds it still needs to fill more space, it takes a long time in the worst case (which will always be the case in the case of a failure).  I cannot currently think of a way of adding code to check for that without massivly increasing the amount of computation required for air.

**Comment by Divineaspect** [comment]
make a smaller volume air bubble generator which generates an air tight
edge at it's maximum range, I'm using the rftools shield block for this.
You could then use the oxygen vent to fill up the central remaining spaces.

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by Valdiralita** [comment]
I cant setup gradle to build this, sorry, cant test your change.

**Comment by zmaster587** [comment]
I'll try to fix the gradle script.  Gradle is not my forte

**Comment by dmodoomsirius** [comment]
Z pm the dependencies you work off off. I'll get to it sometime this week once i know what dependencies you use.

**Comment by dmodoomsirius** [comment]
Put IC2 in a folder called libs and it will add that to the classpath. This is ForgeGradle adding libs to the Classpath not Gradle itself.
