### ISSUE TITLE
[Request/Suggestion] Asteroid changes/Unlockable planets, more open-ended machines

### ISSUE THREAD

**Issue by Shane371** [zmaster587/AdvancedRocketry#397]
Just a couple thoughts. Looks like you plan on changing the way asteroid missions work. Requesting a few config options to add types of asteroids. Distance modifier, density so they wont last forever, Chance to find the type and multiple ores per type with spawn chance.  Ruff Example - Asteroid type X is common takes Y amount of time to reach, has 10k to 5k ore and contains 60% iron 30% copper 9% coal 1% diamonds. Would like to use asteroid missions in a modpack to limit the ways/amount of resources available to a player. Asteroid chip types as loot could be fun.

  Planets: any chance of a tier or unlock method for new planets? Just a slot in the planet selector or warp controller to allow access to a planet. Example place item x in slot click button(consumed, returned to player, required for travel ect..) now a new planet is available or something complex involving the astrobody data processor. Again for modpacks It would be cool to travel to say abysalcraft dimensions but if all the player needs is a warp drive it breaks abysalcraft progression. Could fit in if you plan on fuel/engine types.

  And the long shot, Abit more flexibility with multiblock  machines for custom recipes. liquid/item import/export on more machines. not sure if thats a realistic option as it would be a gui nightmare. Example needing a coolant to cut tuff metals in the lathe.

**Comment by zmaster587** [comment]
Lot of this stuff is coming as I type so it may seem like a bit of a dump..

The suggesting with the asteroids looks very similar to #300, though my plan to prevent a single asteroid from lasting forever was making it a one-shot thing, so once a mission goes there and returns that particular asteroid is gone for good and what you got from it is what you get.  What I'd like to do to prevent people just spamming asteroid missions though is to generate a list that changes every X number of minutes (configurable) sometimes nothing may be there, other times you'd get a selection from a preconfigured list of types with a random (also pre-configured) variation where what types of asteroids displayed are  function of the probability of that type of asteroid and the tier (more than one telescope/ levels of telescope?) of your equipment.

I really would like to bring back unlockable planets (I gave it a shot a while back but it was just tedious to play with...) because you have to use a station to get from one planet to another this does allow for more options on how to determine what planets are accessible.  I'd really like to avoid doing some make-a-chip for every planet deal.  Though now I can probably link what planets are allowed to the warpship itself so players can do the research or whatever on the warpship to gain access to those other planets.  I would like to add impulse and other types of engines to the ship and this would be a great excuse to fit that in.  It would also be cool if some item required for travel to a planet be specified in the XML config too and the warpship has some kind of "insert key here" thing.

It wouldn't actually be too bad to add stuff to machines like that as the UIs I make are modular (adding data IO bar/slots is a one line call for instance) so there's no reason that couldn't be done.  I'll just have to see how i can modify the machines to allowed this.  That actually was my original plan but I kinda got a bit off that (is a bit more evident in earlier machines like the observetory, precision assembler, arc furnace) but I kinda moved away from that design philosophy... I'll definitely bring it back though!
