### ISSUE TITLE
Problem Changing recipe with XML

### ISSUE THREAD

**Issue by tjsd** [zmaster587/AdvancedRocketry#408]
Minecraft 1.10.2
Forge: 2221
AdvancedRocketry-1.10.2-1.0.10
LibVulpes-1.10.2-0.1.15-universal

Issue: I am trying to change the time it takes to process steel and silicon in the Electric Arc Furnace. But no matter what I type in the XML will not change the time. I have tried several different versions and now have silly times just to see if it does anything.

	<Recipe timeRequired="150" power="9000">
		<input>
			<oreDict>ingotIron</oreDict>
			<oreDict>charcoal</oreDict>
        </input>
		<output>
			<oreDict>ingotSteel</oreDict>
		</output>
	</Recipe>

**Comment by zmaster587** [comment]
That particular config should have generated a few warnings.  There is no oredictionary entry for charcoal so you'd need to use "<itemStack>minecraft:coal 1 1</itemStack>" instead of "<oreDict>charcoal</oreDict>".  I did fail to properly implement support for oredictionary outputs so I'll make sure to do that for the next update.  In the meantime you may need to use the entry "<itemStack>libvulpes:productingot 1 6</itemStack>" as your output.  You may also need to set "useDefaults" to false because the current system does not allow overriding and will result in creating two recipes with different power and time values otherwise.
