### ISSUE TITLE
[Idea / Request] Transporters for Space Ships

### ISSUE THREAD

**Issue by Julienc249** [zmaster587/AdvancedRocketry#410]
I was thinking that it is a bit impractical to have to take a rocket every time you want to explore a planet from your ship, could it be possible to add in Star Trek-like transporters to "Beam" down to the surface of planets? Also, would it be in any remote way possible to make spaceships compatible with mods such as Dacincis Vessels? Finally, as a side idea, maybe lasers, to fight with friends in space!? Anyways, Great mod, Keep it up!!! 

- Julien249

**Comment by zmaster587** [comment]
I feel like teleporters would be a bit too hand wavey because people will wonder why they cannot just teleport anywhere then.
I also don't quite like the idea of removing rockets from the station <=> planet transport, though what if you could build infrastructure on a planet such as a space elevator to transport back and forth between the ground and station?  

Then there's a reason why you can't just use it to go anywhere and would require moderate resource investment, however it won't take as much time as a rocket or require fuel.

Dacincis Vessels is more of a framework to make moving ship from what I understand so I'm not really sure how I could go about adding compatibility for it because it looks like it works in a similar manner to AR's rockets already but just lets the player move them around in more directions than up/down.

I do not currently plan on implementing any combat system for AR.  I've been talking with DarkCow, the developer of ICBM and we'd both like to add compat for AR's stations and ICBM's missile systems.  Though at least for now AR is mostly about peaceful(ish) space exploration and combat is beyond the scope of the mod.  Due to the limited amount of time I have to develop AR plus other projects I don't really have time to expand the scope of AR at this time.  If I do eventually get time and get #11 implemented then craft mounted lasters may become a thing.

**Comment by Julienc249** [comment]
Hello, I completely agree with everything you have said, however, the space elevator idea really seems amazing! I honestly have never done any coding but I really enjoy pushing minecraft to it's limits in Vanilla. If you ever want to check it out, I like making fully functional Star Trek Ships, with transporters and torpedoes, even shields! Although there are still some rough points I am trying to clear out. 

Back, to the space elevator, it could be interesting to make it deployable in a way, you arrive at a planet, deploy it and when you leave bring it back...  Then the warp core, I think it could be interesting to add a sort of radiation effect to it and make it a little bit more dangerous... As in, making such a powerful tool more realistic. Finally, I completely understand how you feel, I myself, am an student and although I love spending time digging through the features of minecraft sometimes, there just isn't enough time. 

Sorry, if I seem a bit pushy... these mods that mimic physics or mods like this made by people like you really get me excited! 

Good luck and Good bye! If I can help in any way please do not hesitate to send me a message, I may even learn to code for this mod!

**Comment by zmaster587** [comment]
Space elevators added

**Comment by CTH999** [comment]
Teleporters could work, but it would be for short range (100 km) Travel between [Ships](https://github.com/zmaster587/AdvancedRocketry/issues/11) And [Weapons+ Tools+ Combat+ Compatability ](https://github.com/zmaster587/AdvancedRocketry/issues/1156)
