### ISSUE TITLE
JourneyMap gets stuck on "planet"

### ISSUE THREAD

**Issue by drinfernoo** [zmaster587/AdvancedRocketry#421]
I can only assume that "planet" is a dimension registered by Advanced Rocketry, and there's an issue between it and JourneyMap. I'm running the latest versions of both, and when cycling through the available dimensions in JourneyMap's Waypoints screen, I get stuck on "planet" and can't change to the next one. If I back out and come back, I'll be back on my current dimension, but can never get past "planet".

I'm not sure if this is an issue with this mod or JourneyMap, but none of the other dimensions seem to have this problem.

**Comment by zmaster587** [comment]
I wonder if it has something to do with the fact all AR's dimensions are named "Planet".  Will look into when i can get time to do so

**Comment by ShicKla** [comment]
I noticed this issue as well. JourneyMap isn't actually getting stuck. It is a poor design choice on JourneyMaps behalf. You have to keep clicking the same button to go to the next dimension in the list. Due to Advanced Rocketry adding such a significant amount of dimensions it takes a while to click through the whole list. Simply put, there is not a bug with either mods and everything is working as intended. Just kinda sucks.

@drinfernoo I would recommend suggesting to the JourneyMap team, that instead of a single button that clicks through the list of dimensions. they use a drop down menu or something similar.

@zmaster587 I am not sure how much work it would be, but you could consider getting the planets dimension number as a string, then appending the string to the name of the dimension. Alternatively implement a method that you could use the console/chat to change a dimensions name. Obviously these options are contingent on that dimension names are not static.

**Comment by zmaster587** [comment]
@ShicKla would depend on how JourneyMap actually is getting the name, from what it sound like it may be getting it from the dimensionType object.  Unfortunately it does not seem like the getName() function can be overridden (short of ASM at least) which means rather than recycling the same one for each planet like I've been doing I'd have to create one for each, it seems kinda redundant, but is at the same time an unfortunate result of the modifications done to Minecraft.  (In 1.7.10 the world provider can return a name, the functionality has been replaced somewhere along the line between 1.8 and 1.10 with the dimensionType object.)  

I also fear registering one for each planet would increase the chances of a collision between AR and another mod may occur.  It might be something I could look into though.  No guarantees though.

**Comment by zmaster587** [comment]
I don't think this will be doable post 1.7 unfortunately
