### ISSUE TITLE
Water Flow in space causing huge TPS lag

### ISSUE THREAD

**Issue by SplitInfinitive** [zmaster587/AdvancedRocketry#430]
so this was a complete accident, turns out beds in space explode.  Go figure, but i had a water source block and some of the flowing water got into the vaccuum of space and now I can't do anything in space at all.

Forge TPS report says that dim -2 is running at a tick per 5k+ ms.

I somehow didn't think this was quite intended.

**Comment by zmaster587** [comment]
Do you have the allowPlanetRespawn set to true, was it a vanilla bed you used?  Did you place it in the space station or did you send it up in a module?  What version of AR are you currently using?

Beds are not really supposed to explode, but due to the way MC is coded for me to have access to what dimension the player is allowed to respawn in, beds also kinda explode.  AR is supposed to replace the vanilla bed with a less combustible version when placed by a player but...

That being said I'm not sure why flowing water in space is causing so much lag for you.  I've had flowing water in space before with no noticable change in tick rate.  Space also doesn't treat water any differently from the overworld except that i may try to flow down indefinatly, though that should not add more than a few us of overhead at most.  Would it be possible to use a profiling tool (visualvm, opis) and report the results here so we can see where exactly the TPS issue arises?

**Comment by SplitInfinitive** [comment]
I'm attempting to repeat the problem, but I'll answer your questions that I can.

I didn't touch any of the configs so I think allowPlanetRespawn is set to false (unless the default is true)

I placed a vanilla bed in my space station after constructing it, I was under the impression that it was supposed to replace it with an astro bed after I did so, so I used the bed (to see if I could set my spawn there) and it blew up.

Advanced Rocketry 1.0.12 (latest release version) as of posting.

The problem was that the water source block (as a result of the explosion) ended up flowing out into space and making that stupid endless waterfall thing so I did the responsible thing and rebuilt my space station and stopped the flow of the water.  The problem is that the water didn't follow usual minecraft water programming and tick down and away like it usually does.  It just jerked around in a circle mostly and caused a lot of lag.

I will get back to you with more data when I can

**Comment by zmaster587** [comment]
It is supposed to replace it with an internal copy of the vanilla bed, yes.  I've also been unable to replicate making the bed explode, which is even more confusing... I attempted this by:
1. Going to a space station and placing a vanilla bed in survival mode
2. Attempting to sleep in the bed, nothing happens
3. I rotate the station such that the sun is underneath
4. Attempt to sleep in the bed, sleep successfully.

I've tried this with "allowPlanetRespawn" set to true and false.  The only difference is that when the config is false the result of steps 2 and 4 are the same.

would it be possible to provide a screenshot of what you mean of the water jerking around in a circle would be helpful too.

Also do you have other mods installed and if so would you be willing to try placing and sleeping in a bed in a space station with only AR and libvulpes?
