### ISSUE TITLE
Possible issue with landing pad not functioning as expected on station

### ISSUE THREAD

**Issue by zmaster587** [zmaster587/AdvancedRocketry#447]
see https://github.com/zmaster587/AdvancedRocketry/issues/334#issuecomment-285384136

**Comment by hagfelsh** [comment]
Thanks!  If I can provide steps or debugging in greater detail, let me know. It's worth noting that i'm on 1.0.8 still--I need to upgrade but I have to push the change to all the users which takes quite a long time.

**Comment by zmaster587** [comment]
I meant to get back to this much sooner, but things started getting out of hand, would it be possible to check to see if you're having the same issue with the most recent version?

**Comment by hagfelsh** [comment]
Heya Z!  I'm running 1.7.10-1.0.13 now--seems that there's quite a jump in versions since I updated, and that was only a week or so back!  Most players are out enjoying summer right now, so I'm in a sort of maintenance window where updates are easier. I'll see about shoving 1.7.10-1.2.1 in and report back.  Thanks!

**Comment by zmaster587** [comment]
tested and appears to be working in latest builds.
