### ISSUE TITLE
Jerky rocket launch and skybox/stars/planet rotation movement

### ISSUE THREAD

**Issue by hagfelsh** [zmaster587/AdvancedRocketry#451]
Heya Z, I'm pretty sure this is not related to AR, but I'm hoping that you just happen to know what causes this (and maybe have ideas for solving, too).

As the subject describes it--you can observe the skybox on any planet anywhere and see the general ordinary movement of the stars or sun or whatever.  But every ~1 second or so it jerks back a few pixels, then proceeds forward once again on its usual speed.  

I suspect this has to do with tick rates or some other time-dependant stuff.  Do you happen to know what this is and perhaps how to improve it?  It really cramps the space station rotation feel!

h

**Comment by hagfelsh** [comment]
I just launched up to my station; this process usually proceeds pretty smoothly and ascent takes something like 20-30 seconds.  Descent to the station takes ~ 10.  But now.. .today.. Descent is over 3 minutes and counting.  The jerk-fest is crazy!

Worth noting that I'm playing on my server, which is upstairs connected at 1Gbps.  But still a server.  (It was a server yesterday too, though...)

**Comment by zmaster587** [comment]
Sounds like the server thread is running slow or you have a bad connection somewhere.  Though since it sounds like you're running it on a LAN it's likely not connection related.  I would suggest installing OPIS on both the client and server and trying to see what's taking up the most server tick time.  Alternately you could try running visualVM on the server, though visualVM is a bit harder to use.  Another thing you may want to look at is memory usage by the server.  If there's not enough memory allocated to the server it may be spending most of its time garbage collecting(if you set max hear to 2GB you're likely to be find unless it's a large pack or something).  It's also possible that the machine is swapping to disk which can take time.  But if it's a fairly modern system that is unlikely the case unless you have large programs running on it.

The amount of gravity you have set does not affect CPU cycles as gravity is just a multiplier for acceleration downwards (achieved by multiplying gravity by "Earth gravity").  Distance from space station is only currently used for rendering and won't affect server performance at all.  So I find it unlikely those two changes are related to the issue.

**Comment by hagfelsh** [comment]
Fantastic list of stuff to check through, thank you!  I'll start digging.  Much appreciated!

**Comment by hagfelsh** [comment]
I think this was caused by old hardware backing my minecraft instance.  I migrated the world in question to a minimal centos vm on a much more robust vmware host and ran the game out of a ramdrive with regular flushes to an ssd-backed disk.  Smooth as butter now :)  

Thank you for giving me so many places to investigate.
