### ISSUE TITLE
server console commands

### ISSUE THREAD

**Issue by Doughber** [zmaster587/AdvancedRocketry#461]
I added this mod to ftb sky factory 3 mod pack. It worked but i don't have permissions for the commands. From console I just get the message saying I dont have permission. I even tryed making my player admin and when I type in game I dont get message anymore saying I don't have permission.  I now just get nothing. Anyone know how to get commands to work in sky factory 3 mod pack? Not sure why it does not work even from server console.

**Comment by Doughber** [comment]
Oh yeah using latest release and even tried the latest alpha release for this mod

**Comment by zmaster587** [comment]
Most of the commands won't work from the server terminal because they require a player reference.  Though some of the commands still require a player even though they shouldn't (planet add and delete and things like that if memory serves).

That being said, if you're OP level 2 on the server you should have permissions to execute the commands.  It's possible that sky factory 3 has some permission system built into it that's interfering with vanilla OP.

I'll have to see if i can find a list of mods in the pack

**Comment by Doughber** [comment]
Ok thanks. Yeah settings set for level 4 I thought higher value was better. I will try lowering it. And yeah I was just trying to type help for the list of commands. I also think I tried the command to show planets list which also did not work again will try again later. I do have a list of mods but can't post at the moment. Will later. But I'm sure its a mod in this pack. I'm still trying to figure out what permissions mod its using or if its just something with forge. Will post again in 9+ hrs from now after trying what you said.

**Comment by Doughber** [comment]
Ok, you were right commands do not work in console. But when i made my player admin. I was able to generate a list planets.

But i do see some commands either are not finished or it's my mod pack. 
But commands like help still do not do anything.

Thank you again for helping me out here.
