### ISSUE TITLE
Docking stations

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#481]
Players complained that if the dock station, and then to fly on them is a bug. Station flipped, a part of blocks broken, and rockets have landed on each other.
![2017-03-29_15 27 59](https://cloud.githubusercontent.com/assets/3863970/24461213/e59ed346-14b9-11e7-903c-cf6c9e5d060c.jpg)
![2017-03-29_15 37 46](https://cloud.githubusercontent.com/assets/3863970/24461211/e4e71efe-14b9-11e7-8f3d-5e4fe33f9ac9.png)
![2017-03-29_15 38 28](https://cloud.githubusercontent.com/assets/3863970/24461212/e4ecfed2-14b9-11e7-8d24-9b0d7affb862.png)
Upon landing 2 rockets on the first is the flood in the console.

https://pastebin.com/kqUg8V4D  he continued until he removed the missile that the top

**Comment by zmaster587** [comment]
I dont quite understand what you're trying to show me in the second and
third images.

Second: what do you mean by that station is flipped? Are you saying that
some of the blocks are facing the wrong way or that the entire module is
facing the wrong way?

Also that error is really odd because the only thing that can be null on
the line indicated is worldObj which should not be able to happen in a tile
placed in the world unless something is screwed up with forge or ASM from
another mod

**Comment by denwd** [comment]
The second and third pictures show that when two stations were docked, part of one of them disappeared. In addition, one of the stations was turned over relative to the other (the one that remained whole).

**Comment by zmaster587** [comment]
What were the orientations of the docking pads on both the station and ground?

**Comment by denwd** [comment]
Probably, this is a mistake of the players.

**Comment by zmaster587** [comment]
The mod is supposed to orient the module such that the docking pad in the module faces the docking pad on the station

**Comment by denwd** [comment]
ok))  thanks
