### ISSUE TITLE
Machines Unloading (Slightly different than before)

### ISSUE THREAD

**Issue by sharkck** [zmaster587/AdvancedRocketry#497]
Not sure what's going on but I'm seeing this happen again. The machines are unloading. I have chunk loaders in the area where these are located. The only difference between this time and the last is that right-clicking on the machine does not fix it.  You have to go into the machine block itself and toggle the power switch off and back on to get it to 'wake up'.

**Comment by sharkck** [comment]
Just noticed something else regarding this... the first time you click a machine's main block (ie: cutting machine block) it does nothing.  The second time, it opens the GUI where you can toggle it off and back on.

**Comment by sharkck** [comment]
One more update.  Not sure how to trigger this issue yet... All I do know is that it has happened twice now during our session (no server restarts).

**Comment by zmaster587** [comment]
Definatly sounds like it's still being unbuilt.  Short of a block being broken or a chunk unloading it should be impossible.  Any way to verify the the chunkloader is not failing to load one of the chunks for some reason?

**Comment by sharkck** [comment]
I havent had time to play with it much... trying to get my first drone ship to launch... ugh... I'm using Extra Util's chunk ward (uses grid power) and, so far, nothing else seems to be affected.  Any suggestions on ways to test this?  I could try to add in Chicken Chunks 1.8 or something to see if it continues to happen?

**Comment by zmaster587** [comment]
I know there's an area near world origin that is garunteed to always be loaded with a radius.  You could try chicken chunks, if i remember right it does come with a utility to view loaded chunks.  So if the util indicates the chunks there the machines are is not loaded that'd be a good indicator that it's a chunk issue.  Multiblocks are very hard to get right with chunk loading because if there's any time where only part of it's loaded is very hard to distinguish from being incomplete, so single block machines are not normally affected by chunk loading issues, that's also the reason I wanted to know if the machine in question is straddling multiple chunks because if it's in the same chunk it should be unaffected by chunkloading problems.  You can check that with the F3 menu (one of the things shows what chunk you're currently standing in.)

**Comment by Tyrantin** [comment]
Also the Oxy Vent. I have to break and replace on server restart.

**Comment by zmaster587** [comment]
I think I nailed down the cause of the machines unloading.  When a chunk is unloaded for whatever reason the original tile is replaced with a copy.  Though this seems to be an issue with machines straddling a chunk.

As for the O2 vent, I'll look into it, but I'm fairly sure any issue with that is unrelated
