### ISSUE TITLE
Volumetric calculations taking a ton of time on our server

### ISSUE THREAD

**Issue by Saereth** [zmaster587/AdvancedRocketry#559]
We just switched over to volumetric instead of radius and we also moved to the threaded calculations (option 3). running a top in linux shows it at 680% cpu usage as compared to 95% or so before switching to this option. We've got the block size set to 24 from 32 as well. In the logs we also frequently see
[advancedRocketry]: Atmosphere calculation at zmaster587.libVulpes.util.HashedBlockPosition@2a49a56c aborted due to oversize queue!

Is there anything we can do to improve performance here besides lowering the block size more or switching back to radius?

Would it be possible in the future to see a configurable polling inerval for the oxygen mechanics, setting it to check far less often would be an acceptable sacrifice in realism vs playability for us for instance.

**Comment by zmaster587** [comment]
I believe i can improve the hashing function I'm using for hashed block which may speed things up.  I can also add a config that determines the maximum number of threads it's allowed to use.  The "aborted due to oversize queue" is basically a fancy way of saying "something is trying to recalculate atm on stations very frequently" which could come from something causing a constant block update, or multiple block updates.  Though if an area is already sealed and remains sealed after a block update, it should be a maximum of 6 checks which is lightning quick.  This leads me to beleive whatever it is is happening in an unsealed area.

I really want to avoid polling mechanics because in most cases that'll actually make it run slower and make the server likely to have sudden lag spikes.  

Would it be at all possible to run opis or visualvm on the server so we can get an idea of what the situation actually is?

**Comment by Saereth** [comment]
well its 1.10 so no opis unfortunately, I have warmroast but since it runs outside the main thread im not sure if that's going to pick that up, I could move it to the mainthread a bit to profile (option 2) tomorrow though and see what that finds

**Comment by zmaster587** [comment]
What i need to know in particular is where "zmaster587.advancedRocketry.util.AtmosphereBlob.addBlock" is being called from frequently.  That should be on the server thread somewhere.  The method itself won't take up much time because it just passes off to another thread.

**Comment by Saereth** [comment]
So I suspect the issue is a player had a block placer/breaker for processing ores triggering repeated recalculations. We ran into a similar issue today when someone decided to us an rftools builder to altar their base while the oxygen vent was active. This resulted in a total server deadlock and since it was chunkloaded it had to be edited out. Here was a screencap of the profiler at the time:
http://imgur.com/a/OgXj2

**Comment by zmaster587** [comment]
Alright, hopefully this particular issue would be fixed by a modification
to the hashing function for blockpos.  The algorithm currently used results
in a lot more collisions in certain circumstances than a more improved
algorithm I've been using in another project as of late.  I'll port it
later today and post a build.  If you would be able to test and report back
on performance difference I would greatly appreciate it.  I'll post here
when I push the build

**Comment by zmaster587** [comment]
Can you try with this version of libvulpes and see if it helps?
AR 1.1.x builds: http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_10/
AR 1.0.x builds: http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/MC1_10/

**Comment by Saereth** [comment]
This does seem to help quite a bit

**Comment by zmaster587** [comment]
But does it get timin down to a reasonable value?

**Comment by Saereth** [comment]
it does seem so, similar activity with builders wand etc didnt spike the server tps like it was, thats a bit anecdotal but additionally the profiler showed it as vastly reduce by about 75% of what it was.
