### ISSUE TITLE
Low TPS causes precision assembler to stop working

### ISSUE THREAD

**Issue by Jemsuper** [zmaster587/AdvancedRocketry#594]
Sorry if its already reported. I noticed that on the server i am playing it is often 15-10 tps. Sometimes even lower. During these times crafting something in the precision assembler gets around 2/3 then just stops. The machine even though still on looks like is doing nothing. Turning it off and on again turns it on again, the progress resets to around 1/2.

**Comment by zmaster587** [comment]
Is it only the precision assembler doing this or are all the machines doing this?

**Comment by Jemsuper** [comment]
For now i only noticed it being this machine but maybe because it is so slow. (only have an golden engine in it). Other people on the server confirmed the same

**Comment by zmaster587** [comment]
Can you confirm if it actually stops processing the recipes?  I'm wondering if maybe it's just going slow and the client is not being updated.

**Comment by Jemsuper** [comment]
I can confirm and multiple people can. I have often tried to just wait but even after a minute it didnt finish. Only restarting it did

**Comment by zmaster587** [comment]
So if you hook pipes/hoppers up to the machine it never produces anything even if you wait a few mintues more than normal?  I'm asking because I'm trying to determine if the machine is still running on the server even though the client thinks it stopped.  
From the sounds of it the machine finishes on the client, but because the server is running at 50% speed it takes 2x as long on the server to process, so the client sees it stopped until it forces the server to send an update packet and I'm trying to verify if that's consistant with what's happening.

**Comment by Jemsuper** [comment]
I am sadly unable to currently check, if i remember i will go check for it tomorrow again. I was personally using the machine without pipes connecting to it. And yes the progress bar stops, it even just disappears (as if the machine isnt doing anything). 

As far as i remember the machine would not finish the recipe without manually restarting the machine. 

Also i remember the client not seeing the machine to have finished. With low tps the machine also looked slower and sometimes bouncy (going back and forwards a millisecond all the time) in visuals. It then stopped around 2/3 for the client. 

This is all from memory i will have to try again once i can

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
