### ISSUE TITLE
Rolling machine in Alpha 1.1.7

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#598]
![2017-04-30_20 11 38](https://cloud.githubusercontent.com/assets/23413915/25564249/baaa4954-2de1-11e7-8048-cc145d1dfc75.png)
I try to set the rolling machine，but even if it's same to what the holo projector displays，it's still unsuccessful。

**Comment by zmaster587** [comment]
What direction is the controller facing?  Is it facing away from the input hatches?
if so, when you right click it, where does the red X appear?

**Comment by forestbat** [comment]
@zmaster587 Oh，the face must be correct……I‘m wrong。
But I think machines should have more correct faces。

**Comment by zmaster587** [comment]
What do you mean by more correct faces?

**Comment by forestbat** [comment]
@zmaster587 I mean,now the correct controller facing has only one,or mistake will happen,so I hope the facing of machine shouldn't decide if the setting of machine is right--see Woot by ipsis,the facing of the mob factory must be right,it will trouble players.

**Comment by zmaster587** [comment]
Due to the way structures are handled the result could be ambiguous depending on the direction a machine is facing.  EX: Trying to build machine A and B next to each other, both machines have similar configurations, forming machine A may use machine B's blocks preventing machine B from forming.

The holo projector should be indicating the front of the machine, however I see in the screenshot there it is not. I'll see if i can figure out why
