### ISSUE TITLE
Luna Missing For Players

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#614]
Hey Zmaster, 

I've been getting reported issues of players downloading the modpack, building a rocket, and then unable to actually see Luna as a destination:

https://github.com/Darkosto/InvasionIssues/issues/224

AR: 1.1.6
LibVulpes: 0.2.2
Forge: 2281
MC: 1.10.2

Can I leave this config option set to:     B:resetPlanetsFromXML=true ?

Thanks for checking into this!
Darkosto

**Comment by zmaster587** [comment]
See #587 
There was a bug where having the initial dimid of planets above 255 caused some problems with a botched backward compat handler turning all planets into gas giants on server.  I suggest updating to 1.1.7 where the bug has been fixed for a while.

As for setting B:resetPlanetsFromXML=true, that should be fine.  It'll change itself back to false once the galaxy is reset/on first full world load since being changed.  Though setting to true will delete the surface of AR worlds.  But considering the nature of the issue I do not think it'll be a problem.

**Comment by Darkosto** [comment]
Okay, my dev version of the pack is always on latest as it is updated to 1.1.7, sounds like I don't need to worry about changing the config then. Thanks!
