### ISSUE TITLE
Space suit and other armors

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#622]
If players wear armors stronger than space suit，such as quantum armor or draconic armor，or only they don't want to wear space suit，how will they live on other planets before they make atmosphere terraformer？

**Comment by zmaster587** [comment]
There's no real reason you cannot swap between the armors in a base somewhere that has an O2 seal.

Though if you're suggesting some kind of compatibility layer so that armors from other mods can be used in a vacuum, I can try to add some sort of config option that allow full sets of certain armors to bypass vacuum damage

**Comment by Divineaspect** [comment]
That would be wonderful.

Alternately can we get  some environmental baubles to allow us to sacrifice "other" slots instead?

**Comment by zmaster587** [comment]
what do you mean by environmental baubles?

**Comment by forestbat** [comment]
A bauble which is taken by player and consume electricity or sth. else to protect player from vaccum？ @

**Comment by zmaster587** [comment]
For organization: https://minecraft.curseforge.com/projects/advanced-rocketry?comment=1214

Also what about the idea of an enchantment for armor that would allow a player to breath in space.  Could be applied in same machine like the chemnical processing plant.  Could make it like the armor is being treating with some airtight chemical or something

**Comment by forestbat** [comment]
For an enchantment，making a machine is not so good——why not use respiration or make adjustment on it？

**Comment by zmaster587** [comment]
I don't want to use something already in vanilla because they already have their own function elsewhere and get applied in different ways.  In vanilla respiration is a more magicy solution.
I say enchantment because the enchantment system is already built into the game and does not require a seperate subsystem.  Though for actual lore/in-game logic, it won't be so much of an enchantment so much as some 'seal' put on the armor, which is where the machine comes in.  I'm just trying to think of some way to do this that's easy on the user, easy on me, and works (mostly) universally.  It would probably call it "Air Tight" or something.
The bauble could be an alternative, but that seems more like a magicy or end game solution.  Putting armor inside the spacesuit may run into some issues with certain armors like quantum, because quantum has other effects like speed boosts that would not get processed if it's in something else.

**Comment by forestbat** [comment]
Thanks for your airtight。
