### ISSUE TITLE
1.10.2-1.0.18-19 Crash issue when loading on a old world.

### ISSUE THREAD

**Issue by SFort** [zmaster587/AdvancedRocketry#626]
I updated Advanced Rocketry and LibVulpes on a server on which players are actively using the mod.
This crash does not occur in a backup of the same world before the mod was originally added.
Crash: [Pastebin](https://pastebin.com/t70kfGJS)
Advanced Rocketry:  1.1.7  -> 1.0.18-19
LibVulpes:   0.2.2 -> 0.1.19-12

**Comment by zmaster587** [comment]
You're essentially trying to backport from an unstable and very different version of the mod to an older build.  I cannot say I'm suprised it crashed, but I cannot garuntee backward compatibility with world due to the massive changes that have occured between the two builds.

I can patch this issue but there may be a lot of other things that crop up going backwards.  Hence the minor version change rather than just the build number.

**Comment by zmaster587** [comment]
Forgot to specify repo.  For organization: fixed by commit 1425e86e5463b8db877523890c2507c0d17e3f98

**Comment by SFort** [comment]
Apologies i just assumed that the Jenkins version would be the latest.
and semi panicked when i saw that there might be a world corrupting bug (fa51c0907f2f63640631df8a327c4eff776b8ca1)

**Comment by zmaster587** [comment]
It's a really really rare issue that's been around since probably the initial 1.10.2 update.  It could have also been the fact that I am constantly screwing with my dev world in ways MC worlds are not meant to be broken.  As far as I'm aware it's never occured outside of my test worlds since I've not seen any reports of it yet so I wouldn't be too worried.

Also the jenkins are indeed the latest builds.  You just ended up pulling from the stable (1.0.x) branch rather than the alpha branch (1.1.x/1.2.x).
If you're wondering, this is where the alpha builds are: http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets1_10/
http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_10/
