### ISSUE TITLE
I lost my rocketry

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#627]
I want to come to the dimension sol-17，but when the rocket enter it，the game stopped on altitude 1000 for a long time and the whole system became very lag，so I must kill JVM。
And the next time I enter the game，the rocket is lost with its space station ID chip，I am in the space not sol-17.
This is the second time I lost my rocket，and the biome I land in sol-17 is brushland in BOP。
[fml-client-latest.txt](https://github.com/zmaster587/AdvancedRocketry/files/995720/fml-client-latest.txt)
So what happened let the dimension boomed？

**Comment by zmaster587** [comment]
If you had to actualy kill the JVM, it sounds like it was either low on memory and constantly garbage collecting, or it was chugging trying to generate terrain.  Also I would suggest not using the +UseG1GC and rather using +UseParallelGC, the G1 garbage collector performs very poorly relativly. ( See https://www.optaplanner.org/blog/2015/07/31/WhatIsTheFastestGarbageCollectorInJava8.html ) and is probably not helping the situation.  Also when you say you ended up in space, at what coordinates did you end up at?  Are you going from the station to sol-17?  If so, if you go to sol-17 at the same location you took off from, check to see if your rocket is at 1000 at sol 17

**Comment by forestbat** [comment]
Yes，I went from station to sol-17，but if I enter sol-17，the game was stopped and I can't see anything except sky。So I can't check if the rocket is at 1000.

**Comment by zmaster587** [comment]
Can you attempt it again but keep an eye on memory usage and verify it's
not running low on memory?

**Comment by forestbat** [comment]
The same situation happened in sol-30，and the memory cost in the end is 5630MB，when I allocated 6144MB to JVM。
[fml-client-latest.txt](https://github.com/zmaster587/AdvancedRocketry/files/999058/fml-client-latest.txt)
This is the log of the time。

**Comment by zmaster587** [comment]
I'm kinda confused, in the most recent log you allocated 5120 MB for heap in the VM with the argument "-Xmx5120m".  Whereas your initial report you were using 6144MB for heap space  you're also still using the G1 garbage collector in that run ("-XX:+UseG1GC").

Though that being said it is reporting 2GB being free just before world load and I find 2GB for world load is a bit of a tall order unless you've gont some crazy mods being loaded.

Would it be at all possible to use a profiling tool such as https://visualvm.github.io/ or https://github.com/sk89q/WarmRoast and run a CPU profile when the world hangs so we can get an idea of what's being executed?  Alternatively, if you want to send me a copy of the mods, configuration, and the world/advRocketry folder I can run the same tests on my end.

**Comment by forestbat** [comment]
[snapshot-17.zip](https://github.com/zmaster587/AdvancedRocketry/files/1003243/snapshot-17.zip)
These are CPU profile snapshots during  sol-17 loading。
[fml-client-latest.txt](https://github.com/zmaster587/AdvancedRocketry/files/1003250/fml-client-latest.txt)

**Comment by zmaster587** [comment]
I cannot open the zip file with an unsupported operation error using unzip or 7zip, what did you use to zip the files?

**Comment by forestbat** [comment]
winRAR。

**Comment by forestbat** [comment]
WinRAR。

**Comment by zmaster587** [comment]
Alright, thanks, got it extracted using the rar module for 7z

**Comment by zmaster587** [comment]
I'm not 100% sure when these snapshots were taken, but there's definatly some serious time being put into world generation for all 3 of these.

Though at this point I'm not sure if you're even having a memory problem or if world gen is just taking forever.  If that's the case then the symtoms would makes sense.

So what I think is going on is that the computer is spending most of it's time trying to generate the world so ticks are taking a really long time to perform.  Because the rocket's position is controlled on the server (in this case an integreated server it seems), if the server is spending all its time generating, then the rocket isn't really going anywhere, or doing so very very slowly.  It might help if you turned down your view distance or if you tweaked/removed some world generating mods.  (snapshots 4 and 5 it looks like mo' creatures is doing quite a number, I'm not sure if there's some config to reduce spawn rate but...).

**Comment by zmaster587** [comment]
Doens't really look like there's much I can do to fix this issue, so i'm going to close it.  The loss of the rocket can likely be explained by how MC saves chunks when not shut down properly.
