### ISSUE TITLE
About 1.7.10

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#658]
Now the version 1.7.10 is too old，and now you're developing 5 versions（1.7-1.0.x，1.7-1.2.x，1.10-1.0.x，1.10-1.2.x，1.11-1.2.x），I think AR in 1.7 cost your energy too much。
So do you agree to abandon 1.7.10？

**Comment by FangedHex** [comment]
Also, it's maybe time to move on to the latest version ? I mean backport is still possible to 1.10 because it's popular now. But the final choice is the modder choice, I just give my opinion on that case :)

**Comment by zmaster587** [comment]
@FangedHex I do have a 1.11 build out, which is the latest as far as I'm aware.

I'm not really a fan of abondoning 1.7.10.  But it does cost me a lot of time to keep backporting stuff.  I've been considering abondoning 1.7.10 after the latest content update, but I've not mentioned that publicly before now.  I've still not made a final descision on it, but at this point it seems likely considering I already struggle keeping up with the volume of issues coming in.

**Comment by BurovB** [comment]
Сan I ask you not to throw backporting for 1.7.10, because she is still very popular and more stable than the new version?

**Comment by FangedHex** [comment]
One thing @zmaster587 look at the Mcjty's compat layer maybe it can useful for you for doing the backporting between 1.11 and 1.10 instead of doing "2 versions" of your code. I don't know if this api can help you but it's working, he's using it for all his mods so he can focus on coding stuff instead of thinking about the porting part :)

**Comment by forestbat** [comment]
@FangedHex It will make mods depend on compatlayer，we don't like too many prepositions。
@BurovB 1.7 has passed，we should accept new ages——we can't save a dying bluewhale。

**Comment by FangedHex** [comment]
@forestbat I don't like dependencies too but if the workload can be lowered, it's better for the modder :)

**Comment by zmaster587** [comment]
@BurovB It's not something I really want to drop, but at this point I've got almost 100 unresolved issues on the issue tracker that I've not yet been able to sort out.  I simply do not have time to maintain everything.  That being said, I do plan on continuing to fix bugs that come up in the 1.7.10 builds and I still plan on implementing the content update in the 1.7.10 builds (IE all the planned features for 1.2.x).  But beyond that, if I do choose to officially drop support (I've not yet made up my mind), the newest features may not make it into the 1.7.10 builds anymore.

@FangedHex between 1.10 and 1.11 there's really not much difference anyway, definitely not enough to warrant a compat layer, the worst I've come across so far is the renaming of worldObj -> world ( idk why they cannot settle on a name, it seems to switch back and forth every few builds) and the fact itemstacks can no longer be null.  Other than that it's copy/paste, or rather git --cherry-pick.  Not to mention people already have to download libvulpes, so I don't really want to add another extra layer for not very much effort saved.

@forestbat The sad thing is that @BurovB is really not wrong.  1.8+ has increased the computing requirements to run the game significantly, even to the point where several of my friends literally cannot run the game at a playable framerate seemingly due to massive increases in memory and CPU usage.  The change from 3 primitives for xyz location to instantiating a class for every change in location referenced was not very CPU or memory friendly in particular.

**Comment by Kin37ix** [comment]
I would argue that 1.7.10 is still the most popular build and will be for a while given that 1.12 is just around the corner. Many many popular mods are missing in these versions and the gap seems to be getting wider.

**Comment by FangedHex** [comment]
@zmaster587 Really strange, it's the inverse for my friends and me. The 1.7.10 is unplayable at a correct framerate (We had 20-30fps) and now on the 1.10.2 & 1.11.2, we got 100+ fps, I think we have "PCMasterRace" computers that why and a lot of minecraft players have a potato computer :(

**Comment by BurovB** [comment]
@zmaster587 What do you think about transferring development to 1.7.10 to someone else?

**Comment by zmaster587** [comment]
@Kin37ix given download numbers for AR at least, I'd disagree that 1.7.10 is THE most popular build.  It's still fairly popular though and I suspect you're spot on for the reasoning.  *cough* forever waiting on thaumcraft *cough*.  

@FangedHex I think it strongly depends on what the bottleneck is.  1.8+ takes advantage of the graphics card a lot more than 1.7 did, but ends up using more CPU and memory resources.  So if you have a powerful CPU and a half decent GPU moving to 1.8 would give you an fps boost.  But if your CPU isn't up to snuff, particularly in single threaded performance, you'd suffer from a performance loss.  Or at least this is what I've observed.  Meanwhile I just sit around 16 to 30 fps no matter what build I'm running.

@BurovB Perhaps if somebody volunteered, I don't know of anyone in particular that would be interested in taking over development of 1.7.10.  Though by the same token there's absolutely no reason people cannot submit pull requests if they want to help out without taking responsibility for part of the project.

**Comment by FangedHex** [comment]
@zmaster587 One tip about the memory issue, I use FoamFix(http://asie.pl/Projects/Minecraft/Mods/FoamFix/) in my modpack, it remove the shitty code made by Mojang and the most problems due to Java : for myself, I was able to go from 3GB used to 1.5-2GB for 100 mods :)

**Comment by zmaster587** [comment]
@FangedHex foamfix is useful, though I've found that it's still not enough to get resource usage back down to 1.7.10 levels.  Also it does not remove the bad code in minecraft, is tweaks some of the code, though some of the nastier stuff is still left behind because it is used in so much of the code.  But foamfix does address some of the less pervasive things such as excess resourced allocated by the resource loader which is where most of the gains in memory are made I suspect.

**Comment by TheGuyRunningSouth** [comment]
Another option if you're running Windows 7 or newer (maybe Vista, not sure)
is to buy a USB flash drive at least 4GB or bigger and use it with Windows
ReadyBoost. I've used it before for some heavier packs and it works pretty
well.

**Comment by zmaster587** [comment]
Ready boost is for speeding up access to small files because flash drives (like SSDs) have much faster seek time than a conventional disk because a conventional disk requires time to move a physical arm, but it's still much much slower than physical RAM.  

Readyboost is good for launching small apps and reading small files, though as swap space it performs rather poorly in comparison and you'd get better performance out of swapping pages to a 7200RPM disk than a flashdrive over USB 2.0.  That being said it may work better with USB 3.0 and a fairly new flash drive though, but that would also require a new computer anyway.
