### ISSUE TITLE
Indicate somewhere that water is required for Assembler

### ISSUE THREAD

**Issue by pyure** [zmaster587/AdvancedRocketry#661]
Ideally display this requirement in JEI, or failing that as a general tooltip for the block.

**Comment by zmaster587** [comment]
Assembler?  I'm not aware of any precision assebler recipes that require water?  Do you mean the rolling machine?

**Comment by pyure** [comment]
I'm on a roll for idiocy today.  Yes, I mean the rolling machine.  No I have no idea why I said Assembler.

**Comment by zmaster587** [comment]
I feel ya there.

I could probably just move the water requirement into the recipe which would then make the water show up in JEI, right now it's not actually part of the recipe and is handled directly by the machine because the water requirement was added before fluids were supported by the AR recipe system.

**Comment by pyure** [comment]
Makes sense.  That would be great.

**Comment by zmaster587** [comment]
Fixed in b635e17ea4344a8b2f29c8dc0a63abf291f7f5b7
