### ISSUE TITLE
Oxygen Vent works without power and C02 Scrubbers work without Cartridge.

### ISSUE THREAD

**Issue by Kin37ix** [zmaster587/AdvancedRocketry#667]
MC version 1.7.10, AR version 1.2.0c and LibVulpes version 0.2.3. The config file is all default settings except AR dimensions are set to start at ID 500+ (Space Station is still -2). I should add that I was switching back and forth between creative and survival for testing on a space station.

Excellent mod by the way.

**Comment by zmaster587** [comment]
Thank you, glad you like it!

Though I regret to inform you that I cannot replicate the issue where the CO2 scrubbers work without the cartridge, if I take a cartdrige out I begin taking damage within a few seconds (I also assume there's no O2 in the vent itself during this test due to the fact that the vent will work by design without the scrubbers when fed O2).  Though I did notice if the power it cut it switches between oxygenated and unoxygenated rapidly.

**Comment by Kin37ix** [comment]
I made a quick video though I'm not sure how helpful it will be. These were "new" blocks cheated in from NEI. [https://ufile.io/r7dx9](url)

**Comment by zmaster587** [comment]
Can you try this build and see if it still occurs?  If you do get a chance to test, you may want to make a backup  There have been some significant changes between builds.
http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_7/lastSuccessfulBuild/artifact/output/LibVulpes-1.7.10-0.2.4-13-universal.jar
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets7_10/21/artifact/build/libs/AdvancedRocketry-1.7.10-1.2.1-21.jar
