### ISSUE TITLE
Hydrogen tanks combined

### ISSUE THREAD

**Issue by Arkeus121** [zmaster587/AdvancedRocketry#671]
When there are two hydrogen tanks in the modular suit chestpiece The GUI does not recognize the second and will not update the GUI when this happens, Happens also with oxygen.
Great work on the mod though, love it so far. =)

**Comment by zmaster587** [comment]
If you don't mind me asking, how exactly did you test this and what version of MC/AR are you using?
Reason I ask is that if both are full or both are empty there wouldn't be any change in the UI.  Though if one were half full and the other completely full, then if it's functioning properly I'd expect to see the UI at 3/4 full, though if there's a problem, then I'd expect to see the UI completely full or only 1/2 full.  I do not intend to be rude, but just wanted to verify up front though because I think trying to get as much info as possible at once will save time for both of us.

**Comment by Arkeus121** [comment]
After testing a little it seems to work sometimes, not sure what makes it tick though.

**Comment by Arkeus121** [comment]
the way it seem to glitch out is that when i had two tanks and one was 1/2 full while the other was full the display read out 1/2 full.

**Comment by zmaster587** [comment]
do you have any other mods installed that add hydrogen as a fluid?

**Comment by Arkeus121** [comment]
Nope, but i've just been testing it and it started to occur less and less, now not at all, not sure how but it's fixed itself, if it happens again and i find out why, i'll let you know. It may have just been a glitch, sorry for any inconvenience.

**Comment by zmaster587** [comment]
Alright, thanks for reporting it anyway.  I'll close the issue for now, if you can find a way to replicate it post back here and we can reopen the issue and get to work fixing it.
