### ISSUE TITLE
Helmet susceptible to certain damage?

### ISSUE THREAD

**Issue by Arkeus121** [zmaster587/AdvancedRocketry#673]
The helmet appers to take damage from falling blocks e.g. sand and gravel.

**Comment by zmaster587** [comment]
Tested with Advanced Rocketry (1.2.x) for MC 1.10.2, MC 1.11.2, and MC 1.7.10.  The code for damage hasn't changed since stable 1.0.x.  While wearing a  full suit I let sand and gravel fall on my character and let the character sustain several hits of damage without seeing any change in the helmet.

If you have other mods installed, can you replicate the issue with the mods removed.  Otherwise can you describe some kind of setup where I can replicate the issue?

**Comment by Arkeus121** [comment]
I am currently unable to test without the mods as I don't have access to my PC but when I found this issue I was using the invasion mod pack, this may mean that the mod that enables all blocks to fall like sand or gravel could have something to do with that. I was not playing with any extra mods.

**Comment by zmaster587** [comment]
It very well may be some interaction from the mod allowing other blocks to fall.  If I were to take a guess, rather than calling damage on the player, its modifies the meta of the armor directly.  I'll see if I can identify the mod in the pack (I don't actually know the name of it).  
In light of that, when you do get a chance I would appriciate if you could test with all the other mods except the one that adds falling stone before trying with only AR and libvulpes.
