### ISSUE TITLE
[1.11.2] Failing to process an Asteroid chip in the observatory

### ISSUE THREAD

**Issue by DestinyPlayer** [zmaster587/AdvancedRocketry#676]
I have a 200 distance fully powered observatory with 385 Dist, 647 Comp and 294 Mass. It is night time, it is opened, and I have an Asteroid chip inside of it. I select an asteroid and press the Process Discovery button. Nothing happens, nothing at all. The observatory is placed in a Superflat world.

All I have in terms of mods are Waila, Wawla, JourneyMap, JEI and Advanced Rocketry.
Forge 12.20.0.2310
AdvancedRocketry 1.11.2-1.2.0f
LibVulpes 0.2.3b

Anything else I need to upload for info? It doesn't seem to leave anything related to the problem in the log. Or to the mod itself, in fact.

**Comment by Leaveleaf** [comment]
click the like gear's button.→_→

**Comment by DestinyPlayer** [comment]
Well yeah, that's what I'm clicking, duh. It's the button that shows you the Process Discovery tooltip. Doesn't work.

**Comment by Sh0oter** [comment]
I've got the same problem

**Comment by DestinyPlayer** [comment]
https://youtu.be/lcx9QlZN-gE
Decided to straight up record a video that shows off this issue.
Forge 12.20.0.2310
Advanced Rocketry 1.11.2-1.2.0f
libVulpes 1.11.2-0.2.3b
Just Enough Items 4.3.6.282

Literally no other mods.

**Comment by Leaveleaf** [comment]
Try to use only one data interface, I used only one in 1.10.2

**Comment by DestinyPlayer** [comment]
Still doesn't work. Besides, how am I going to put in the other two types of data if one data interface can only hold one type of data?

**Comment by zmaster587** [comment]
In 1.10.2 minecraft uses null to signify an empty slot, in 1.11.2 the isEmpty() method must be called on an itemstack to check if the slot is empty.  So what ended up happening is I basically missed one in the observatory.  When pressing the processing button it was checking to see if the output stack was null before proceeding and in 1.11.2 slots can never contain null.  But I've verified this issue is fixed for next release.

**Comment by DestinyPlayer** [comment]
Thank you!

**Comment by zmaster587** [comment]
No problem!
