### ISSUE TITLE
Extinguished Torches turn to normal torches

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#688]
Minecraft 1.10.2
Forge 2297
AR 1.2.0c
libvulpes 0.2.3

When breaking an extinguished torch on a planet with normal atmosphere, it turns into a normal Minecraft torch. Is that the intended behaviour? If yes, can there be a config option added to change that as it doesn't make a lot of sense to me. I appreciate it. Thanks in advance.

**Comment by zmaster587** [comment]
Breaking an extinguished in any situation is intended to drop a normal minecraft torch.  I'm going to have to say I don't really see any point to having them drop extinguished torches, because in minecraft the player doesn't have to light the torch as it is and I'd like to keep it consistant.  In addition to that it seems like it would just be annoying to require the player to light the torch again.

If you really want I can still add a config for it though, but I thought I'd explain the logic first.

**Comment by davqvist** [comment]
Okay, then I misunderstood the point of extiguished torches. It just didn't make thematic sense to me that you place an extinguished torch and it magically lights itself. I would like to add the option in my pack to add a recipe to light them, but then I need a seperate mod that prevents placing them. If you don't want to add such a config option, fair enough. Was just a suggestion, maybe you even could add a recipe to light them if you want to. Let me know if you would consider adding such a feature.

**Comment by zmaster587** [comment]
I can add it as an option then
