### ISSUE TITLE
Faction and GriefPrevention Claims disappear every restart?

### ISSUE THREAD

**Issue by GoatMog** [zmaster587/AdvancedRocketry#690]
I made claims on a planet, but they keep on disappearing. Is there a way to fix this?

**Comment by zmaster587** [comment]
I don't know if there's a way to fix it or not, but I do know it's certainly not an issue with advanced rocketry.  There's likely some foulup with how GriefPrevention is storing or loading its own settings for extra dimensions.  The only thing I can think of that where AR could have an impact could be the fact it saves dimensions in world/advRocketry/DIM* rather than world/DIM*.  But even if that is the case it's still an issue with GriefPrevention.
