### ISSUE TITLE
[1.10.2-1.2.1] Satellite Builder UI Item Slots Broken(?) & Broken Space Station Assembler

### ISSUE THREAD

**Issue by CaptainB52** [zmaster587/AdvancedRocketry#702]
The satellite builder is connected to power and everything checks out until I try to put in the empty satellite chassis in. The only things I can put into the slots are the Satellite ID chips into the correct slot and I can put anything into the IO slot just to the right of the power indicator. I can't put the satellite chassis in the bottom, I can't put the optical sensor in the top, I can't install memory chips into the lower IO slots and I can't install modules into the module slots. 

I'm running Advanced Rocketry version 1.10.2-1.2.1 and libVulpes 1.10.2-0.2.4

**Comment by Leaveleaf** [comment]
1.7.10-1.2.1 have this bug too.

**Comment by zmaster587** [comment]
I think this is more of a graphical issue than anything, the IO icon in the top left slot was actually a placeholder for a satellite icon that I forgot to actually put in.  You should be able to have something like the following:
![image](https://user-images.githubusercontent.com/3536685/27016796-43177944-4ef1-11e7-82f5-44a1f173bc9c.png)

**Comment by Leaveleaf** [comment]
!! But I can"t put anything into it
![tim 20170612100317](https://user-images.githubusercontent.com/19620848/27016913-bafba57e-4f56-11e7-8ea7-91472c07de7c.png)

**Comment by zmaster587** [comment]
Do you have an empty chassis in the top right slot?

**Comment by Leaveleaf** [comment]
yep,they are empty,
![image](https://user-images.githubusercontent.com/19620848/27017727-29a208f0-4f5d-11e7-8452-ff4a62569ebd.png)
![image](https://user-images.githubusercontent.com/19620848/27017711-0cd448a0-4f5d-11e7-954b-818f8e866be3.png)

**Comment by zmaster587** [comment]
Try putting a satellite chassis into the top left slot, the behavoir of the machine has been modified so that the upgrades go directly into the satellite in a manner similar to steve's carts.  When trying to test this out I did notice it was not showing up in the vanilla creative menu in 1.7.10 (this is patched for the next build), so you may need to spawn the satellite in via NEI, the give command, or just crafting it.  (The item is advancedrocketry:item.satellite if memory serves)

**Comment by AlphaNovaLight** [comment]
ya u have to put the chassis in first then the rest will go in properly

**Comment by Leaveleaf** [comment]
Oh ,thanks,I can't get chassis at 1.7.10,and can you join create power at 1.7.10

**Comment by zmaster587** [comment]
you should be able to craft it or spawn it in with the give command, like I said in my last post, I forgot to put it in the vanilla creative UI in 1.7.10.  Also turns out to not be in NEI because I forgot to remove it there too... what a day...
Anyway this recipe in the crafting bench should work even though it doesn't show in NEI in this build:
![image](https://user-images.githubusercontent.com/3536685/27018834-7c778246-4f01-11e7-8edf-6764631c3dee.png)
The things on the top and bottom are aluminum sheets.

Also what do you mean by can i join creative power in 1.7.10?

**Comment by Leaveleaf** [comment]
yep,like 1.10.2 creative power

**Comment by zmaster587** [comment]
Backported the creative battery
