### ISSUE TITLE
Mystcraft infinite profiling bug

### ISSUE THREAD

**Issue by DamnuDen** [zmaster587/AdvancedRocketry#723]
Greetings, not sure what causes this problem, the point is that when i installed AR at my game client, important notification i ve Mystcraft there (lastest) at the begining of the game, mystcraft doing its profiling thing as usual, but it s geting stuck at aprox 1/3 of the profiling progress bar, i tryed 2 keep pc over night, so mby it s problem with mystcraft logic, but all others mods working fine, and i m not quite sure what causes it, coz game isn`t crashing, it s just keep profiling forever, i m not sure what info from me u require to check what s reason of that or even if it s AR or mystcraft but i would appreciate if u would at least check this out. 
Here is my Forge log if it helps u either way.
Den.
[fml-client-latest.txt](https://github.com/zmaster587/AdvancedRocketry/files/1075468/fml-client-latest.txt)

**Comment by zmaster587** [comment]
This may seem like a strange request, but what happens if you allocate less memory to java (say around 4 or 5GB)?  I'm wondering if the profile ends up causing the JVM to allocate a lot of memory and then paging memory the system doesn't have.  

If you allocate a lot of RAM to java it will sometimes just allocate more memory now and not run a GC to free up memory until later.  But if you've allocated as much memory to java as your computer has (or even 1GB less) it can cause problems.

**Comment by DamnuDen** [comment]
Thanks for response, as i said i also thought that it might be coz of memory, i m giving to java 6gb ram ddr 4, it s prety much never full, i ll try to remove gc for 1 loading, i just duno why AR causing this while i made this client heavy previously, and mystcraft was working good. I ll report any progress as i test.
Den

**Comment by zmaster587** [comment]
One theory I have is that it's constantly loading AR worlds for profiling them, and because I have them setup to unload when no in use, it may be loading and unloading 20+ worlds repeatedly while profiling.  Loading worlds in MC is a rather expensive process so...  I don't know if this is the case for sure, more of a potshot than anything.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
