### ISSUE TITLE
Chisel blocks (like laboratory blocks) don't seal oxygen?

### ISSUE THREAD

**Issue by Mrminesheeps** [zmaster587/AdvancedRocketry#758]
I'd like to know if maybe blocks from the chisel mod can be sealed, It would be awesome because it'd make building space stations so much cooler. Just a question, curiosity struck me.

Would be great if that was fixed tho, kind of unfortunate since my friend built a station and they didn't seal.

**Comment by dcbartlett** [comment]
Please provide your minecraft version and mod version numbers.

I am using chisel blocks on over 3/4 of my station and it seals fine.

MC Version 1.10.2
Mod Version 1.2.2

**Comment by Mrminesheeps** [comment]
odd, I was told that Chisel didn't seal. it's possible they were referring to Chisel and Bits... .-. Well thanks for the info.

**Comment by Mrminesheeps** [comment]
Hmm. seems they don't seal.

Minecraft version 1.10.2
Chisel mod version 0.0.11.25
Advanced Rocketry version 1.2.2

**Comment by dcbartlett** [comment]
I'll load those up and test it.  I know chisel and bits definitely does NOT seal.

**Comment by dcbartlett** [comment]
I did look at my config, and i don't have any special settings for chisel blocks...so investigating some more.
```
sealableblockwhitelist {
    # Mod:Blockname  for example "minecraft:chest" [default: ]
    S:general <
     >
}
```

**Comment by dcbartlett** [comment]
My chisel version is 0.0.10.22 so this may be the difference?

**Comment by Mrminesheeps** [comment]
Idk. My problem is, why doesn't he use a sealing system relevant to that of galacticraft's? that was WAY more efficient and accurate .-.

**Comment by duncanwebb** [comment]
Chisel mod blocks seal a space station, slabs don't. I had a floor from slabs and when I replaced them for blocks it sealed.

**Comment by Mrminesheeps** [comment]
No slabs were used in my station.

**Comment by dcbartlett** [comment]
@Mrminesheeps i agree that the sealing system isn't as friendly as galacticraft's is.  This however, isn't galacticraft and he probably has a reason for not doing it that way.  I wish that the sealers were stackable, because they are not, i just turned my sealing radius up to 128 so i can make hugh rooms (Currently building Deep Space 9).  As far as blocks that make it sealable, Both myself and @duncanwebb have stated that the chisel blocks DO seal a room as long as the room is not larger than the sealing radius, and as long as they are full blocks. 

By chance, how large is your room in blocks, and is the oxygen vent in the center or against a wall.  This is important as the seal has a maximum radius and adding a second vent to the room will not help.  I would look in the config of your pack, but i think the default seal radius is 32 blocks.

You can see the documentation for the oxygen vent here -
 http://65.78.115.159:8000/AdvancedRocketry/blocks/OxygenVent.php
```
By default, the Oxygen Vent can only fill a square radius of 32 blocks. However if the atmosphereCalculationMethod is set to use volume based calcuations, the Oxygen Vent can fill up to 32,768 cubic blocks.
```
In your case, it may be easier to seal the room with the volume based algorithm, This will check the volume of the room itself i believe, rather than doing it in a radius fashion.  Thus, if you make a 3 x 3 room, and stick it in a corner, it should seal that room based on it being 9 cubic blocks rather than "withing the radious"  The sealing capability is very generous in the volume based mode.  the 32,768 blocks will seal roughly a 32x32x32 room.  If you need more rooms, you'll need to make walls with doors and put a vent in the other rooms.

**Comment by Mrminesheeps** [comment]
I did move my oxygen system into the center of my room, and it did seal. Thanks to all you guys!!

**Comment by dcbartlett** [comment]
No Problem.
