### ISSUE TITLE
World ID conflicts with RFTools Dimension worlds

### ISSUE THREAD

**Issue by mike-potter** [zmaster587/AdvancedRocketry#793]
I tried installing Advanced Rocketry on an existing single-player FTB Beyond instance.

I changed the conflicting Space Station ID from -3 to -66 and that allowed me to load my world.

However, I also have several RFTools Dimensions, and now when I visit existing dimensions, like my mining dimension, it looks like I'm going to an Advanced Rocketry planet instead.

I don't see any config to change the planet IDs.  Is there any way to make this co-exist with existing RFTools worlds?  I'd really love to play with rockets, but can't give up my RFTools dimensions.

**Comment by mike-potter** [comment]
To answer my own question, I found the planetDefs.xml in the advRocketry folder of my Saves and was able to edit all of the various planet IDs listed there.  I just added 100 to all the values (except Earth).  Not sure how large the world IDs can be, but you might want to default to something that doesn't easily conflict with another mod.  I can get back to my RFTool dimension now, and will assume this fixes the issue although I guess I won't know for sure till I travel to another planet and see what happens.

**Comment by Bysokar** [comment]
The planet defs is 100% configurable... its all on us to sort this one out. 
If your using the random generator in advancedRocketry.cfg there is a setting to set the minimum dimension ID. Hope this helps.

```
    # Dimensions including and after this number are allowed to be made into planets [range: -127 ~ 8000, default: 2]
    I:minDimension=2
```

**Comment by zmaster587** [comment]
If Advanced Rocketry is added at the same time as or before RFTools, generally there is no conflict, unfortunatly adding AR afterwards is a much trickier edgecase, while it is possible to change the starting value of the world, it may also reduce useable range for people that just want to spawn some very large number of planets and run, since it is configurable I don't really see it as a big deal to change.  I do appricate the suggestion though.
