### ISSUE TITLE
[1.7.10] Rocket dupe issue

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#795]
This only happens when someone use a rocket to return to the space station from a planet other than the overworld, you get two rocket on the station instead of one. 

P.S.: might be a thermos issue, but could you add some sort of additional check for this?

**Comment by denwd** [comment]
Confirm, also repeated

**Comment by denwd** [comment]
Up

**Comment by denwd** [comment]
The player arrives at the station on the rocket. Flies with the station to another planet. Sits in a rocket on this planet. He returns on the same rocket back to the station, but for some reason the player himself is not in the rocket, but under it (visually). The rocket sits down, the player rejoins the server and is in the rocket (as if everything is normal), but under that rocket there is another rocket (a copy).

**Comment by denwd** [comment]
Please test only through the server

**Comment by zmaster587** [comment]
It's been confirmed to be a thermos issue, unfortunatly it'd be fairly hard for me to figure out what is causing the issue and I have very little time.  Since at this point in time I'm only supported forge and I've got several 100 issues in line, it's going to be a while before I get to fixing thermos compat stuff.
