### ISSUE TITLE
Suggestion: multiplayer support

### ISSUE THREAD

**Issue by Trinsdar** [zmaster587/AdvancedRocketry#828]
Is it possible to add the abillity for more than one person to ride a rocket given there are enough seats?

**Comment by zmaster587** [comment]
It should be possible in 1.10+, though until I think it time to officially discontinue 1.7 ( which will likely be soon) im trying to maintain the same featureset.

**Comment by choum33** [comment]
oh no please, we are many to play 1.7, many mods are not compatible with 1.10...

**Comment by Divineaspect** [comment]
You should ask more of the authors of those mods to update then. I'm excited about loading a pile of us in a rocket in 1.12.

**Comment by choum33** [comment]
Sadly i think about Gregtech that will never be updated to new minecraft version :(
Many other smaller mods are very goods but finished and will not be redevelopped to new versions ...

**Comment by Thutmose** [comment]
Here a sample of some existing code for having more than 1 player seated on a entity made from a multiblock structure: https://github.com/Thutmose/ThutCrafts/blob/master/src/main/java/thut/crafts/entity/EntityCraft.java

If @zmaster587 gives me the OK, I look into stripping out just the multiple-seat section of that mod, and attempt to integrate it into the rockets.

**Comment by Thutmose** [comment]
I am working on getting this functional for the pokecube-advanced rocketry support: 
![image](https://user-images.githubusercontent.com/2363472/31977152-77d7280a-b909-11e7-9da6-3d21f05b58f8.png)
So far I have it mostly functional for travelling to/from moon, just a few minor bugs to work out (players falling off when going to moon, players in wrong seat client-side when returning to overworld), but once it is done, the code will be available for seeing if it is feasible to add to AR as well for rockets.

**Comment by Thutmose** [comment]
All of the bugs I had found with the multiple players riding to/from moon are fixed, I also managed to fix the chisel and bits rendering support on my elevators, so I suspect a very similar fix will work for the rocket rendering

**Comment by zmaster587** [comment]
@Thutmose does that functionality work in 1.7.10, or only 1.8+?

**Comment by Thutmose** [comment]
I have only tested it in 1.12, it will only work 1.9+, as it uses some of the vanilla methods for multiple passenger stuff, as well as some of the datamanager stuff added in 1.9

For transfering them between worlds, the main important thing is to move the mount, then the next tick or so attempt to move all of the riders, and re-mount them in the correct order, I use this for that:
https://github.com/Thutmose/Thut/blob/1.12.x/ThutCore/src/main/java/thut/api/entity/Transporter.java#L75-L136

I then use this for the seat management: 
https://github.com/Thutmose/Thut/blob/1.12.x/ThutCore/src/main/java/thut/api/entity/IMultiplePassengerEntity.java

the pitch is only needed if you want the mount to be able to pitch over in flight, for the pokemob I don't return anything for that, and the yaw is only needed if the mount needs to rotate, I just return the renderYawOffset for that.

Here is my implementation:
https://github.com/Thutmose/Pokecube/blob/1.12.x/Pokecube%20Core/src/main/java/pokecube/core/entity/pokemobs/helper/EntityMountablePokemob.java

I have it limited to 10 seats atm, but you can probably expand that to quite a bit, since the new datamanager allows for 255 or something values, any more than that and you will need to make your own packet for syncronizing seats and locations.  Currently you will need to run the same initialization for seats on the server and client side, though since you have to send the location of the blocks for rendering anyway, that shouldn't be a problem, just look through the blocks in the initSeats method and make one for each seat there.

The only other thing not in one of those 3 classes is this line in the mod class to register the dataserializer:
https://github.com/Thutmose/Thut/blob/1.12.x/ThutCore/src/main/java/thut/core/common/ThutCore.java#L111

**Comment by BeaNeaLol** [comment]
Issue is alive? Can I move more than one player in a single rocket?

**Comment by dmodoomsirius** [comment]
yes. it has been in for a little while now. https://github.com/zmaster587/AdvancedRocketry/commit/d94841152f7efb199d0c2e8d9d01878bfc3eacea
