### ISSUE TITLE
Crash with orbital laser drill and other things.

### ISSUE THREAD

**Issue by brianvis** [zmaster587/AdvancedRocketry#837]
Hello!
On my server. TechHaven I have some problems with advanced  rocketry.
First of all. Whenever I fire an orbital laser drill it won't shoot at all, and when I try to take out the lens it immediately crashes my game and gives a Java exception.
Same thing for rockets. Whenever I try to put in a chip, satellite bay or anything else in a made rocket it crashes my game with Java exception, this only happens the 2nd time I open up any module in the rocket. I also cannot go into the rocket gui when I'm in it.

Second is that the crystallizers don't work. It does not transfer dilithium. 

Thanks!

**Comment by zmaster587** [comment]
I have no idea what's going on without a crash report or a stack trace at minimum

**Comment by brianvis** [comment]
I'll get a crash report asap

**Comment by Janrupf** [comment]
It could be the same problem as #827 (With crashreport ;))

**Comment by zmaster587** [comment]
I'm not thinking so, the issue with #827 is that the observetory (and station control block) have a dynamic number of slots, so if the client and server get desynced, they may have a different number of slots and when the client/server update each other it may run out of bounds.  The laser does not have this issue, though it is possible the rocket might even though the rocket is (supposedly) impossible to desync because upon building or loading the whole structure gets send and cannot be modified without building it again.

**Comment by zmaster587** [comment]
Space laser and electrolyser confirmed fixed at this point, will look into the rocket tmmr

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
