### ISSUE TITLE
1.7.10 copy rocket

### ISSUE THREAD

**Issue by fogss** [zmaster587/AdvancedRocketry#878]
Dup of a rocket
1) Create a space station and fly to it.
2) Create a warp core on the space station.
3) Go to the orbit of any planet at the station.
4) Sit on that planet in the rocket.
5) Fly back to the station on the same rocket. At this step, problems.
The player appears in orbit under the rocket, hi disconnects from the server, reconnects again. In this case, he is in a rocket and sits down regularly. But! After about 10 seconds, a copy of the rocket with the same resources lands on top.
This works on the latest versions of any server core for 1.7.10.

**Comment by zmaster587** [comment]
Since you did not list what versions you tested with, I must ask did you test it with version 1.2.4?

**Comment by fogss** [comment]
Good day, the core was the thermos and kcauldron and cauldron
AdvancedRocketry-1.7.10-1.0.19b.jar
LibVulpes-1.7.10-0.1.20-universal.jar

**Comment by fogss** [comment]
Try the free version AdvancedRocketry-1.7.10-1.2.4.jar LibVulpes-1.7.10-0.2.6-universal.jar the same thing
![2017-10-22_20 57 53](https://user-images.githubusercontent.com/3863970/32141991-d984e020-bcaf-11e7-9930-a2f39658c35e.png)

**Comment by fogss** [comment]
When flying back to the station from the planet, I was under the rocket, go to the game menu and enter again to the server as a result of 2 missiles down

**Comment by zmaster587** [comment]
does this occur without thermos or cauldron, and only using forge libvulpes and AR?
Thermos and Cauldron are known to cause some weird issues.

**Comment by fogss** [comment]
what kernel I have to do the test?

**Comment by zmaster587** [comment]
just forge, with the  AdvancedRocketry-1.7.10-1.2.4.jar LibVulpes-1.7.10-0.2.6-universal.jar and nothing else

**Comment by fogss** [comment]
forge-1.7.10-10.13.4.1614-1.7.10-universal 

On a clean forge the nucleus of all normal, but I can't use no support for plugins on all other cauldorn , kcauldron thermos .. the bug is. I will work with any of these kernels. Since with this bug it is impossible to use it on the server.

**Comment by fogss** [comment]
forge-1.7.10-10.13.4.1614-1.7.10-universal    no bugs
cauldron   bugs
thermos bugs
kcauldron  bugs
fffork   bugs

**Comment by fogss** [comment]
link  http://www.tcpr.ca/downloads/thermos

**Comment by fogss** [comment]
good afternoon when can we expect a fix?

**Comment by fogss** [comment]
UP

**Comment by zmaster587** [comment]
Unfortunatly, it's unfair for me to fix issues involving an API I've repeatedly said I do not support when there's 100+ issues that are on a supported API that are still outstanding.  Thermos changes a lot of things in forge and I'd have to deciper what exactly it changes before I can even begin to work on a fix. 
So to answer your question on when a fix can be expected, that depends on how much free time I get to work on the mod and how much help i have with fixing existing issues on the platforms that are supported.

I am also supporting 4 different versions of minecraft concurrently, 1.7 being the oldest version and it is very difficult for me to even get a few hours a week these days to fix issues.  Unfortunatly because of the above it may be a while before I can fix this issue.

**Comment by fogss** [comment]
very much waiting for

**Comment by fogss** [comment]
really looking forward to people playing not fair(

**Comment by fogss** [comment]
Up)

**Comment by dmodoomsirius** [comment]
Stop trying to bump this. Zmaster will get to this when he is able.
