### ISSUE TITLE
[Suggestion] CraftTweaker Support

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#879]
Heya! 

Thanks for updating to 1.12.x!

Would you consider adding CraftTweaker support for your machines?
https://github.com/jaredlll08/CraftTweaker

**Comment by gdarai** [comment]
It would be definitley more convinient for the modpack authors, but it is not necessary since you can set up each and every machine recipes via internal format. So I would not see it as a big priority for the mod author.

Question is if the format he set up supports NBT or such custom things like damaging, I believe not. In that the MT3 is surely much better.

**Comment by NillerMedDild** [comment]
I wasn't aware there was an internal way to make recipes, woops ^^'
