### ISSUE TITLE
[1.11.2/1.12.2] Observatory doesn't observe.

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#897]
Minecraft Version:
- 1.12.2 (and also 1.11)
Forge Version:
- tested on 2517
LibVulpes Version:
- 0.2.6-7
Explain issue in detail:

It seems the processComplete method for the observatory isn't implemented in 1.11.2 (and therefore 1.12.2 as well, since that was the base for the port)

The 1.10.2 branch does this: https://github.com/zmaster587/AdvancedRocketry/blob/MC1_10/src/main/java/zmaster587/advancedRocketry/tile/multiblock/TileObservatory.java#L135-L146

whereas it is blank in the 1.11 branch, was something to be changed there for 1.11? or was it just not implemented during the update?
https://github.com/zmaster587/AdvancedRocketry/blob/MC1.11/src/main/java/zmaster587/advancedRocketry/tile/multiblock/TileObservatory.java#L212-L214

I also noticed that the 1.10.2 (and 1.7.10) versions call the super.onUpdate method here:
https://github.com/zmaster587/AdvancedRocketry/blob/MC1_10/src/main/java/zmaster587/advancedRocketry/tile/multiblock/TileObservatory.java#L111-L114

whereas the 1.11 version did not.

**Comment by zmaster587** [comment]
The Observetory's function was changed between MC1_10 and roundplanets1_10 so that it no longer provides data.  This was done between the satellite was a cheaper option anyway and the Observetory's function made more sense if it was for asteroid discovery given input data.  So since everything is now user input driven, there's no need for an update function save animating opening and closing of the dome.

**Comment by Thutmose** [comment]
Closing this issue, since the observatory is functioning as intended (other than #917)
