### ISSUE TITLE
[1.12.2] Dilithium doesn't spawn

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#908]
Minecraft Version:
- 1.12.2
Forge Version:
- 2517 (or any other)
LibVulpes Version:
- 0.2.6-7
Explain issue in detail:
Dilithium doesn't seem to spawn around, I tried adding a printout for the coords it attempts to spawn a cluster in, and it didn't show up there either, so I assume something has gone wrong with the generator used, and it is being sent invalid coordinates

**Comment by gdarai** [comment]
try some advanced confirmation like... worldStripper mod.
Also... should dilithium spawn in the overworld at all? Isn't it asteroids and Moon only sort of thing?
Check it out in the setting.
If you want, god mod for ustomization of the oregen to your needs is CoFH core. Wery easy to understand and works like a charm.

**Comment by Thutmose** [comment]
I had stuck a printout here: https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/world/ore/OreGenerator.java#L74 to see where it was trying to spawn the ore, then when I went to the location it printed, there were no ore clusters to be seen, so I suspect something has changed with WorldGenMinable.generate, and either needs chunk coordinates, or possibly relative block coordinates rather than the absolution block coordinates to spawn the ore correctly

That method also indicates that it should spawn very rarely in overworld, and very abundantly on the moon.

**Comment by zmaster587** [comment]
Are the other ores also not spawning?

**Comment by astocky** [comment]
Just ran a quarry across 200 chunks on luna and did not get any diluthium. Got some (but seems like much less than I expected of the other metals). I also ran a JER profile across 10000 chunks and didn't get any dilithium either. Pastebin here:
https://pastebin.com/jaQSuuxJ

**Comment by Thutmose** [comment]
The other ores use your custom ore generator which works fine, dilithium uses a different one.

I suspect the dilithium that spawned in that tiny amount was all near 0,0 as if my suspicion is correct, it will only be able to spawn in or near that chunk with the blockpos sent to the generator

**Comment by zmaster587** [comment]
Dilithium uses the same ore generator, it just a special case because it spawns differently on the moon so it's not passed to the method, since it doesn't support a different spawn rate.  It could be modified to do so, but that's less effienct.  Both call the same generate function https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/world/ore/OreGenerator.java#L38 and line 76.  Second.  I can't replicate the issue, it's spawning fine on the overworld at least.

**Comment by astocky** [comment]
Using the following (default configs)
Forge 1.12.2-14.23.0.2517
AR 1.12.2-1.2.5a
JEI 1.12.2-4.80.111
JER 1.12.2-0.8.5.26
LibVulpes 1.12.2-0.2.6

I used the fill command to remove all stone blocks and there was no dilithium. I also ran JER on 10000 chunks and all the ores except dilitium and iridium spawn on the overworld. Although I can't see anything that looks like an error in the logs.

**Comment by EmosewaGamer** [comment]
![image](https://user-images.githubusercontent.com/25333164/32405164-ea00c888-c15f-11e7-8498-8ab89221c80f.png)

- I derped in the first result
- The second result is how many of all the LibVulpes Ores there are
- The third result is how much Dilithium Ore there is

 If everyone (myself, everyone on this issue page, people playing my pack) can reproduce this, either you've managed to fix it without realizing on your side or there's an issue with the version that's on CurseForge. This bug is reproducible 100% of the time.

**Comment by zmaster587** [comment]
I suppose It's possible it was fixed accidently.  I'll try using the curseforge build and see if i can replicate it with that.

**Comment by zmaster587** [comment]
I was able to replicate the issue in the curse forge build.  Still no idea why there's a difference though.  Will post back with updates.

**Comment by zmaster587** [comment]
Turns out to be somthing funky with libvulpes's ore registration, somehow the entry for dilthium block has become null.

**Comment by zmaster587** [comment]
Was a loading order issue.  Advanced rocketry was registering ores with the material system in preinit and libvulpes was registering in the registerblock event call.  Libvulpes should have been registering first (libvulpes depends on AR) but was not because the register block is called after preinit

**Comment by Daihok41** [comment]
I know this has been closed but was wondering if this issue had been fixed im still not finding any dilithium in my worlds.

**Comment by DarVillous** [comment]
Daihok41, it looks like the issues was fixed on Nov 4th, but Curseforge still shows the LibVulpes-1.12.2-0.2.6-universal.jar from Oct 22, 2017 and AdvancedRocketry-1.12.2-1.2.5a.jar from Oct 31, 2017.  So it appears the fix hasnt made its way to curse yet.

**Comment by zmaster587** [comment]
you can find the latest builds here for now http://65.78.115.159:8080/ I'll likely be pushing to curse sometime this weekend however.

**Comment by Daihok41** [comment]
Sweet thanks. Will use the ones ya linked for now should at least get it spawning then if anything does change when added to curse will re-download.

**Comment by EmosewaGamer** [comment]
The weekend is almost over... I'd like to release a completable major version of my pack.
