### ISSUE TITLE
[bug] Warp Engine Consumption + Mid Flight Redirection

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#923]
Minecraft Version:
1.10

So I am going on with my experiments and I decided to test out how much fuel the warp engine consume.
And Guess What I discovered that from time to time, it does not consume a thing.

**Test conditions:**
I set Dilithium fuel efficiency to just 1
    # How many units of fuel should each Dilithium Crystal give to warp ships
    I:pointsPerDilithium=1
Simply to see the ratio working.
I Seleted a target cca 80  fuel away in the warp controller. I put 80 dilithium into the warp core and jump and when I arrive I selected the previous target and jump back... and again.

**Observations:**
- On one Warpcore fuelling it allowed me to do 2 - 3 jumps. Each time I waited up until the warping effect ended and I was hovering above the new planet. If the warp controller said that it is ready for jump, I did anoher jump. If it said that it is not, I conscidred it empty.
- When the Wapcore is empty again, it is not enough to give it 70 dilithium, it needs again the full 80 pieces. I tried with 10 pieces chunks.
- When I am in the middle of warp, I can select a different target in the warp controller and the ship is redirected there no matter if I have the required artefact in the Controller or not.

**Hypothesis:**
- Sometimes it consumes the fuel, sometimes it does not. Maybe I was able to make the second jump before the game realized that it should consume the fuel.
- The Redirection in the middle of warp should not be allowed.

**Comment by zmaster587** [comment]
When you make the second jump in the middle, it definatly won't consume fuel because it still thinks it's in the same jump, it's just the variable containing the destination planet has changed and it only actually reads it when it 'leaves the warp field' (which is really a planet id that is hardcoded, has no dimid and no graphics and special handling).

I've fixed the redirect in midwarp.  A return got commented out for some reason.  Probably some debug thing I forgot.

I did some testing after fixing the midwarp redirect and fuel seems to be being consumed proprly.  I did also add a visual indicator, so now you'll see a number tell you how much fuel you have left starting in the next build.
