### ISSUE TITLE
Block IDs in space station corrupted

### ISSUE THREAD

**Issue by john01dav** [zmaster587/AdvancedRocketry#924]
Minecraft Version:
- 1.10
Forge Version:
- 1.10.2-12.18.3.2477-universal
LibVulpes Version:
- 1.10.2-0.1.19-universal
*is this the latest curseforge build?* Probably not, I am using the Age of Engineering modpack, so this sort of thing is completely outside my control.
Crash Report: NA
Explain issue in detail:
I run a server with the Age of Engineering modpack and one of my player's space station has had what appears to be a block id swap, with some blocks becoming others, and console spam from forge about those sorts of things not matching up. Is there some easy fix to this? If not, how are the stations stored so I can roll back this station from a backup? I found that they seem to be in DIM-2, but I can't get a clear idea of how many/what stations are in each region file. I can provide the region files and other relevant data if that is useful in fixing this issue. 

EDIT: Apparently the areas that were affected are areas that are force-loaded by a custom Sponge mod.

**Comment by zmaster587** [comment]
Space station worlds are stored in the world/advRocketry/DIM[whatever dimid the space stations use, usually -2].  They're stored like any other dimension in minecraft so whether or not they can be restored depends on if you have backups setup and how exactly the damage was casued.  In the temp.dat file there's a list of stations and their respective coordinates, from there you can plug the coords into a block to region file on a site like http://dinnerbone.com/minecraft/tools/coordinates/ or you can do the math by hand.

Unfortunately, again due to the fact AR stores space stations like any other dimension in minecraft and therefore uses the vanilla block store/load methods for everything.  I don't think there's really much to fix unless some block/entity in AR did the corrupting and that can be pinpointed.

**Comment by john01dav** [comment]
@zmaster587 Thanks for your help! I have one question, when I rollback the region file (I do have backups), will other stations be affected, or is there only one station per region file? If other stations are affected, I may opt to use mcedit instead, otherwise, I'd rather not make things a ton harder. 

Regarding the block corruption, would this possibly be caused if the custom Sponge mod is frequently adding/removing a chunk load on some of the chunks in the station, preventing AR from doing some sort of logic as the chunk is loaded or unloaded? 

Once again, thanks for the really fast reply!

**Comment by zmaster587** [comment]
the stations are larger than a region by default with the same amount of space in between, so you should be ok with just replacing the region.  They can span multiple regions however (station size is 1024 by default).  I've never actually checked nor did i design it such that there are not two stations per region, so im only about 90% sure.

As for the block corruption, I don't think that's the case either because AR doesn't do anything on chuck load/save.  Originally it was going to be used to store O2 info, but that idea was scrapped before a built with O2 was released.  The commented code might still be there i don't remember.  More on topic, the only event of the load/save sort is that AR has is a global save event that runs when the overworld saves (writes to the dat and xml files to store things like satellites, planet heirarchy and composition, space station data such as fuel, planet orbiting rocket landing locations, no block stuff though.).  If that were interrupted the only damage would be to the solar system layout and/or loss of satellites.

**Comment by john01dav** [comment]
Thanks for all the help!
