### ISSUE TITLE
Gas Giants are not registered as dimensions, but have a DIMID listed in the xml, This causes conflicts if another mod registers that ID.

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#934]
I noticed that gas giants don't register their dimid, but still have a dimid listed in the xml, which then allows other mods to register that ID.  Will this cause any conflicts with such mods?

I ask because when I created a secret base with pokecube (makes a pocket dimension) forge said it could use dimid 4, which in the xml was listed as for one of the gas giant planets.

I also noticed that it was assigning the high pressure atmosphere to the secret base dimension, as it was giving mining fatigue and slowness.  These effects then persisted client side after leaving the dimension

**Comment by zmaster587** [comment]
The dimid is also used internally as the planet id, but it's easier to externally label as dimid, I do plan on seperating them eventually, ( it's under the enhancement tag on issues somewhere ).  But since there's no surface there's no real need to actually register with forge.

As for the effects persisting after leaving a high pressure atm, I'll look into that when I get a chance, it should be a 5 or 10 second effect applied every tick while inside the high pressure atm, so it should run out on its own even if it's not killed by the atmosphere change.  Something would have to be reapplying it otherwise.

**Comment by Thutmose** [comment]
I suspect the issue is here: 
https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/atmosphere/AtmosphereHandler.java#L54

there should probably be a check there for whether you actually registered the dimensions or not, as currently gas giants return true for isNativeDimension, so whenever another mod used that dimid, the AtmoshereHandler still applied to it.
