### ISSUE TITLE
Server stall on EntityRocket

### ISSUE THREAD

**Issue by cjm721** [zmaster587/AdvancedRocketry#937]
Minecraft Version:
-  1.12.2

Forge Version:
- 14.23.0.2529

Advanced Rocketry Version:
- 1.2.5a

LibVulpes Version:
- 0.2.6-universal

Stall Report:
- https://gist.github.com/cjm721/72907bcee766ced9ac7edfa31c2dfbe4  Have quite a few all same stack trace.
----------
Explain issue in detail:
Don't know what the player did but whenever the entity is loaded server does not tick again (Watchdog could not even kill it (catching the interrupt event it looks like?)).

Pulled up the NBT data for the entity in question. It has 524288 entries in the infrastructure tag.

**Comment by zmaster587** [comment]
It doesn't appear to be halted, just taking a long time.  Considering that trace shows a call that could involve memory allocation, I'm wondering if you've nearly exhuasted memory resources on either the VM or the host since adding 500,000 objects to a hashmap shouldn't take all that long.  That could also screw with timing of the watchdog thread if the VM is spending most of its time running a GC.  Would it be possible to elimate that as a possible cause and in the meantime could you send a copy of the rocket NBT for me to analyze?  Either way, that many entries in the infrastruture tag still indicates something went wrong.

**Comment by cjm721** [comment]
Not hitting memory memory limits. 

Here is just the entire region file for it. Chunk is -48,38 (16,6 local)

[r.-2.1.zip](https://github.com/zmaster587/AdvancedRocketry/files/1464279/r.-2.1.zip)

**Comment by zmaster587** [comment]
Well, as it turns out it hangs NBT editors too.  Looks there needs to be a check to make sure it cannot add the same object twice to the coordinate list

**Comment by zmaster587** [comment]
appears fixed, gonna close it for now
