### ISSUE TITLE
[1.12.2] Satellite Launch rockets stalling at max altitude

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#950]
Minecraft Version:
- 1.12.2
Forge Version:
- 2517
Advanced Rocketry Version:
- 1.2.5a-22
LibVulpes Version:
- 0.2.6-11
Explain issue in detail:
Sometimes when launching sats, the rocket re-lands at some random looking location nearby, oftenhowever, it stalls at max altitude as shown in the rocket monitoring station:

![image](https://user-images.githubusercontent.com/2363472/32987171-9290f87c-ccb1-11e7-8ef5-5d7f2f8b0f2f.png)

Using the command `/tp @e[type=advancedrocketry:rocket] @p`  will teleport the rocket to you.

**Comment by zmaster587** [comment]
The rockets are supposed to come back after launching sats at a nearby random location.  What i think may be happening is that the rocket is being moved to an unloaded chunk and getting stuck there because it can no longer tick.  If you load the chunk it should come down, however that really shouldn't be neccessary

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
