### ISSUE TITLE
Advanced Rocketry adds extra texture noise

### ISSUE THREAD

**Issue by qrwe1100** [zmaster587/AdvancedRocketry#972]
Minecraft Version:
-1.7.10
Forge Version:
-10.13.4.1614
Advanced Rocketry Version:
-1.7.10-1.2.5
LibVulpes Version:
-1.7.10-0.2.6
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
Tried to add Advanced Rocketry to a custom modpack some friends and I are playing, we all noticed that the trees and grass became much more grainy and full of noise.(Pictures included) Tried with a fresh install of just AR and it did the same thing. The blocks that are in the foreground look fine but the farther away you get the worse it looks. It is much easier to see when zoomed in.  Thanks for the help

With AR
![with ar](https://user-images.githubusercontent.com/22180175/33460845-0f172678-d5fe-11e7-9aed-e71b9ab1ca18.png)
Without AR
![without ar](https://user-images.githubusercontent.com/22180175/33460856-18d4b36a-d5fe-11e7-8448-4e87de72c6e1.png)

**Comment by qrwe1100** [comment]
Friends how found that a temp fix if turning graphics, specifically mipmap and anisotropic filtering. My pc cant run on that so that fix wont work for me.

**Comment by danielm59** [comment]
this may be related to #925

**Comment by zmaster587** [comment]
Is mipmapping in video options the same for both images?

**Comment by zmaster587** [comment]
Mipmapping off in both photos.
I've verified that with mipmapping it's also identical with or without AR though I've not posted images for the sake of bandwidth.   Perhaps it got fixed in the middle somewher, I'm not sure, but it does not appear to be an issue now.

With AR:
![image](https://user-images.githubusercontent.com/3536685/34648288-8549256a-f365-11e7-9c99-346b035c3784.png)
Without AR:
![image](https://user-images.githubusercontent.com/3536685/34648290-8c48bc54-f365-11e7-8f32-2c40a08158a8.png)
