### ISSUE TITLE
crash chemical reactor

### ISSUE THREAD

**Issue by nonenothing** [zmaster587/AdvancedRocketry#984]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2555
Advanced Rocketry Version:
1.2.6-33
LibVulpes Version:
0.2.7-19-universal

https://hastebin.com/enunajiqiv.css

Explain issue in detail:
Crash when start filling fluid input - every time.

**Comment by Hexogenx** [comment]
https://hastebin.com/jacewutala

Basically the same bug but some more info:
Filled Oxygen and Hydrogen from Nuclearcraft into the Fluid Inputs, Fluid Inputs correctly display Oxygen and Hydroxen inside. Turned machine on, instant crash of both client and server.
The worst part is that the server crashes instantly on start now because the machine is still turned on, which means you have to restore an older backup.

This also means you cannot progress in Advanced Rocketry because Rocket Fuel cannot be made.

Minecraft Version:
1.12.2
Forge Version:
14.23.1.2562
Advanced Rocketry Version:
AdvancedRocketry-1.12.2-1.2.6-5
LibVulpes Version:
LibVulpes-1.12.2-0.2.7-19-universal

**Comment by zmaster587** [comment]
Can you upload a copy of the config/advRocketry/ChemicalReactor.xml file?

**Comment by zmaster587** [comment]
#982

**Comment by nonenothing** [comment]
> config/advRocketry/ChemicalReactor.xml file and a copy of the fml-server-latest.log or fml-client-latest.log?

Already - archive in elevator issue.
If you update mods - world will crash.

**Comment by jonabrv1965** [comment]
Hello. I just found this glitch (as soon as I started to pump oxygen in the chemical reactor, the MC crash and render my world unloadable... basically I have to restore a backup... and stuck with this great mod!) I downloaded the latest version not to avail : AdvancedRocketry-1.12.2-1.2.6-37, LibVulpes-1.12.2-0.2.7-20-universal.

I'm using the electrolyzer from this mod (I do have mekanism but opted to use the AR machine to avoid conflicts), the electric pump form mekanism and fluid ducts from Thermal Expansion/Dynamics (because I can cover them :-). If you need anything just let me know.

**Comment by jonabrv1965** [comment]
Here an excerpt from the crash log : 
Time: 12/16/17 4:07 PM
Description: Exception in server tick loop

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at zmaster587.advancedRocketry.tile.multiblock.machine.TileChemicalReactor.onInventoryUpdated(TileChemicalReactor.java:73)
	at zmaster587.libVulpes.tile.multiblock.hatch.TileFluidHatch.fillInternal(TileFluidHatch.java:129)
	at zmaster587.libVulpes.tile.multiblock.hatch.TileFluidHatch.fill(TileFluidHatch.java:98)
	at zmaster587.libVulpes.cap.FluidCapability.fill(FluidCapability.java:23)
	at cofh.thermaldynamics.duct.fluid.DuctUnitFluid.transfer(DuctUnitFluid.java:177)

**Comment by JennyLeeP** [comment]
I am also getting this crash , Same as above. 
Crashes the server, and client in single player mode.
Can provide more info if needed.

**Comment by sshagent** [comment]
Same for me, on advanced rocketry 1.2.6-37.jar  and forge-1.12.2-14.23.1.2570
I've got a pastebin if useful

https://pastebin.com/N9re1qNv

**Comment by zmaster587** [comment]
Should be fixed next build with commit in #997
